import type { GuidanceBeat } from "./guidance";

const ASSISTANT_PRESENTER_ID = "presenter/assistant";

const OPENING_BEATS_MUTABLE = [
  {
    id: "guidance/opening/board-briefing",
    track: "opening",
    featureIds: ["contracts"],
    milestoneOrder: 1,
    presenterId: ASSISTANT_PRESENTER_ID,
    presenterExpression: "serious",
    delivery: {
      mode: "blocking",
      pauseWorld: true,
      allowSkip: false,
      replayPolicy: "manual_replay",
    },
    gating: {
      requiredCompletedBeatIds: [],
    },
    bindings: {},
    copy: {
      title: "Welcome, {playerName}",
      subtitle: "Operations Briefing",
      body: "Dungeons started showing up six years ago. The city now licenses private guilds to clear them — and {playerName} just opened {guildName}, a small operation running out of a converted bodega in New York. The contract board lists government-regulated clearance jobs. Each posting shows the filing cost, threat level, payout, and whatever intel made it into the paperwork. Pick a job, staff a team, send them in, keep the lights on.",
      ctaLabel: "Understood",
      fallbackBody:
        "The contract board is where {playerName} chooses government-cleared work for {guildName}.",
      eventLogSummary: "Operations briefing: posted contracts explained",
    },
    completion: { kind: "acknowledged" },
  },
  {
    id: "guidance/opening/first-contract-choice",
    track: "opening",
    featureIds: ["contracts", "bidding"],
    milestoneOrder: 2,
    presenterId: ASSISTANT_PRESENTER_ID,
    presenterExpression: "serious",
    delivery: {
      mode: "focused",
      target: "ui/ops/contract-board",
      fallbackIntent: "ops/open-contract-board",
      pauseWorld: true,
      allowSkip: false,
      replayPolicy: "manual_replay",
    },
    gating: {
      requiredCompletedBeatIds: ["guidance/opening/board-briefing"],
    },
    bindings: {},
    copy: {
      title: "Secure Your First Contract",
      subtitle: "One job at a time",
      body: "{guildName} handles one active contract at a time. Filing a bid costs cash up front. Review the available sites, weigh the risk against what this roster can handle, and lock in a contract.",
      ctaLabel: "Select a contract",
      fallbackBody: "Open Operations and file a bid on one posted contract.",
      eventLogSummary: "Guidance: choose your first contract from the board",
    },
    completion: { kind: "contract_secured" },
  },
  {
    id: "guidance/opening/bodega-overview",
    track: "opening",
    featureIds: ["rooms", "bodega"],
    milestoneOrder: 3,
    presenterId: ASSISTANT_PRESENTER_ID,
    presenterExpression: "amused",
    delivery: {
      mode: "focused",
      target: "ui/hq/category/rooms",
      fallbackIntent: "hq/open-rooms",
      pauseWorld: true,
      allowSkip: false,
      replayPolicy: "manual_replay",
    },
    gating: {
      requiredCompletedBeatIds: ["guidance/opening/first-contract-choice"],
    },
    bindings: {},
    copy: {
      title: "The Bodega",
      subtitle: "Headquarters, technically",
      body: "The bodega has four rooms, each pulling double duty. The Register handles contracts and walk-ins. The Counter brings in recruits. The Dining Area covers recovery and morale. The Supply Closet stores gear — but it starts dark until someone turns it on.",
      ctaLabel: "Inspect a room",
      fallbackBody:
        "Open Rooms and inspect one room card to review what this bodega actually does.",
      eventLogSummary: "Guidance: bodega rooms explained",
    },
    completion: { kind: "room_inspected" },
  },
  {
    id: "guidance/opening/roster-and-equip",
    track: "opening",
    featureIds: ["roster", "operators", "gear"],
    milestoneOrder: 4,
    presenterId: ASSISTANT_PRESENTER_ID,
    presenterExpression: "neutral",
    delivery: {
      mode: "focused",
      target: "ui/hq/category/roster",
      fallbackIntent: "hq/open-roster",
      pauseWorld: true,
      allowSkip: false,
      replayPolicy: "manual_replay",
    },
    gating: {
      requiredCompletedBeatIds: ["guidance/opening/bodega-overview"],
    },
    bindings: {},
    copy: {
      title: "Roster and Gear",
      subtitle: "Check the people, then the kit",
      body: "Every operator has morale, loyalty, fatigue, and injury stats that affect whether they can deploy and how well they perform. Equipment matters too — {guildName} does not have enough gear for everyone yet. Check the roster, then decide who gets outfitted before the first deployment.",
      ctaLabel: "Inspect an operator",
      fallbackBody: "Open Roster and inspect one operator before the first deployment.",
      eventLogSummary: "Guidance: roster condition and early gear pressure explained",
    },
    completion: { kind: "operator_inspected" },
  },
  {
    id: "guidance/opening/first-team-departure",
    track: "opening",
    featureIds: ["raids", "autonomy"],
    milestoneOrder: 5,
    presenterId: ASSISTANT_PRESENTER_ID,
    presenterExpression: "serious",
    delivery: {
      mode: "focused",
      target: "ui/raid/map",
      fallbackIntent: "ops/open-raid-map",
      pauseWorld: true,
      allowSkip: false,
      replayPolicy: "manual_replay",
    },
    gating: {
      requiredCompletedBeatIds: ["guidance/opening/roster-and-equip"],
      requireFirstTeamDeparture: true,
    },
    bindings: {},
    copy: {
      title: "Raid Operations",
      subtitle: "They go in. {playerName} manages what comes back.",
      body: "Once a team deploys into a dungeon, they operate on their own. They scout, fight, loot, and decide when to push deeper or pull out. {playerName} does not control tactics inside the rift — {playerName} controls preparation, staffing, equipment, and whatever consequences come back through the door.",
      ctaLabel: "Understood",
      fallbackBody: "Watch the raid map. Teams move and act without direct tactical control.",
      eventLogSummary: "Guidance: autonomous raid behavior explained",
    },
    completion: { kind: "team_departed", requiresManualCompletion: true },
  },
  {
    id: "guidance/opening/first-raid-return",
    track: "opening",
    featureIds: ["raids", "results"],
    milestoneOrder: 6,
    presenterId: ASSISTANT_PRESENTER_ID,
    presenterExpression: "concerned",
    delivery: {
      mode: "focused",
      target: "ui/ops/panel/history",
      fallbackIntent: "ops/open-history",
      pauseWorld: true,
      allowSkip: false,
      replayPolicy: "manual_replay",
    },
    gating: {
      requiredCompletedBeatIds: ["guidance/opening/first-team-departure"],
      requireFirstRaidReturn: true,
    },
    bindings: {},
    copy: {
      title: "Raid Debrief",
      subtitle: "They came back. Here is the bill.",
      body: "Every raid return comes with a full report: loot recovered, injuries sustained, morale shifts, and what the team had to do to get out. This is where {playerName} sees the real cost of each deployment.",
      ctaLabel: "Review summary",
      fallbackBody: "Raid returns change inventory, injuries, and operator condition all at once.",
      eventLogSummary: "Guidance: first raid return explained",
    },
    completion: { kind: "acknowledged" },
  },
  {
    id: "guidance/opening/roster-condition",
    track: "opening",
    featureIds: ["roster", "recovery"],
    milestoneOrder: 7,
    presenterId: ASSISTANT_PRESENTER_ID,
    presenterExpression: "concerned",
    delivery: {
      mode: "focused",
      target: "ui/hq/category/roster",
      fallbackIntent: "hq/open-roster",
      pauseWorld: true,
      allowSkip: false,
      replayPolicy: "manual_replay",
    },
    gating: {
      requiredCompletedBeatIds: ["guidance/opening/first-raid-return"],
      requireOperatorWorn: true,
    },
    bindings: {},
    copy: {
      title: "Morning-After Condition",
      subtitle: "Rest is management",
      body: "Fatigue, injuries, and morale drops are not cosmetic — they determine who can deploy and how badly the next contract can go. The Dining Area handles recovery for now, because {guildName} cannot afford a proper infirmary yet.",
      ctaLabel: "Understood",
      fallbackBody: "Open Roster to review which operators came back worn down.",
      eventLogSummary: "Guidance: post-raid roster wear explained",
    },
    completion: { kind: "acknowledged" },
  },
  {
    id: "guidance/opening/first-incident",
    track: "opening",
    featureIds: ["incidents", "interruptions"],
    milestoneOrder: 8,
    presenterId: ASSISTANT_PRESENTER_ID,
    presenterExpression: "serious",
    delivery: {
      mode: "blocking",
      pauseWorld: true,
      allowSkip: false,
      replayPolicy: "manual_replay",
    },
    gating: {
      requiredCompletedBeatIds: ["guidance/opening/first-raid-return"],
      requireFirstIncidentEligible: true,
    },
    bindings: {},
    copy: {
      title: "Incident Report",
      subtitle: "Management decision required",
      body: "Incidents are management decisions that pause the simulation. Morale, loyalty, cash, and relationships can all shift depending on how {playerName} responds. There is no undo.",
      ctaLabel: "Handle it",
      fallbackBody:
        "An incident has landed and the simulation is paused until {playerName} responds.",
      eventLogSummary: "Guidance: incident handling introduced",
    },
    completion: { kind: "incident_resolved" },
  },
  {
    id: "guidance/opening/loot-and-market",
    track: "opening",
    featureIds: ["loot", "market", "inventory"],
    milestoneOrder: 9,
    presenterId: ASSISTANT_PRESENTER_ID,
    presenterExpression: "amused",
    delivery: {
      mode: "focused",
      target: "ui/hq/category/market",
      fallbackIntent: "hq/open-market",
      pauseWorld: true,
      allowSkip: false,
      replayPolicy: "manual_replay",
    },
    gating: {
      requiredCompletedBeatIds: ["guidance/opening/first-incident"],
      requireFirstRaidReturnWithLoot: true,
    },
    bindings: {},
    copy: {
      title: "Loot and Market",
      subtitle: "The bodega is still a business",
      body: "Monster parts are not trophies — they are revenue once {playerName} sells them. The market also sells weapons, outfits, and accessories. Better gear means better raid outcomes, which means more loot to sell. That is the loop.",
      ctaLabel: "Open market",
      fallbackBody: "Open Market to review what loot can be sold and what gear can be bought.",
      eventLogSummary: "Guidance: loot and market loop explained",
    },
    completion: { kind: "market_opened", requiresManualCompletion: true },
  },
  {
    id: "guidance/opening/staffing-and-rooms",
    track: "opening",
    featureIds: ["staffing", "rooms"],
    milestoneOrder: 10,
    presenterId: ASSISTANT_PRESENTER_ID,
    presenterExpression: "neutral",
    delivery: {
      mode: "focused",
      target: "ui/hq/category/rooms",
      fallbackIntent: "hq/open-rooms",
      pauseWorld: true,
      allowSkip: false,
      replayPolicy: "manual_replay",
    },
    gating: {
      requiredCompletedBeatIds: ["guidance/opening/loot-and-market"],
      requireUnassignedManagementAction: true,
    },
    bindings: {},
    copy: {
      title: "Staffing and Rooms",
      subtitle: "Payroll should buy labor",
      body: "Idle staff and unused rooms are wasted overhead. Assign operators where they help, and bring dormant rooms online when {guildName} needs the capacity. Everyone is on the clock either way.",
      ctaLabel: "Assign staff or activate a room",
      fallbackBody: "Open the Rooms tab, then assign a staff member or activate an idle room.",
      eventLogSummary: "Guidance: staffing and room activation explained",
    },
    completion: { kind: "staffing_action_taken" },
  },
  {
    id: "guidance/opening/first-upgrade",
    track: "opening",
    featureIds: ["upgrades", "rooms"],
    milestoneOrder: 11,
    presenterId: ASSISTANT_PRESENTER_ID,
    presenterExpression: "neutral",
    delivery: {
      mode: "focused",
      target: "ui/hq/category/rooms",
      fallbackIntent: "hq/open-rooms",
      pauseWorld: true,
      allowSkip: false,
      replayPolicy: "manual_replay",
    },
    gating: {
      requiredCompletedBeatIds: ["guidance/opening/staffing-and-rooms"],
      minimumSecuredContractCount: 3,
      requireUpgradeAffordable: true,
    },
    bindings: {},
    copy: {
      title: "First Upgrade",
      subtitle: "A small improvement is still a milestone",
      body: "Upgrades are physical improvements to the bodega — better records systems, better equipment, better recovery tools. They cost real cash, but they make the operation less fragile.",
      ctaLabel: "Buy an upgrade",
      fallbackBody:
        "Open room management and purchase the first upgrade {guildName} can actually afford.",
      eventLogSummary: "Guidance: first upgrade decision explained",
    },
    completion: { kind: "upgrade_purchased" },
  },
  {
    id: "guidance/opening/setback-recovery",
    track: "opening",
    featureIds: ["recovery", "failure"],
    milestoneOrder: 12,
    presenterId: ASSISTANT_PRESENTER_ID,
    presenterExpression: "serious",
    delivery: {
      mode: "blocking",
      pauseWorld: true,
      allowSkip: false,
      replayPolicy: "manual_replay",
    },
    gating: {
      requiredCompletedBeatIds: ["guidance/opening/first-team-departure"],
      requireSetbackRecoveryTrigger: true,
    },
    bindings: {},
    copy: {
      title: "Setback Recovery",
      subtitle: "Bad runs are part of the job",
      body: "Failed raids, serious injuries, operator deaths, lost contracts — none of it ends the operation. It means {playerName} rests the wounded, recruits replacements, and keeps {guildName} running long enough to take the next job.",
      ctaLabel: "Understood",
      fallbackBody:
        "Setbacks are recoverable if {playerName} manages the roster and keeps work flowing.",
      eventLogSummary: "Guidance: setback recovery explained",
    },
    completion: { kind: "acknowledged" },
  },
  {
    id: "guidance/opening/boss-commitment",
    track: "opening",
    featureIds: ["boss-commitment", "encounters"],
    milestoneOrder: 13,
    presenterId: ASSISTANT_PRESENTER_ID,
    presenterExpression: "serious",
    delivery: {
      mode: "blocking",
      pauseWorld: true,
      allowSkip: false,
      replayPolicy: "manual_replay",
    },
    gating: {
      requiredCompletedBeatIds: ["guidance/opening/first-upgrade"],
      requireFirstBossCommitment: true,
    },
    bindings: {},
    copy: {
      title: "Boss Commitment",
      subtitle: "This one can kill the whole team",
      body: "Reaching a floor boss triggers a commitment decision. Sending the team in means a real encounter with real stakes. Pulling back keeps everyone alive, but the contract stays incomplete. The call is {playerName}'s.",
      ctaLabel: "Decide",
      fallbackBody: "A team has reached the boss. The game is paused for a commitment decision.",
      eventLogSummary: "Guidance: boss commitment explained",
    },
    completion: { kind: "boss_commitment_resolved" },
  },
] as const satisfies readonly GuidanceBeat[];

export const OPENING_BEATS: readonly GuidanceBeat[] = OPENING_BEATS_MUTABLE;

export const OPENING_BEAT_IDS: readonly string[] = OPENING_BEATS.map((b) => b.id);

export const OPENING_BEAT_BY_ID: ReadonlyMap<string, GuidanceBeat> = new Map(
  OPENING_BEATS.map((b) => [b.id, b]),
);

export const OPENING_BEAT_COUNT: number = OPENING_BEATS.length;

export const BODEGA_SPECIFIC_BEAT_IDS: readonly string[] = OPENING_BEATS.filter((b) =>
  b.featureIds.includes("bodega"),
).map((b) => b.id);

export const FIRST_RAID_RETURN_BEAT_ID = "guidance/opening/first-raid-return";
