import { soa } from "bitecs";

export const OperatorIdentity = soa({
  id: [] as string[],
  name: [] as string[],
  roleTag: [] as string[],
  specialtyTag: [] as string[],
  personaSummary: [] as string[],
  personaHooks: [] as string[][],
  appearancePresetId: [] as string[],
  appearanceWeaponPartId: [] as string[],
  appearanceOutfitOverlayPartId: [] as string[],
  appearanceAccessoryPartId: [] as string[],
  lifecycleStatus: [] as string[],
  deathTick: [] as number[],
  deathRaidSummaryId: [] as string[],
  departureTick: [] as number[],
  departureReason: [] as string[],
  rank: [] as string[],
  attunementTag: [] as string[],
  traits: [] as string[][],
  regularAttackId: [] as string[],
  skillId: [] as string[],
  ultimateId: [] as string[],
  passiveIds: [] as string[][],
  baseStrength: [] as number[],
  baseSpeed: [] as number[],
  baseEndurance: [] as number[],
  baseResilience: [] as number[],
  basePerception: [] as number[],
  baseIntelligence: [] as number[],
});
