import { soa } from "bitecs";

export const VisitorState = soa({
  id: [] as string[],
  name: [] as string[],
  desiredRoleTag: [] as string[],
  specialtyTag: [] as string[],
  patience: [] as number[],
  quality: [] as number[],
  expectedLoyalty: [] as number[],
  appearancePresetId: [] as string[],
  appearanceWeaponPartId: [] as string[],
  appearanceOutfitOverlayPartId: [] as string[],
  appearanceAccessoryPartId: [] as string[],
  personaSummary: [] as string[],
  personaHooks: [] as string[][],
  preferenceRiskTolerance: [] as number[],
  preferenceRewardFocus: [] as number[],
  preferenceRecoveryBias: [] as number[],
  preferenceSocialBias: [] as number[],
  preferenceTrainingBias: [] as number[],
  preferenceComfortBias: [] as number[],
  preferencePreferredMissionTags: [] as string[][],
  identitySource: [] as string[],
  queueState: [] as string[],
});
