import type { EnemyFamilyTemplate } from "./shared";

export const enemyFamilyTemplates: readonly EnemyFamilyTemplate[] = [
  // ── F-rank families ──────────────────────────────────────────────────

  {
    familyId: "enemy-family/tunnel-crawlers",
    name: "Tunnel Crawlers",
    description:
      "Things that used to be subway maintenance fauna — rats, roaches, drainage mold — fused together by warm wrong water into segmented masses that navigate flooded tunnels by echolocation. They hate light.",
    siteConceptIds: ["site/flooded-subway-tunnel"],
    members: [
      {
        enemyTemplateId: "enemy/drain-louse",
        familyId: "enemy-family/tunnel-crawlers",
        name: "Drain Louse",
        description:
          "A cockroach-rat hybrid the size of a dog, coated in sewer biofilm. Skitters along tunnel walls and drops onto operators from above. The legs are wrong — too many joints, all bending inward.",
        attack: 10,
        defense: 6,
        hp: 25,
        speed: 16,
        threat: 22,
        actions: [
          {
            id: "action/drain-louse/wall-drop",
            name: "Wall Drop",
            weight: 6,
            basePower: 12,
            targeting: "single",
            tags: ["ambush"],
          },
          {
            id: "action/drain-louse/skitter-bite",
            name: "Skitter Bite",
            weight: 4,
            basePower: 8,
            targeting: "single",
          },
        ],
        tags: ["ambush", "swarm-pressure"],
        dropTableId: "drop-table/tunnel-crawlers-regular",
      },
      {
        enemyTemplateId: "enemy/pipe-wyrm",
        familyId: "enemy-family/tunnel-crawlers",
        name: "Pipe Wyrm",
        description:
          "A segmented mass of fused drainage organisms that fills an entire pipe section. Moves by peristalsis. Exudes warm water that dissolves boot leather and morale in equal measure.",
        attack: 18,
        defense: 14,
        hp: 50,
        speed: 10,
        threat: 48,
        actions: [
          {
            id: "action/pipe-wyrm/pressure-surge",
            name: "Pressure Surge",
            weight: 4,
            basePower: 20,
            targeting: "all",
            tags: ["hazard-synergy"],
          },
          {
            id: "action/pipe-wyrm/constrict",
            name: "Constrict",
            weight: 3,
            basePower: 16,
            targeting: "single",
            tags: ["entangle"],
          },
          {
            id: "action/pipe-wyrm/dissolving-film",
            name: "Dissolving Film",
            weight: 3,
            basePower: 10,
            targeting: "weakest",
            tags: ["corrosive"],
          },
        ],
        tags: ["heavy", "hazard-synergy", "entangle"],
        dropTableId: "drop-table/tunnel-crawlers-elite",
      },
    ],
  },

  {
    familyId: "enemy-family/concrete-sentinels",
    name: "Concrete Sentinels",
    description:
      "Parking infrastructure that started moving. Tire stops, bollards, and ramp dividers reassembled into squat bipedal forms held together by exhaust fumes that behave like muscle fiber. They patrol the spiral ramps on a schedule nobody set.",
    siteConceptIds: ["site/condemned-parking-garage"],
    members: [
      {
        enemyTemplateId: "enemy/bollard-walker",
        familyId: "enemy-family/concrete-sentinels",
        name: "Bollard Walker",
        description:
          "A parking bollard that pulled itself out of the floor and grew legs from rebar. Slow, methodical, hits like getting sideswiped by a sedan. Patrols a fixed route and does not appreciate detours.",
        attack: 12,
        defense: 11,
        hp: 35,
        speed: 8,
        threat: 30,
        actions: [
          {
            id: "action/bollard-walker/concrete-slam",
            name: "Concrete Slam",
            weight: 5,
            basePower: 14,
            targeting: "single",
            tags: ["heavy"],
          },
          {
            id: "action/bollard-walker/exhaust-cloud",
            name: "Exhaust Cloud",
            weight: 5,
            basePower: 8,
            targeting: "all",
            tags: ["suppression"],
          },
        ],
        tags: ["heavy", "suppression"],
        dropTableId: "drop-table/concrete-sentinels-regular",
      },
      {
        enemyTemplateId: "enemy/ramp-sentinel",
        familyId: "enemy-family/concrete-sentinels",
        name: "Ramp Sentinel",
        description:
          "A speed bump that unfolded into something taller than a person, reinforced with crushed parking meters and held rigid by fume-tension. Guards chokepoints on the spiral ramps. Hits hard enough to relocate dental work.",
        attack: 20,
        defense: 16,
        hp: 55,
        speed: 10,
        threat: 52,
        actions: [
          {
            id: "action/ramp-sentinel/barrier-charge",
            name: "Barrier Charge",
            weight: 4,
            basePower: 22,
            targeting: "single",
            tags: ["heavy", "armor-break"],
          },
          {
            id: "action/ramp-sentinel/fume-suppression",
            name: "Fume Suppression",
            weight: 3,
            basePower: 12,
            targeting: "all",
            tags: ["suppression", "hazard-synergy"],
          },
          {
            id: "action/ramp-sentinel/parking-violation",
            name: "Parking Violation",
            weight: 3,
            basePower: 16,
            targeting: "weakest",
            tags: ["armor-break"],
          },
        ],
        tags: ["heavy", "armor-break", "suppression"],
        dropTableId: "drop-table/concrete-sentinels-elite",
      },
    ],
  },

  {
    familyId: "enemy-family/chalk-swarms",
    name: "Chalk Swarms",
    description:
      "Chalk dust that remembers being written. Lesson fragments and attendance records compressed into mobile particulate clouds that reshape hallways and fill lungs. The handwriting is still legible if you look close, but reading it is not recommended.",
    siteConceptIds: ["site/abandoned-school"],
    members: [
      {
        enemyTemplateId: "enemy/dust-sketch",
        familyId: "enemy-family/chalk-swarms",
        name: "Dust Sketch",
        description:
          "A chalk-dust outline of a child's drawing that peeled off a blackboard and learned to move. Two-dimensional, fast, and surprisingly sharp at the edges. Slips through door cracks.",
        attack: 9,
        defense: 5,
        hp: 20,
        speed: 18,
        threat: 24,
        actions: [
          {
            id: "action/dust-sketch/paper-cut",
            name: "Paper Cut",
            weight: 5,
            basePower: 10,
            targeting: "single",
            tags: ["hit-and-run"],
          },
          {
            id: "action/dust-sketch/chalk-scatter",
            name: "Chalk Scatter",
            weight: 5,
            basePower: 6,
            targeting: "all",
            tags: ["swarm-pressure"],
          },
        ],
        tags: ["hit-and-run", "swarm-pressure"],
        dropTableId: "drop-table/chalk-swarms-regular",
      },
      {
        enemyTemplateId: "enemy/lesson-cloud",
        familyId: "enemy-family/chalk-swarms",
        name: "Lesson Cloud",
        description:
          "A dense particulate mass of compressed lesson plans, report cards, and disciplinary notes. Fills corridors with chalk haze that rewrites itself mid-air. Operators who breathe it in report hearing roll call.",
        attack: 14,
        defense: 8,
        hp: 40,
        speed: 14,
        threat: 40,
        actions: [
          {
            id: "action/lesson-cloud/curriculum-suffocation",
            name: "Curriculum Suffocation",
            weight: 4,
            basePower: 16,
            targeting: "all",
            tags: ["suppression", "hazard-synergy"],
          },
          {
            id: "action/lesson-cloud/detention-grip",
            name: "Detention Grip",
            weight: 3,
            basePower: 14,
            targeting: "single",
            tags: ["entangle"],
          },
        ],
        tags: ["suppression", "hazard-synergy", "entangle"],
        dropTableId: "drop-table/chalk-swarms-elite",
      },
      {
        enemyTemplateId: "enemy/locker-sentinel",
        familyId: "enemy-family/chalk-swarms",
        name: "Locker Sentinel",
        description:
          "A row of hall lockers that fused into a hinged metal centipede. Opens and slams shut in sequence. Still has combination locks, none of which work.",
        attack: 15,
        defense: 12,
        hp: 38,
        speed: 12,
        threat: 38,
        actions: [
          {
            id: "action/locker-sentinel/slam-shut",
            name: "Slam Shut",
            weight: 5,
            basePower: 18,
            targeting: "single",
            tags: ["heavy"],
          },
          {
            id: "action/locker-sentinel/combination-rattle",
            name: "Combination Rattle",
            weight: 5,
            basePower: 10,
            targeting: "all",
            tags: ["suppression"],
          },
        ],
        tags: ["heavy", "suppression"],
        dropTableId: "drop-table/chalk-swarms-regular",
      },
    ],
  },

  {
    familyId: "enemy-family/vine-constructs",
    name: "Vine Constructs",
    description:
      "Botanical garden specimens that outgrew their planters and started building with themselves. Root systems that act as distributed nervous tissue, moving greenhouse furniture and garden tools into defensive arrangements. The growth is patient and deliberate.",
    siteConceptIds: ["site/overgrown-botanical-garden"],
    members: [
      {
        enemyTemplateId: "enemy/creeper-tendril",
        familyId: "enemy-family/vine-constructs",
        name: "Creeper Tendril",
        description:
          "A vine cluster that detached from the main root network and learned to ambush. Lies flat against greenhouse glass until something warm walks past, then wraps and squeezes. Stronger than it looks.",
        attack: 11,
        defense: 7,
        hp: 22,
        speed: 14,
        threat: 25,
        actions: [
          {
            id: "action/creeper-tendril/vine-lash",
            name: "Vine Lash",
            weight: 4,
            basePower: 12,
            targeting: "single",
            tags: ["entangle"],
          },
          {
            id: "action/creeper-tendril/root-trip",
            name: "Root Trip",
            weight: 6,
            basePower: 8,
            targeting: "single",
            tags: ["ambush"],
          },
        ],
        tags: ["entangle", "ambush"],
        dropTableId: "drop-table/vine-constructs-regular",
      },
      {
        enemyTemplateId: "enemy/trellis-golem",
        familyId: "enemy-family/vine-constructs",
        name: "Trellis Golem",
        description:
          "A garden trellis wrapped in so much vine mass that it walks. Wooden lattice skeleton, living plant musculature, a garden hose for a spine. Carries a planter box in each hand like improvised shields.",
        attack: 16,
        defense: 15,
        hp: 48,
        speed: 10,
        threat: 46,
        actions: [
          {
            id: "action/trellis-golem/planter-smash",
            name: "Planter Smash",
            weight: 4,
            basePower: 18,
            targeting: "single",
            tags: ["heavy", "armor-break"],
          },
          {
            id: "action/trellis-golem/pollen-burst",
            name: "Pollen Burst",
            weight: 3,
            basePower: 10,
            targeting: "all",
            tags: ["hazard-synergy", "suppression"],
          },
          {
            id: "action/trellis-golem/root-anchor",
            name: "Root Anchor",
            weight: 3,
            basePower: 12,
            targeting: "weakest",
            tags: ["entangle"],
          },
        ],
        tags: ["heavy", "entangle", "hazard-synergy"],
        dropTableId: "drop-table/vine-constructs-elite",
      },
    ],
  },

  {
    familyId: "enemy-family/suds-constructs",
    name: "Suds Constructs",
    description:
      "Laundromat machinery that fused with its own chemical runoff. Washers, dryers, and detergent dispensers twisted into steam-venting ambulatory masses that slosh through flooded basement corridors. The rinse cycle never ends.",
    siteConceptIds: ["site/flooded-laundromat-basement"],
    members: [
      {
        enemyTemplateId: "enemy/lint-crawler",
        familyId: "enemy-family/suds-constructs",
        name: "Lint Crawler",
        description:
          "A compacted lint mass the size of a laundry bag, held together by static charge and detergent residue. Rolls along wet floors and clings to anything warm. The static discharge when it makes contact is unpleasant.",
        attack: 9,
        defense: 5,
        hp: 22,
        speed: 16,
        threat: 20,
        actions: [
          {
            id: "action/lint-crawler/static-cling",
            name: "Static Cling",
            weight: 5,
            basePower: 10,
            targeting: "single",
            tags: ["entangle"],
          },
          {
            id: "action/lint-crawler/lint-burst",
            name: "Lint Burst",
            weight: 5,
            basePower: 7,
            targeting: "all",
            tags: ["suppression"],
          },
        ],
        tags: ["swarm-pressure", "entangle"],
        dropTableId: "drop-table/suds-constructs-regular",
      },
      {
        enemyTemplateId: "enemy/drum-roller",
        familyId: "enemy-family/suds-constructs",
        name: "Drum Roller",
        description:
          "An industrial washer drum that tore free of its housing and learned to spin-walk on protruding agitator fins. Filled with scalding water and whatever was in the last load. Charges in straight lines and bounces off walls.",
        attack: 16,
        defense: 14,
        hp: 45,
        speed: 12,
        threat: 44,
        actions: [
          {
            id: "action/drum-roller/spin-charge",
            name: "Spin Charge",
            weight: 4,
            basePower: 18,
            targeting: "single",
            tags: ["heavy"],
          },
          {
            id: "action/drum-roller/scald-spray",
            name: "Scald Spray",
            weight: 3,
            basePower: 12,
            targeting: "all",
            tags: ["hazard-synergy", "corrosive"],
          },
          {
            id: "action/drum-roller/agitator-grind",
            name: "Agitator Grind",
            weight: 3,
            basePower: 14,
            targeting: "weakest",
            tags: ["armor-break"],
          },
        ],
        tags: ["heavy", "hazard-synergy", "armor-break"],
        dropTableId: "drop-table/suds-constructs-elite",
      },
    ],
  },

  {
    familyId: "enemy-family/cellar-dwellers",
    name: "Cellar Dwellers",
    description:
      "Domestic objects from a basement apartment that kept furnishing itself after the tenants left. Radiators, folding chairs, and box fans reassembled into territorial masses that defend rooms nobody lives in anymore. The mail slot still accepts deliveries.",
    siteConceptIds: ["site/condemned-residential-basement"],
    members: [
      {
        enemyTemplateId: "enemy/radiator-creep",
        familyId: "enemy-family/cellar-dwellers",
        name: "Radiator Creep",
        description:
          "A cast-iron radiator that tore itself off the wall and drags itself by its own pipes. Leaks scalding water from every joint. The thermostat dial on top still clicks between settings, none of which are 'off.'",
        attack: 12,
        defense: 10,
        hp: 32,
        speed: 8,
        threat: 28,
        actions: [
          {
            id: "action/radiator-creep/pipe-swing",
            name: "Pipe Swing",
            weight: 5,
            basePower: 14,
            targeting: "single",
            tags: ["heavy"],
          },
          {
            id: "action/radiator-creep/steam-hiss",
            name: "Steam Hiss",
            weight: 5,
            basePower: 8,
            targeting: "all",
            tags: ["suppression", "hazard-synergy"],
          },
        ],
        tags: ["heavy", "suppression"],
        dropTableId: "drop-table/cellar-dwellers-regular",
      },
      {
        enemyTemplateId: "enemy/box-fan-swarm",
        familyId: "enemy-family/cellar-dwellers",
        name: "Box Fan Swarm",
        description:
          "A cluster of oscillating box fans wired together with extension cords, hovering on blade-draft and bad physics. The cords trail behind like tentacles. Operators near them report the air tasting like pennies.",
        attack: 10,
        defense: 6,
        hp: 24,
        speed: 18,
        threat: 26,
        actions: [
          {
            id: "action/box-fan-swarm/blade-pass",
            name: "Blade Pass",
            weight: 5,
            basePower: 12,
            targeting: "single",
            tags: ["hit-and-run"],
          },
          {
            id: "action/box-fan-swarm/cord-tangle",
            name: "Cord Tangle",
            weight: 5,
            basePower: 8,
            targeting: "single",
            tags: ["entangle"],
          },
        ],
        tags: ["hit-and-run", "swarm-pressure", "entangle"],
        dropTableId: "drop-table/cellar-dwellers-regular",
      },
      {
        enemyTemplateId: "enemy/fridge-hulk",
        familyId: "enemy-family/cellar-dwellers",
        name: "Fridge Hulk",
        description:
          "A full-size refrigerator that stands upright and walks on compressor legs. The door opens and slams shut with enough force to bend rebar. Whatever is inside expired a long time ago and is not improving with age.",
        attack: 18,
        defense: 16,
        hp: 52,
        speed: 10,
        threat: 50,
        actions: [
          {
            id: "action/fridge-hulk/door-slam",
            name: "Door Slam",
            weight: 4,
            basePower: 20,
            targeting: "single",
            tags: ["heavy", "armor-break"],
          },
          {
            id: "action/fridge-hulk/expired-gas",
            name: "Expired Gas",
            weight: 3,
            basePower: 10,
            targeting: "all",
            tags: ["suppression", "corrosive"],
          },
          {
            id: "action/fridge-hulk/compressor-charge",
            name: "Compressor Charge",
            weight: 3,
            basePower: 16,
            targeting: "weakest",
            tags: ["heavy"],
          },
        ],
        tags: ["heavy", "armor-break", "suppression"],
        dropTableId: "drop-table/cellar-dwellers-elite",
      },
    ],
  },

  {
    familyId: "enemy-family/court-echoes",
    name: "Court Echoes",
    description:
      "Athletic equipment and gymnasium fixtures animated by the rec center's residual competitive energy. Basketballs that hunt in packs, bleacher seats that snap shut, and gymnastics apparatus that executes routines no coach assigned. The scoreboard updates in real time.",
    siteConceptIds: ["site/closed-community-center"],
    members: [
      {
        enemyTemplateId: "enemy/rebound-hunter",
        familyId: "enemy-family/court-echoes",
        name: "Rebound Hunter",
        description:
          "A basketball inflated to dangerous PSI, bouncing at lethal velocity through gymnasium corridors. Changes direction on contact with walls, floors, and operators. The impact sounds like a gunshot in an enclosed space.",
        attack: 11,
        defense: 4,
        hp: 20,
        speed: 20,
        threat: 24,
        actions: [
          {
            id: "action/rebound-hunter/ricochet",
            name: "Ricochet",
            weight: 6,
            basePower: 12,
            targeting: "single",
            tags: ["hit-and-run"],
          },
          {
            id: "action/rebound-hunter/court-press",
            name: "Court Press",
            weight: 4,
            basePower: 8,
            targeting: "all",
            tags: ["swarm-pressure"],
          },
        ],
        tags: ["hit-and-run", "swarm-pressure"],
        dropTableId: "drop-table/court-echoes-regular",
      },
      {
        enemyTemplateId: "enemy/bleacher-maw",
        familyId: "enemy-family/court-echoes",
        name: "Bleacher Maw",
        description:
          "A section of retractable bleacher seating that folds and unfolds like a jaw. Lures operators into the gap between rows, then snaps shut. The seat numbers are still visible if you look while it's chewing.",
        attack: 15,
        defense: 13,
        hp: 42,
        speed: 10,
        threat: 40,
        actions: [
          {
            id: "action/bleacher-maw/seat-trap",
            name: "Seat Trap",
            weight: 4,
            basePower: 18,
            targeting: "single",
            tags: ["entangle", "heavy"],
          },
          {
            id: "action/bleacher-maw/fold-crush",
            name: "Fold Crush",
            weight: 3,
            basePower: 14,
            targeting: "single",
            tags: ["armor-break"],
          },
          {
            id: "action/bleacher-maw/row-rattle",
            name: "Row Rattle",
            weight: 3,
            basePower: 10,
            targeting: "all",
            tags: ["suppression"],
          },
        ],
        tags: ["entangle", "heavy", "suppression"],
        dropTableId: "drop-table/court-echoes-elite",
      },
    ],
  },

  {
    familyId: "enemy-family/freezer-fauna",
    name: "Freezer Fauna",
    description:
      "Cold storage inventory that stopped being inventory. Frozen meat, dairy crates, and refrigeration coils fused into ambulatory masses preserved at temperatures that should not sustain movement. The cold that radiates from them is wrong — it numbs thoughts before it numbs skin.",
    siteConceptIds: ["site/corner-deli-cold-storage"],
    members: [
      {
        enemyTemplateId: "enemy/frost-skitter",
        familyId: "enemy-family/freezer-fauna",
        name: "Frost Skitter",
        description:
          "A frozen poultry carcass on ice-crystal legs, skittering across shelving units with unnatural agility. The freezer burn on its surface crackles on contact. Operators report it smells like a walk-in that lost power for a week and then got colder.",
        attack: 10,
        defense: 6,
        hp: 22,
        speed: 17,
        threat: 22,
        actions: [
          {
            id: "action/frost-skitter/ice-scratch",
            name: "Ice Scratch",
            weight: 6,
            basePower: 10,
            targeting: "single",
            tags: ["ambush"],
          },
          {
            id: "action/frost-skitter/cold-snap",
            name: "Cold Snap",
            weight: 4,
            basePower: 8,
            targeting: "all",
            tags: ["suppression"],
          },
        ],
        tags: ["ambush", "swarm-pressure"],
        dropTableId: "drop-table/freezer-fauna-regular",
      },
      {
        enemyTemplateId: "enemy/coil-serpent",
        familyId: "enemy-family/freezer-fauna",
        name: "Coil Serpent",
        description:
          "Refrigeration coils that unwound from the ceiling and learned to constrict. Copper tubing filled with coolant that frosts on contact. Moves by contracting in waves along the floor and walls. The compressor sound it makes is almost soothing until it wraps around an ankle.",
        attack: 14,
        defense: 10,
        hp: 38,
        speed: 14,
        threat: 38,
        actions: [
          {
            id: "action/coil-serpent/frost-constrict",
            name: "Frost Constrict",
            weight: 4,
            basePower: 16,
            targeting: "single",
            tags: ["entangle"],
          },
          {
            id: "action/coil-serpent/coolant-leak",
            name: "Coolant Leak",
            weight: 3,
            basePower: 12,
            targeting: "all",
            tags: ["hazard-synergy", "corrosive"],
          },
          {
            id: "action/coil-serpent/deep-freeze",
            name: "Deep Freeze",
            weight: 3,
            basePower: 14,
            targeting: "weakest",
            tags: ["suppression"],
          },
        ],
        tags: ["entangle", "hazard-synergy", "suppression"],
        dropTableId: "drop-table/freezer-fauna-elite",
      },
    ],
  },

  // ── E-rank families ──────────────────────────────────────────────────

  {
    familyId: "enemy-family/aquatic-horrors",
    name: "Aquatic Horrors",
    description:
      "Former exhibit specimens — fish, eels, jellyfish — that kept growing after the tanks stopped being tanks. The water they move through does not obey normal physics. They are too large for the spaces they occupy and do not seem to care.",
    siteConceptIds: ["site/infested-aquarium"],
    members: [
      {
        enemyTemplateId: "enemy/glass-eel",
        familyId: "enemy-family/aquatic-horrors",
        name: "Glass Eel",
        description:
          "An eel that grew transparent and six feet longer than biology allows. Swims through air in flooded corridors as easily as water. The teeth are the only part that stayed opaque.",
        attack: 14,
        defense: 9,
        hp: 32,
        speed: 20,
        threat: 35,
        actions: [
          {
            id: "action/glass-eel/translucent-strike",
            name: "Translucent Strike",
            weight: 5,
            basePower: 16,
            targeting: "single",
            tags: ["ambush"],
          },
          {
            id: "action/glass-eel/conductive-lash",
            name: "Conductive Lash",
            weight: 5,
            basePower: 12,
            targeting: "single",
            tags: ["hit-and-run"],
          },
        ],
        tags: ["ambush", "hit-and-run"],
        dropTableId: "drop-table/dungeon-f-regular",
      },
      {
        enemyTemplateId: "enemy/bloom-jelly",
        familyId: "enemy-family/aquatic-horrors",
        name: "Bloom Jelly",
        description:
          "A jellyfish the size of a weather balloon, trailing stinger filaments through flooded exhibit halls. The bell pulses with bioluminescent light that makes it hard to look at directly. Contact with the filaments is inadvisable.",
        attack: 16,
        defense: 10,
        hp: 38,
        speed: 12,
        threat: 38,
        actions: [
          {
            id: "action/bloom-jelly/filament-sweep",
            name: "Filament Sweep",
            weight: 4,
            basePower: 14,
            targeting: "all",
            tags: ["corrosive"],
          },
          {
            id: "action/bloom-jelly/pressure-pulse",
            name: "Pressure Pulse",
            weight: 6,
            basePower: 10,
            targeting: "all",
            tags: ["suppression"],
          },
        ],
        tags: ["corrosive", "suppression"],
        dropTableId: "drop-table/dungeon-f-regular",
      },
      {
        enemyTemplateId: "enemy/tank-breacher",
        familyId: "enemy-family/aquatic-horrors",
        name: "Tank Breacher",
        description:
          "Something that outgrew its exhibit tank and took the acrylic wall with it as armor plating. Crab-shaped, building-material heavy, and angry about the enclosure it can no longer fit inside. The exhibit placard is still stuck to its shell.",
        attack: 24,
        defense: 18,
        hp: 70,
        speed: 14,
        threat: 62,
        actions: [
          {
            id: "action/tank-breacher/acrylic-ram",
            name: "Acrylic Ram",
            weight: 4,
            basePower: 26,
            targeting: "single",
            tags: ["heavy", "armor-break"],
          },
          {
            id: "action/tank-breacher/flood-surge",
            name: "Flood Surge",
            weight: 3,
            basePower: 18,
            targeting: "all",
            tags: ["hazard-synergy"],
          },
          {
            id: "action/tank-breacher/shell-clamp",
            name: "Shell Clamp",
            weight: 3,
            basePower: 20,
            targeting: "weakest",
            tags: ["entangle"],
          },
        ],
        tags: ["heavy", "armor-break", "hazard-synergy"],
        dropTableId: "drop-table/dungeon-f-elite",
      },
    ],
  },

  {
    familyId: "enemy-family/mannequin-stalkers",
    name: "Mannequin Stalkers",
    description:
      "Department store display mannequins that move when unobserved. Fiberglass bodies dressed in last season's inventory, repositioning themselves between aisles to cut off exits. They do not animate — they simply are not where they were a moment ago.",
    siteConceptIds: ["site/shuttered-department-store"],
    members: [
      {
        enemyTemplateId: "enemy/display-figure",
        familyId: "enemy-family/mannequin-stalkers",
        name: "Display Figure",
        description:
          "A headless mannequin in business casual that relocates when line of sight breaks. Attacks with rigid fiberglass limbs at joints that should not articulate. The price tag is still attached.",
        attack: 15,
        defense: 10,
        hp: 35,
        speed: 18,
        threat: 36,
        actions: [
          {
            id: "action/display-figure/blind-reposition",
            name: "Blind Reposition",
            weight: 5,
            basePower: 16,
            targeting: "single",
            tags: ["ambush"],
          },
          {
            id: "action/display-figure/rigid-swipe",
            name: "Rigid Swipe",
            weight: 5,
            basePower: 12,
            targeting: "single",
            tags: ["hit-and-run"],
          },
        ],
        tags: ["ambush", "hit-and-run"],
        dropTableId: "drop-table/dungeon-f-regular",
      },
      {
        enemyTemplateId: "enemy/perfume-specter",
        familyId: "enemy-family/mannequin-stalkers",
        name: "Perfume Specter",
        description:
          "A fragrance counter display that became ambulatory. Sprays aerosolized wrong-perfume that induces disorientation and mild hallucinations. Smells like department store samples from a store that never existed.",
        attack: 13,
        defense: 8,
        hp: 30,
        speed: 16,
        threat: 32,
        actions: [
          {
            id: "action/perfume-specter/sample-spray",
            name: "Sample Spray",
            weight: 4,
            basePower: 12,
            targeting: "all",
            tags: ["suppression"],
          },
          {
            id: "action/perfume-specter/counter-shove",
            name: "Counter Shove",
            weight: 6,
            basePower: 14,
            targeting: "single",
          },
        ],
        tags: ["suppression", "ranged"],
        dropTableId: "drop-table/dungeon-f-regular",
      },
      {
        enemyTemplateId: "enemy/fitting-room-mimic",
        familyId: "enemy-family/mannequin-stalkers",
        name: "Fitting Room Mimic",
        description:
          "A fitting room stall that walks on curtain-rod legs. Lures operators inside with spatial distortion that makes the interior look like an exit. The door locks from the outside, and the mirrors do not show your reflection.",
        attack: 22,
        defense: 16,
        hp: 65,
        speed: 14,
        threat: 58,
        actions: [
          {
            id: "action/fitting-room-mimic/curtain-trap",
            name: "Curtain Trap",
            weight: 4,
            basePower: 24,
            targeting: "single",
            tags: ["entangle", "ambush"],
          },
          {
            id: "action/fitting-room-mimic/mirror-shatter",
            name: "Mirror Shatter",
            weight: 3,
            basePower: 18,
            targeting: "all",
            tags: ["ranged"],
          },
          {
            id: "action/fitting-room-mimic/wrong-reflection",
            name: "Wrong Reflection",
            weight: 3,
            basePower: 14,
            targeting: "weakest",
            tags: ["suppression"],
          },
        ],
        tags: ["entangle", "ambush", "suppression"],
        dropTableId: "drop-table/dungeon-f-elite",
      },
    ],
  },

  {
    familyId: "enemy-family/rebar-constructs",
    name: "Rebar Constructs",
    description:
      "Construction materials that kept building without a blueprint. Rebar, wet concrete, and scaffold framing twisted into ambulatory structures that patrol half-finished floors. They add to themselves from debris, growing heavier with each circuit.",
    siteConceptIds: ["site/collapsed-construction-site"],
    members: [
      {
        enemyTemplateId: "enemy/scaffold-spider",
        familyId: "enemy-family/rebar-constructs",
        name: "Scaffold Spider",
        description:
          "A scaffold frame that folded itself into an eight-legged climbing rig. Traverses vertical surfaces and drops rebar spikes from above. The safety netting it drags behind it is not for safety.",
        attack: 16,
        defense: 11,
        hp: 38,
        speed: 18,
        threat: 38,
        actions: [
          {
            id: "action/scaffold-spider/rebar-drop",
            name: "Rebar Drop",
            weight: 5,
            basePower: 18,
            targeting: "single",
            tags: ["ambush", "ranged"],
          },
          {
            id: "action/scaffold-spider/net-tangle",
            name: "Net Tangle",
            weight: 5,
            basePower: 10,
            targeting: "single",
            tags: ["entangle"],
          },
        ],
        tags: ["ambush", "ranged", "entangle"],
        dropTableId: "drop-table/dungeon-f-regular",
      },
      {
        enemyTemplateId: "enemy/wet-pour",
        familyId: "enemy-family/rebar-constructs",
        name: "Wet Pour",
        description:
          "A mass of uncured concrete that moves like an amoeba, absorbing debris into its body as ballast. Slow but nearly impossible to hurt once it hardens around a rebar skeleton. Smells like a job site in August.",
        attack: 14,
        defense: 16,
        hp: 50,
        speed: 10,
        threat: 42,
        actions: [
          {
            id: "action/wet-pour/engulf",
            name: "Engulf",
            weight: 4,
            basePower: 16,
            targeting: "single",
            tags: ["entangle", "heavy"],
          },
          {
            id: "action/wet-pour/debris-spray",
            name: "Debris Spray",
            weight: 6,
            basePower: 12,
            targeting: "all",
            tags: ["ranged", "hazard-synergy"],
          },
        ],
        tags: ["heavy", "entangle", "hazard-synergy"],
        dropTableId: "drop-table/dungeon-f-regular",
      },
      {
        enemyTemplateId: "enemy/crane-arm",
        familyId: "enemy-family/rebar-constructs",
        name: "Crane Arm",
        description:
          "A detached crane boom section that drags itself across unfinished floors like a mechanical serpent. The cable winch at its tip still operates, swinging a concrete counterweight in wide arcs. Nobody is in the operator cabin.",
        attack: 26,
        defense: 20,
        hp: 75,
        speed: 16,
        threat: 66,
        actions: [
          {
            id: "action/crane-arm/counterweight-swing",
            name: "Counterweight Swing",
            weight: 4,
            basePower: 28,
            targeting: "all",
            tags: ["heavy", "armor-break"],
          },
          {
            id: "action/crane-arm/cable-snare",
            name: "Cable Snare",
            weight: 3,
            basePower: 18,
            targeting: "single",
            tags: ["entangle"],
          },
          {
            id: "action/crane-arm/structural-collapse",
            name: "Structural Collapse",
            weight: 3,
            basePower: 22,
            targeting: "weakest",
            tags: ["hazard-synergy"],
          },
        ],
        tags: ["heavy", "armor-break", "entangle"],
        dropTableId: "drop-table/dungeon-f-elite",
      },
    ],
  },

  {
    familyId: "enemy-family/conduit-crawlers",
    name: "Conduit Crawlers",
    description:
      "Electrical infrastructure that started hunting. Cable bundles, junction boxes, and transformer coils rewired into predatory configurations that navigate the station's grid by current flow. They arc before they strike.",
    siteConceptIds: ["site/derelict-power-station"],
    members: [
      {
        enemyTemplateId: "enemy/live-wire",
        familyId: "enemy-family/conduit-crawlers",
        name: "Live Wire",
        description:
          "A severed power cable that moves like a whip-snake. Sparks continuously from the exposed end. Fast, erratic, and attracted to anything conductive. Operators in metal armor learn this the hard way.",
        attack: 15,
        defense: 8,
        hp: 30,
        speed: 22,
        threat: 34,
        actions: [
          {
            id: "action/live-wire/arc-lash",
            name: "Arc Lash",
            weight: 5,
            basePower: 16,
            targeting: "single",
            tags: ["hit-and-run"],
          },
          {
            id: "action/live-wire/chain-spark",
            name: "Chain Spark",
            weight: 5,
            basePower: 10,
            targeting: "all",
            tags: ["ranged"],
          },
        ],
        tags: ["hit-and-run", "ranged"],
        dropTableId: "drop-table/dungeon-f-regular",
      },
      {
        enemyTemplateId: "enemy/junction-crawler",
        familyId: "enemy-family/conduit-crawlers",
        name: "Junction Crawler",
        description:
          "A junction box that tore free of its wall mount and grew cable-bundle legs. Scuttles across ceilings trailing live wires. The breaker switches on its face click on and off in patterns that almost mean something.",
        attack: 18,
        defense: 12,
        hp: 42,
        speed: 16,
        threat: 42,
        actions: [
          {
            id: "action/junction-crawler/breaker-overload",
            name: "Breaker Overload",
            weight: 4,
            basePower: 18,
            targeting: "all",
            tags: ["hazard-synergy", "suppression"],
          },
          {
            id: "action/junction-crawler/cable-bind",
            name: "Cable Bind",
            weight: 6,
            basePower: 14,
            targeting: "single",
            tags: ["entangle"],
          },
        ],
        tags: ["hazard-synergy", "suppression", "entangle"],
        dropTableId: "drop-table/dungeon-f-regular",
      },
      {
        enemyTemplateId: "enemy/transformer-hulk",
        familyId: "enemy-family/conduit-crawlers",
        name: "Transformer Hulk",
        description:
          "A substation transformer that tore itself off the concrete pad and learned to walk on cable-bundle legs. Hums at a frequency that makes fillings vibrate. The oil inside it is hot and wrong and leaks from seams when it moves.",
        attack: 24,
        defense: 20,
        hp: 72,
        speed: 14,
        threat: 64,
        actions: [
          {
            id: "action/transformer-hulk/voltage-slam",
            name: "Voltage Slam",
            weight: 4,
            basePower: 26,
            targeting: "single",
            tags: ["heavy", "armor-break"],
          },
          {
            id: "action/transformer-hulk/magnetic-pulse",
            name: "Magnetic Pulse",
            weight: 3,
            basePower: 20,
            targeting: "all",
            tags: ["suppression", "hazard-synergy"],
          },
          {
            id: "action/transformer-hulk/oil-leak",
            name: "Oil Leak",
            weight: 3,
            basePower: 14,
            targeting: "weakest",
            tags: ["corrosive"],
          },
        ],
        tags: ["heavy", "armor-break", "suppression"],
        dropTableId: "drop-table/dungeon-f-elite",
      },
    ],
  },
];

export const enemyFamilyById: ReadonlyMap<string, EnemyFamilyTemplate> = new Map(
  enemyFamilyTemplates.map((f) => [f.familyId, f]),
);
