import type { EnemyFamilyTemplate } from "./shared";

export const enemyFamilyTemplates: readonly EnemyFamilyTemplate[] = [
  // ── F-rank families ──────────────────────────────────────────────────

  {
    familyId: "enemy-family/tunnel-crawlers",
    name: "Tunnel Crawlers",
    description:
      "Things that used to be subway maintenance fauna — rats, roaches, drainage mold — fused together by warm wrong water into segmented masses that navigate flooded tunnels by echolocation. They hate light.",
    siteConceptIds: ["site/flooded-subway-tunnel"],
    members: [
      {
        enemyTemplateId: "enemy/drain-louse",
        familyId: "enemy-family/tunnel-crawlers",
        name: "Drain Louse",
        description:
          "A cockroach-rat hybrid the size of a dog, coated in sewer biofilm. Skitters along tunnel walls and drops onto operators from above. The legs are wrong — too many joints, all bending inward.",
        attack: 10,
        defense: 6,
        hp: 25,
        speed: 16,
        threat: 22,
        actions: [
          {
            id: "action/drain-louse/wall-drop",
            name: "Wall Drop",
            weight: 6,
            basePower: 12,
            targeting: "single",
            tags: ["ambush"],
          },
          {
            id: "action/drain-louse/skitter-bite",
            name: "Skitter Bite",
            weight: 4,
            basePower: 8,
            targeting: "single",
          },
        ],
        tags: ["ambush", "swarm-pressure"],
        dropTableId: "drop-table/tunnel-crawlers-regular",
      },
      {
        enemyTemplateId: "enemy/pipe-wyrm",
        familyId: "enemy-family/tunnel-crawlers",
        name: "Pipe Wyrm",
        description:
          "A segmented mass of fused drainage organisms that fills an entire pipe section. Moves by peristalsis. Exudes warm water that dissolves boot leather and morale in equal measure.",
        attack: 18,
        defense: 14,
        hp: 50,
        speed: 10,
        threat: 48,
        actions: [
          {
            id: "action/pipe-wyrm/pressure-surge",
            name: "Pressure Surge",
            weight: 4,
            basePower: 20,
            targeting: "all",
            tags: ["hazard-synergy"],
          },
          {
            id: "action/pipe-wyrm/constrict",
            name: "Constrict",
            weight: 3,
            basePower: 16,
            targeting: "single",
            tags: ["entangle"],
          },
          {
            id: "action/pipe-wyrm/dissolving-film",
            name: "Dissolving Film",
            weight: 3,
            basePower: 10,
            targeting: "weakest",
            tags: ["corrosive"],
          },
        ],
        tags: ["heavy", "hazard-synergy", "entangle"],
        dropTableId: "drop-table/tunnel-crawlers-elite",
      },
    ],
  },

  {
    familyId: "enemy-family/concrete-sentinels",
    name: "Concrete Sentinels",
    description:
      "Parking infrastructure that started moving. Tire stops, bollards, and ramp dividers reassembled into squat bipedal forms held together by exhaust fumes that behave like muscle fiber. They patrol the spiral ramps on a schedule nobody set.",
    siteConceptIds: ["site/condemned-parking-garage"],
    members: [
      {
        enemyTemplateId: "enemy/bollard-walker",
        familyId: "enemy-family/concrete-sentinels",
        name: "Bollard Walker",
        description:
          "A parking bollard that pulled itself out of the floor and grew legs from rebar. Slow, methodical, hits like getting sideswiped by a sedan. Patrols a fixed route and does not appreciate detours.",
        attack: 12,
        defense: 11,
        hp: 35,
        speed: 8,
        threat: 30,
        actions: [
          {
            id: "action/bollard-walker/concrete-slam",
            name: "Concrete Slam",
            weight: 5,
            basePower: 14,
            targeting: "single",
            tags: ["heavy"],
          },
          {
            id: "action/bollard-walker/exhaust-cloud",
            name: "Exhaust Cloud",
            weight: 5,
            basePower: 8,
            targeting: "all",
            tags: ["suppression"],
          },
        ],
        tags: ["heavy", "suppression"],
        dropTableId: "drop-table/concrete-sentinels-regular",
      },
      {
        enemyTemplateId: "enemy/ramp-sentinel",
        familyId: "enemy-family/concrete-sentinels",
        name: "Ramp Sentinel",
        description:
          "A speed bump that unfolded into something taller than a person, reinforced with crushed parking meters and held rigid by fume-tension. Guards chokepoints on the spiral ramps. Hits hard enough to relocate dental work.",
        attack: 20,
        defense: 16,
        hp: 55,
        speed: 10,
        threat: 52,
        actions: [
          {
            id: "action/ramp-sentinel/barrier-charge",
            name: "Barrier Charge",
            weight: 4,
            basePower: 22,
            targeting: "single",
            tags: ["heavy", "armor-break"],
          },
          {
            id: "action/ramp-sentinel/fume-suppression",
            name: "Fume Suppression",
            weight: 3,
            basePower: 12,
            targeting: "all",
            tags: ["suppression", "hazard-synergy"],
          },
          {
            id: "action/ramp-sentinel/parking-violation",
            name: "Parking Violation",
            weight: 3,
            basePower: 16,
            targeting: "weakest",
            tags: ["armor-break"],
          },
        ],
        tags: ["heavy", "armor-break", "suppression"],
        dropTableId: "drop-table/concrete-sentinels-elite",
      },
    ],
  },

  {
    familyId: "enemy-family/chalk-swarms",
    name: "Chalk Swarms",
    description:
      "Chalk dust that remembers being written. Lesson fragments and attendance records compressed into mobile particulate clouds that reshape hallways and fill lungs. The handwriting is still legible if you look close, but reading it is not recommended.",
    siteConceptIds: ["site/abandoned-school"],
    members: [
      {
        enemyTemplateId: "enemy/dust-sketch",
        familyId: "enemy-family/chalk-swarms",
        name: "Dust Sketch",
        description:
          "A chalk-dust outline of a child's drawing that peeled off a blackboard and learned to move. Two-dimensional, fast, and surprisingly sharp at the edges. Slips through door cracks.",
        attack: 9,
        defense: 5,
        hp: 20,
        speed: 18,
        threat: 24,
        actions: [
          {
            id: "action/dust-sketch/paper-cut",
            name: "Paper Cut",
            weight: 5,
            basePower: 10,
            targeting: "single",
            tags: ["hit-and-run"],
          },
          {
            id: "action/dust-sketch/chalk-scatter",
            name: "Chalk Scatter",
            weight: 5,
            basePower: 6,
            targeting: "all",
            tags: ["swarm-pressure"],
          },
        ],
        tags: ["hit-and-run", "swarm-pressure"],
        dropTableId: "drop-table/chalk-swarms-regular",
      },
      {
        enemyTemplateId: "enemy/lesson-cloud",
        familyId: "enemy-family/chalk-swarms",
        name: "Lesson Cloud",
        description:
          "A dense particulate mass of compressed lesson plans, report cards, and disciplinary notes. Fills corridors with chalk haze that rewrites itself mid-air. Operators who breathe it in report hearing roll call.",
        attack: 14,
        defense: 8,
        hp: 40,
        speed: 14,
        threat: 40,
        actions: [
          {
            id: "action/lesson-cloud/curriculum-suffocation",
            name: "Curriculum Suffocation",
            weight: 4,
            basePower: 16,
            targeting: "all",
            tags: ["suppression", "hazard-synergy"],
          },
          {
            id: "action/lesson-cloud/detention-grip",
            name: "Detention Grip",
            weight: 3,
            basePower: 14,
            targeting: "single",
            tags: ["entangle"],
          },
        ],
        tags: ["suppression", "hazard-synergy", "entangle"],
        dropTableId: "drop-table/chalk-swarms-elite",
      },
      {
        enemyTemplateId: "enemy/locker-sentinel",
        familyId: "enemy-family/chalk-swarms",
        name: "Locker Sentinel",
        description:
          "A row of hall lockers that fused into a hinged metal centipede. Opens and slams shut in sequence. Still has combination locks, none of which work.",
        attack: 15,
        defense: 12,
        hp: 38,
        speed: 12,
        threat: 38,
        actions: [
          {
            id: "action/locker-sentinel/slam-shut",
            name: "Slam Shut",
            weight: 5,
            basePower: 18,
            targeting: "single",
            tags: ["heavy"],
          },
          {
            id: "action/locker-sentinel/combination-rattle",
            name: "Combination Rattle",
            weight: 5,
            basePower: 10,
            targeting: "all",
            tags: ["suppression"],
          },
        ],
        tags: ["heavy", "suppression"],
        dropTableId: "drop-table/chalk-swarms-regular",
      },
    ],
  },

  {
    familyId: "enemy-family/vine-constructs",
    name: "Vine Constructs",
    description:
      "Botanical garden specimens that outgrew their planters and started building with themselves. Root systems that act as distributed nervous tissue, moving greenhouse furniture and garden tools into defensive arrangements. The growth is patient and deliberate.",
    siteConceptIds: ["site/overgrown-botanical-garden"],
    members: [
      {
        enemyTemplateId: "enemy/creeper-tendril",
        familyId: "enemy-family/vine-constructs",
        name: "Creeper Tendril",
        description:
          "A vine cluster that detached from the main root network and learned to ambush. Lies flat against greenhouse glass until something warm walks past, then wraps and squeezes. Stronger than it looks.",
        attack: 11,
        defense: 7,
        hp: 22,
        speed: 14,
        threat: 25,
        actions: [
          {
            id: "action/creeper-tendril/vine-lash",
            name: "Vine Lash",
            weight: 4,
            basePower: 12,
            targeting: "single",
            tags: ["entangle"],
          },
          {
            id: "action/creeper-tendril/root-trip",
            name: "Root Trip",
            weight: 6,
            basePower: 8,
            targeting: "single",
            tags: ["ambush"],
          },
        ],
        tags: ["entangle", "ambush"],
        dropTableId: "drop-table/vine-constructs-regular",
      },
      {
        enemyTemplateId: "enemy/trellis-golem",
        familyId: "enemy-family/vine-constructs",
        name: "Trellis Golem",
        description:
          "A garden trellis wrapped in so much vine mass that it walks. Wooden lattice skeleton, living plant musculature, a garden hose for a spine. Carries a planter box in each hand like improvised shields.",
        attack: 16,
        defense: 15,
        hp: 48,
        speed: 10,
        threat: 46,
        actions: [
          {
            id: "action/trellis-golem/planter-smash",
            name: "Planter Smash",
            weight: 4,
            basePower: 18,
            targeting: "single",
            tags: ["heavy", "armor-break"],
          },
          {
            id: "action/trellis-golem/pollen-burst",
            name: "Pollen Burst",
            weight: 3,
            basePower: 10,
            targeting: "all",
            tags: ["hazard-synergy", "suppression"],
          },
          {
            id: "action/trellis-golem/root-anchor",
            name: "Root Anchor",
            weight: 3,
            basePower: 12,
            targeting: "weakest",
            tags: ["entangle"],
          },
        ],
        tags: ["heavy", "entangle", "hazard-synergy"],
        dropTableId: "drop-table/vine-constructs-elite",
      },
    ],
  },

  {
    familyId: "enemy-family/suds-constructs",
    name: "Suds Constructs",
    description:
      "Laundromat machinery that fused with its own chemical runoff. Washers, dryers, and detergent dispensers twisted into steam-venting ambulatory masses that slosh through flooded basement corridors. The rinse cycle never ends.",
    siteConceptIds: ["site/flooded-laundromat-basement"],
    members: [
      {
        enemyTemplateId: "enemy/lint-crawler",
        familyId: "enemy-family/suds-constructs",
        name: "Lint Crawler",
        description:
          "A compacted lint mass the size of a laundry bag, held together by static charge and detergent residue. Rolls along wet floors and clings to anything warm. The static discharge when it makes contact is unpleasant.",
        attack: 9,
        defense: 5,
        hp: 22,
        speed: 16,
        threat: 20,
        actions: [
          {
            id: "action/lint-crawler/static-cling",
            name: "Static Cling",
            weight: 5,
            basePower: 10,
            targeting: "single",
            tags: ["entangle"],
          },
          {
            id: "action/lint-crawler/lint-burst",
            name: "Lint Burst",
            weight: 5,
            basePower: 7,
            targeting: "all",
            tags: ["suppression"],
          },
        ],
        tags: ["swarm-pressure", "entangle"],
        dropTableId: "drop-table/suds-constructs-regular",
      },
      {
        enemyTemplateId: "enemy/drum-roller",
        familyId: "enemy-family/suds-constructs",
        name: "Drum Roller",
        description:
          "An industrial washer drum that tore free of its housing and learned to spin-walk on protruding agitator fins. Filled with scalding water and whatever was in the last load. Charges in straight lines and bounces off walls.",
        attack: 16,
        defense: 14,
        hp: 45,
        speed: 12,
        threat: 44,
        actions: [
          {
            id: "action/drum-roller/spin-charge",
            name: "Spin Charge",
            weight: 4,
            basePower: 18,
            targeting: "single",
            tags: ["heavy"],
          },
          {
            id: "action/drum-roller/scald-spray",
            name: "Scald Spray",
            weight: 3,
            basePower: 12,
            targeting: "all",
            tags: ["hazard-synergy", "corrosive"],
          },
          {
            id: "action/drum-roller/agitator-grind",
            name: "Agitator Grind",
            weight: 3,
            basePower: 14,
            targeting: "weakest",
            tags: ["armor-break"],
          },
        ],
        tags: ["heavy", "hazard-synergy", "armor-break"],
        dropTableId: "drop-table/suds-constructs-elite",
      },
    ],
  },

  {
    familyId: "enemy-family/cellar-dwellers",
    name: "Cellar Dwellers",
    description:
      "Domestic objects from a basement apartment that kept furnishing itself after the tenants left. Radiators, folding chairs, and box fans reassembled into territorial masses that defend rooms nobody lives in anymore. The mail slot still accepts deliveries.",
    siteConceptIds: ["site/condemned-residential-basement"],
    members: [
      {
        enemyTemplateId: "enemy/radiator-creep",
        familyId: "enemy-family/cellar-dwellers",
        name: "Radiator Creep",
        description:
          "A cast-iron radiator that tore itself off the wall and drags itself by its own pipes. Leaks scalding water from every joint. The thermostat dial on top still clicks between settings, none of which are 'off.'",
        attack: 12,
        defense: 10,
        hp: 32,
        speed: 8,
        threat: 28,
        actions: [
          {
            id: "action/radiator-creep/pipe-swing",
            name: "Pipe Swing",
            weight: 5,
            basePower: 14,
            targeting: "single",
            tags: ["heavy"],
          },
          {
            id: "action/radiator-creep/steam-hiss",
            name: "Steam Hiss",
            weight: 5,
            basePower: 8,
            targeting: "all",
            tags: ["suppression", "hazard-synergy"],
          },
        ],
        tags: ["heavy", "suppression"],
        dropTableId: "drop-table/cellar-dwellers-regular",
      },
      {
        enemyTemplateId: "enemy/box-fan-swarm",
        familyId: "enemy-family/cellar-dwellers",
        name: "Box Fan Swarm",
        description:
          "A cluster of oscillating box fans wired together with extension cords, hovering on blade-draft and bad physics. The cords trail behind like tentacles. Operators near them report the air tasting like pennies.",
        attack: 10,
        defense: 6,
        hp: 24,
        speed: 18,
        threat: 26,
        actions: [
          {
            id: "action/box-fan-swarm/blade-pass",
            name: "Blade Pass",
            weight: 5,
            basePower: 12,
            targeting: "single",
            tags: ["hit-and-run"],
          },
          {
            id: "action/box-fan-swarm/cord-tangle",
            name: "Cord Tangle",
            weight: 5,
            basePower: 8,
            targeting: "single",
            tags: ["entangle"],
          },
        ],
        tags: ["hit-and-run", "swarm-pressure", "entangle"],
        dropTableId: "drop-table/cellar-dwellers-regular",
      },
      {
        enemyTemplateId: "enemy/fridge-hulk",
        familyId: "enemy-family/cellar-dwellers",
        name: "Fridge Hulk",
        description:
          "A full-size refrigerator that stands upright and walks on compressor legs. The door opens and slams shut with enough force to bend rebar. Whatever is inside expired a long time ago and is not improving with age.",
        attack: 18,
        defense: 16,
        hp: 52,
        speed: 10,
        threat: 50,
        actions: [
          {
            id: "action/fridge-hulk/door-slam",
            name: "Door Slam",
            weight: 4,
            basePower: 20,
            targeting: "single",
            tags: ["heavy", "armor-break"],
          },
          {
            id: "action/fridge-hulk/expired-gas",
            name: "Expired Gas",
            weight: 3,
            basePower: 10,
            targeting: "all",
            tags: ["suppression", "corrosive"],
          },
          {
            id: "action/fridge-hulk/compressor-charge",
            name: "Compressor Charge",
            weight: 3,
            basePower: 16,
            targeting: "weakest",
            tags: ["heavy"],
          },
        ],
        tags: ["heavy", "armor-break", "suppression"],
        dropTableId: "drop-table/cellar-dwellers-elite",
      },
    ],
  },

  {
    familyId: "enemy-family/court-echoes",
    name: "Court Echoes",
    description:
      "Athletic equipment and gymnasium fixtures animated by the rec center's residual competitive energy. Basketballs that hunt in packs, bleacher seats that snap shut, and gymnastics apparatus that executes routines no coach assigned. The scoreboard updates in real time.",
    siteConceptIds: ["site/closed-community-center"],
    members: [
      {
        enemyTemplateId: "enemy/rebound-hunter",
        familyId: "enemy-family/court-echoes",
        name: "Rebound Hunter",
        description:
          "A basketball inflated to dangerous PSI, bouncing at lethal velocity through gymnasium corridors. Changes direction on contact with walls, floors, and operators. The impact sounds like a gunshot in an enclosed space.",
        attack: 11,
        defense: 4,
        hp: 20,
        speed: 20,
        threat: 24,
        actions: [
          {
            id: "action/rebound-hunter/ricochet",
            name: "Ricochet",
            weight: 6,
            basePower: 12,
            targeting: "single",
            tags: ["hit-and-run"],
          },
          {
            id: "action/rebound-hunter/court-press",
            name: "Court Press",
            weight: 4,
            basePower: 8,
            targeting: "all",
            tags: ["swarm-pressure"],
          },
        ],
        tags: ["hit-and-run", "swarm-pressure"],
        dropTableId: "drop-table/court-echoes-regular",
      },
      {
        enemyTemplateId: "enemy/bleacher-maw",
        familyId: "enemy-family/court-echoes",
        name: "Bleacher Maw",
        description:
          "A section of retractable bleacher seating that folds and unfolds like a jaw. Lures operators into the gap between rows, then snaps shut. The seat numbers are still visible if you look while it's chewing.",
        attack: 15,
        defense: 13,
        hp: 42,
        speed: 10,
        threat: 40,
        actions: [
          {
            id: "action/bleacher-maw/seat-trap",
            name: "Seat Trap",
            weight: 4,
            basePower: 18,
            targeting: "single",
            tags: ["entangle", "heavy"],
          },
          {
            id: "action/bleacher-maw/fold-crush",
            name: "Fold Crush",
            weight: 3,
            basePower: 14,
            targeting: "single",
            tags: ["armor-break"],
          },
          {
            id: "action/bleacher-maw/row-rattle",
            name: "Row Rattle",
            weight: 3,
            basePower: 10,
            targeting: "all",
            tags: ["suppression"],
          },
        ],
        tags: ["entangle", "heavy", "suppression"],
        dropTableId: "drop-table/court-echoes-elite",
      },
    ],
  },

  {
    familyId: "enemy-family/freezer-fauna",
    name: "Freezer Fauna",
    description:
      "Cold storage inventory that stopped being inventory. Frozen meat, dairy crates, and refrigeration coils fused into ambulatory masses preserved at temperatures that should not sustain movement. The cold that radiates from them is wrong — it numbs thoughts before it numbs skin.",
    siteConceptIds: ["site/corner-deli-cold-storage"],
    members: [
      {
        enemyTemplateId: "enemy/frost-skitter",
        familyId: "enemy-family/freezer-fauna",
        name: "Frost Skitter",
        description:
          "A frozen poultry carcass on ice-crystal legs, skittering across shelving units with unnatural agility. The freezer burn on its surface crackles on contact. Operators report it smells like a walk-in that lost power for a week and then got colder.",
        attack: 10,
        defense: 6,
        hp: 22,
        speed: 17,
        threat: 22,
        actions: [
          {
            id: "action/frost-skitter/ice-scratch",
            name: "Ice Scratch",
            weight: 6,
            basePower: 10,
            targeting: "single",
            tags: ["ambush"],
          },
          {
            id: "action/frost-skitter/cold-snap",
            name: "Cold Snap",
            weight: 4,
            basePower: 8,
            targeting: "all",
            tags: ["suppression"],
          },
        ],
        tags: ["ambush", "swarm-pressure"],
        dropTableId: "drop-table/freezer-fauna-regular",
      },
      {
        enemyTemplateId: "enemy/coil-serpent",
        familyId: "enemy-family/freezer-fauna",
        name: "Coil Serpent",
        description:
          "Refrigeration coils that unwound from the ceiling and learned to constrict. Copper tubing filled with coolant that frosts on contact. Moves by contracting in waves along the floor and walls. The compressor sound it makes is almost soothing until it wraps around an ankle.",
        attack: 14,
        defense: 10,
        hp: 38,
        speed: 14,
        threat: 38,
        actions: [
          {
            id: "action/coil-serpent/frost-constrict",
            name: "Frost Constrict",
            weight: 4,
            basePower: 16,
            targeting: "single",
            tags: ["entangle"],
          },
          {
            id: "action/coil-serpent/coolant-leak",
            name: "Coolant Leak",
            weight: 3,
            basePower: 12,
            targeting: "all",
            tags: ["hazard-synergy", "corrosive"],
          },
          {
            id: "action/coil-serpent/deep-freeze",
            name: "Deep Freeze",
            weight: 3,
            basePower: 14,
            targeting: "weakest",
            tags: ["suppression"],
          },
        ],
        tags: ["entangle", "hazard-synergy", "suppression"],
        dropTableId: "drop-table/freezer-fauna-elite",
      },
    ],
  },

  // ── E-rank families ──────────────────────────────────────────────────

  {
    familyId: "enemy-family/aquatic-horrors",
    name: "Aquatic Horrors",
    description:
      "Former exhibit specimens — fish, eels, jellyfish — that kept growing after the tanks stopped being tanks. The water they move through does not obey normal physics. They are too large for the spaces they occupy and do not seem to care.",
    siteConceptIds: ["site/infested-aquarium"],
    members: [
      {
        enemyTemplateId: "enemy/glass-eel",
        familyId: "enemy-family/aquatic-horrors",
        name: "Glass Eel",
        description:
          "An eel that grew transparent and six feet longer than biology allows. Swims through air in flooded corridors as easily as water. The teeth are the only part that stayed opaque.",
        attack: 14,
        defense: 9,
        hp: 32,
        speed: 20,
        threat: 35,
        actions: [
          {
            id: "action/glass-eel/translucent-strike",
            name: "Translucent Strike",
            weight: 5,
            basePower: 16,
            targeting: "single",
            tags: ["ambush"],
          },
          {
            id: "action/glass-eel/conductive-lash",
            name: "Conductive Lash",
            weight: 5,
            basePower: 12,
            targeting: "single",
            tags: ["hit-and-run"],
          },
        ],
        tags: ["ambush", "hit-and-run"],
        dropTableId: "drop-table/dungeon-f-regular",
      },
      {
        enemyTemplateId: "enemy/bloom-jelly",
        familyId: "enemy-family/aquatic-horrors",
        name: "Bloom Jelly",
        description:
          "A jellyfish the size of a weather balloon, trailing stinger filaments through flooded exhibit halls. The bell pulses with bioluminescent light that makes it hard to look at directly. Contact with the filaments is inadvisable.",
        attack: 16,
        defense: 10,
        hp: 38,
        speed: 12,
        threat: 38,
        actions: [
          {
            id: "action/bloom-jelly/filament-sweep",
            name: "Filament Sweep",
            weight: 4,
            basePower: 14,
            targeting: "all",
            tags: ["corrosive"],
          },
          {
            id: "action/bloom-jelly/pressure-pulse",
            name: "Pressure Pulse",
            weight: 6,
            basePower: 10,
            targeting: "all",
            tags: ["suppression"],
          },
        ],
        tags: ["corrosive", "suppression"],
        dropTableId: "drop-table/dungeon-f-regular",
      },
      {
        enemyTemplateId: "enemy/tank-breacher",
        familyId: "enemy-family/aquatic-horrors",
        name: "Tank Breacher",
        description:
          "Something that outgrew its exhibit tank and took the acrylic wall with it as armor plating. Crab-shaped, building-material heavy, and angry about the enclosure it can no longer fit inside. The exhibit placard is still stuck to its shell.",
        attack: 24,
        defense: 18,
        hp: 70,
        speed: 14,
        threat: 62,
        actions: [
          {
            id: "action/tank-breacher/acrylic-ram",
            name: "Acrylic Ram",
            weight: 4,
            basePower: 26,
            targeting: "single",
            tags: ["heavy", "armor-break"],
          },
          {
            id: "action/tank-breacher/flood-surge",
            name: "Flood Surge",
            weight: 3,
            basePower: 18,
            targeting: "all",
            tags: ["hazard-synergy"],
          },
          {
            id: "action/tank-breacher/shell-clamp",
            name: "Shell Clamp",
            weight: 3,
            basePower: 20,
            targeting: "weakest",
            tags: ["entangle"],
          },
        ],
        tags: ["heavy", "armor-break", "hazard-synergy"],
        dropTableId: "drop-table/dungeon-f-elite",
      },
    ],
  },

  {
    familyId: "enemy-family/mannequin-stalkers",
    name: "Mannequin Stalkers",
    description:
      "Department store display mannequins that move when unobserved. Fiberglass bodies dressed in last season's inventory, repositioning themselves between aisles to cut off exits. They do not animate — they simply are not where they were a moment ago.",
    siteConceptIds: ["site/shuttered-department-store"],
    members: [
      {
        enemyTemplateId: "enemy/display-figure",
        familyId: "enemy-family/mannequin-stalkers",
        name: "Display Figure",
        description:
          "A headless mannequin in business casual that relocates when line of sight breaks. Attacks with rigid fiberglass limbs at joints that should not articulate. The price tag is still attached.",
        attack: 15,
        defense: 10,
        hp: 35,
        speed: 18,
        threat: 36,
        actions: [
          {
            id: "action/display-figure/blind-reposition",
            name: "Blind Reposition",
            weight: 5,
            basePower: 16,
            targeting: "single",
            tags: ["ambush"],
          },
          {
            id: "action/display-figure/rigid-swipe",
            name: "Rigid Swipe",
            weight: 5,
            basePower: 12,
            targeting: "single",
            tags: ["hit-and-run"],
          },
        ],
        tags: ["ambush", "hit-and-run"],
        dropTableId: "drop-table/dungeon-f-regular",
      },
      {
        enemyTemplateId: "enemy/perfume-specter",
        familyId: "enemy-family/mannequin-stalkers",
        name: "Perfume Specter",
        description:
          "A fragrance counter display that became ambulatory. Sprays aerosolized wrong-perfume that induces disorientation and mild hallucinations. Smells like department store samples from a store that never existed.",
        attack: 13,
        defense: 8,
        hp: 30,
        speed: 16,
        threat: 32,
        actions: [
          {
            id: "action/perfume-specter/sample-spray",
            name: "Sample Spray",
            weight: 4,
            basePower: 12,
            targeting: "all",
            tags: ["suppression"],
          },
          {
            id: "action/perfume-specter/counter-shove",
            name: "Counter Shove",
            weight: 6,
            basePower: 14,
            targeting: "single",
          },
        ],
        tags: ["suppression", "ranged"],
        dropTableId: "drop-table/dungeon-f-regular",
      },
      {
        enemyTemplateId: "enemy/fitting-room-mimic",
        familyId: "enemy-family/mannequin-stalkers",
        name: "Fitting Room Mimic",
        description:
          "A fitting room stall that walks on curtain-rod legs. Lures operators inside with spatial distortion that makes the interior look like an exit. The door locks from the outside, and the mirrors do not show your reflection.",
        attack: 22,
        defense: 16,
        hp: 65,
        speed: 14,
        threat: 58,
        actions: [
          {
            id: "action/fitting-room-mimic/curtain-trap",
            name: "Curtain Trap",
            weight: 4,
            basePower: 24,
            targeting: "single",
            tags: ["entangle", "ambush"],
          },
          {
            id: "action/fitting-room-mimic/mirror-shatter",
            name: "Mirror Shatter",
            weight: 3,
            basePower: 18,
            targeting: "all",
            tags: ["ranged"],
          },
          {
            id: "action/fitting-room-mimic/wrong-reflection",
            name: "Wrong Reflection",
            weight: 3,
            basePower: 14,
            targeting: "weakest",
            tags: ["suppression"],
          },
        ],
        tags: ["entangle", "ambush", "suppression"],
        dropTableId: "drop-table/dungeon-f-elite",
      },
    ],
  },

  {
    familyId: "enemy-family/rebar-constructs",
    name: "Rebar Constructs",
    description:
      "Construction materials that kept building without a blueprint. Rebar, wet concrete, and scaffold framing twisted into ambulatory structures that patrol half-finished floors. They add to themselves from debris, growing heavier with each circuit.",
    siteConceptIds: ["site/collapsed-construction-site"],
    members: [
      {
        enemyTemplateId: "enemy/scaffold-spider",
        familyId: "enemy-family/rebar-constructs",
        name: "Scaffold Spider",
        description:
          "A scaffold frame that folded itself into an eight-legged climbing rig. Traverses vertical surfaces and drops rebar spikes from above. The safety netting it drags behind it is not for safety.",
        attack: 16,
        defense: 11,
        hp: 38,
        speed: 18,
        threat: 38,
        actions: [
          {
            id: "action/scaffold-spider/rebar-drop",
            name: "Rebar Drop",
            weight: 5,
            basePower: 18,
            targeting: "single",
            tags: ["ambush", "ranged"],
          },
          {
            id: "action/scaffold-spider/net-tangle",
            name: "Net Tangle",
            weight: 5,
            basePower: 10,
            targeting: "single",
            tags: ["entangle"],
          },
        ],
        tags: ["ambush", "ranged", "entangle"],
        dropTableId: "drop-table/dungeon-f-regular",
      },
      {
        enemyTemplateId: "enemy/wet-pour",
        familyId: "enemy-family/rebar-constructs",
        name: "Wet Pour",
        description:
          "A mass of uncured concrete that moves like an amoeba, absorbing debris into its body as ballast. Slow but nearly impossible to hurt once it hardens around a rebar skeleton. Smells like a job site in August.",
        attack: 14,
        defense: 16,
        hp: 50,
        speed: 10,
        threat: 42,
        actions: [
          {
            id: "action/wet-pour/engulf",
            name: "Engulf",
            weight: 4,
            basePower: 16,
            targeting: "single",
            tags: ["entangle", "heavy"],
          },
          {
            id: "action/wet-pour/debris-spray",
            name: "Debris Spray",
            weight: 6,
            basePower: 12,
            targeting: "all",
            tags: ["ranged", "hazard-synergy"],
          },
        ],
        tags: ["heavy", "entangle", "hazard-synergy"],
        dropTableId: "drop-table/dungeon-f-regular",
      },
      {
        enemyTemplateId: "enemy/crane-arm",
        familyId: "enemy-family/rebar-constructs",
        name: "Crane Arm",
        description:
          "A detached crane boom section that drags itself across unfinished floors like a mechanical serpent. The cable winch at its tip still operates, swinging a concrete counterweight in wide arcs. Nobody is in the operator cabin.",
        attack: 26,
        defense: 20,
        hp: 75,
        speed: 16,
        threat: 66,
        actions: [
          {
            id: "action/crane-arm/counterweight-swing",
            name: "Counterweight Swing",
            weight: 4,
            basePower: 28,
            targeting: "all",
            tags: ["heavy", "armor-break"],
          },
          {
            id: "action/crane-arm/cable-snare",
            name: "Cable Snare",
            weight: 3,
            basePower: 18,
            targeting: "single",
            tags: ["entangle"],
          },
          {
            id: "action/crane-arm/structural-collapse",
            name: "Structural Collapse",
            weight: 3,
            basePower: 22,
            targeting: "weakest",
            tags: ["hazard-synergy"],
          },
        ],
        tags: ["heavy", "armor-break", "entangle"],
        dropTableId: "drop-table/dungeon-f-elite",
      },
    ],
  },

  {
    familyId: "enemy-family/conduit-crawlers",
    name: "Conduit Crawlers",
    description:
      "Electrical infrastructure that started hunting. Cable bundles, junction boxes, and transformer coils rewired into predatory configurations that navigate the station's grid by current flow. They arc before they strike.",
    siteConceptIds: ["site/derelict-power-station"],
    members: [
      {
        enemyTemplateId: "enemy/live-wire",
        familyId: "enemy-family/conduit-crawlers",
        name: "Live Wire",
        description:
          "A severed power cable that moves like a whip-snake. Sparks continuously from the exposed end. Fast, erratic, and attracted to anything conductive. Operators in metal armor learn this the hard way.",
        attack: 15,
        defense: 8,
        hp: 30,
        speed: 22,
        threat: 34,
        actions: [
          {
            id: "action/live-wire/arc-lash",
            name: "Arc Lash",
            weight: 5,
            basePower: 16,
            targeting: "single",
            tags: ["hit-and-run"],
          },
          {
            id: "action/live-wire/chain-spark",
            name: "Chain Spark",
            weight: 5,
            basePower: 10,
            targeting: "all",
            tags: ["ranged"],
          },
        ],
        tags: ["hit-and-run", "ranged"],
        dropTableId: "drop-table/dungeon-f-regular",
      },
      {
        enemyTemplateId: "enemy/junction-crawler",
        familyId: "enemy-family/conduit-crawlers",
        name: "Junction Crawler",
        description:
          "A junction box that tore free of its wall mount and grew cable-bundle legs. Scuttles across ceilings trailing live wires. The breaker switches on its face click on and off in patterns that almost mean something.",
        attack: 18,
        defense: 12,
        hp: 42,
        speed: 16,
        threat: 42,
        actions: [
          {
            id: "action/junction-crawler/breaker-overload",
            name: "Breaker Overload",
            weight: 4,
            basePower: 18,
            targeting: "all",
            tags: ["hazard-synergy", "suppression"],
          },
          {
            id: "action/junction-crawler/cable-bind",
            name: "Cable Bind",
            weight: 6,
            basePower: 14,
            targeting: "single",
            tags: ["entangle"],
          },
        ],
        tags: ["hazard-synergy", "suppression", "entangle"],
        dropTableId: "drop-table/dungeon-f-regular",
      },
      {
        enemyTemplateId: "enemy/transformer-hulk",
        familyId: "enemy-family/conduit-crawlers",
        name: "Transformer Hulk",
        description:
          "A substation transformer that tore itself off the concrete pad and learned to walk on cable-bundle legs. Hums at a frequency that makes fillings vibrate. The oil inside it is hot and wrong and leaks from seams when it moves.",
        attack: 24,
        defense: 20,
        hp: 72,
        speed: 14,
        threat: 64,
        actions: [
          {
            id: "action/transformer-hulk/voltage-slam",
            name: "Voltage Slam",
            weight: 4,
            basePower: 26,
            targeting: "single",
            tags: ["heavy", "armor-break"],
          },
          {
            id: "action/transformer-hulk/magnetic-pulse",
            name: "Magnetic Pulse",
            weight: 3,
            basePower: 20,
            targeting: "all",
            tags: ["suppression", "hazard-synergy"],
          },
          {
            id: "action/transformer-hulk/oil-leak",
            name: "Oil Leak",
            weight: 3,
            basePower: 14,
            targeting: "weakest",
            tags: ["corrosive"],
          },
        ],
        tags: ["heavy", "armor-break", "suppression"],
        dropTableId: "drop-table/dungeon-f-elite",
      },
    ],
  },

  // ── F-rank families (continued) ────────────────────────────────────────

  {
    familyId: "enemy-family/transit-haunts",
    name: "Transit Haunts",
    description:
      "Leftover commuter energy compressed into shapes. Turnstile arms that grab, bench seats that fold shut, map displays that scream the wrong stops. They move on a schedule that stopped making sense months ago.",
    siteConceptIds: ["site/sealed-subway-platform"],
    members: [
      {
        enemyTemplateId: "enemy/turnstile-snapper",
        familyId: "enemy-family/transit-haunts",
        name: "Turnstile Snapper",
        description:
          "A subway turnstile arm that detached and learned to crawl. Snaps shut on anything that passes through its invisible gate. Fast, erratic, and surprisingly loud.",
        attack: 11,
        defense: 5,
        hp: 22,
        speed: 18,
        threat: 24,
        actions: [
          {
            id: "action/turnstile-snapper/gate-snap",
            name: "Gate Snap",
            weight: 6,
            basePower: 13,
            targeting: "single",
            tags: ["ambush"],
          },
          {
            id: "action/turnstile-snapper/fare-dodge",
            name: "Fare Dodge",
            weight: 4,
            basePower: 8,
            targeting: "single",
            tags: ["hit-and-run"],
          },
        ],
        tags: ["ambush", "hit-and-run"],
        dropTableId: "drop-table/transit-haunts-regular",
      },
      {
        enemyTemplateId: "enemy/bench-mimic",
        familyId: "enemy-family/transit-haunts",
        name: "Bench Mimic",
        description:
          "A platform bench that unfolds into a flat, heavy shape and charges. The seats are teeth now. It waits until you sit down.",
        attack: 16,
        defense: 14,
        hp: 46,
        speed: 10,
        threat: 44,
        actions: [
          {
            id: "action/bench-mimic/fold-crush",
            name: "Fold Crush",
            weight: 5,
            basePower: 18,
            targeting: "single",
            tags: ["heavy", "entangle"],
          },
          {
            id: "action/bench-mimic/announcement-shriek",
            name: "Announcement Shriek",
            weight: 3,
            basePower: 10,
            targeting: "all",
            tags: ["suppression"],
          },
          {
            id: "action/bench-mimic/platform-edge",
            name: "Platform Edge",
            weight: 2,
            basePower: 14,
            targeting: "weakest",
            tags: ["ambush"],
          },
        ],
        tags: ["heavy", "entangle", "suppression"],
        dropTableId: "drop-table/transit-haunts-elite",
      },
    ],
  },

  {
    familyId: "enemy-family/fume-wraiths",
    name: "Fume Wraiths",
    description:
      "Acetone and acrylic fumes that condensed into semi-solid shapes. They drift through the salon in slow arcs, burning on contact. The UV lamps make them visible; without light, they are invisible and everywhere.",
    siteConceptIds: ["site/abandoned-nail-salon"],
    members: [
      {
        enemyTemplateId: "enemy/polish-wisp",
        familyId: "enemy-family/fume-wraiths",
        name: "Polish Wisp",
        description:
          "A small cloud of neon-colored chemical vapor. Barely visible, barely solid, and it burns exposed skin on contact. Comes in packs.",
        attack: 9,
        defense: 3,
        hp: 18,
        speed: 20,
        threat: 20,
        actions: [
          {
            id: "action/polish-wisp/chemical-kiss",
            name: "Chemical Kiss",
            weight: 6,
            basePower: 10,
            targeting: "single",
            tags: ["corrosive"],
          },
          {
            id: "action/polish-wisp/drift-scatter",
            name: "Drift Scatter",
            weight: 4,
            basePower: 6,
            targeting: "all",
            tags: ["swarm-pressure"],
          },
        ],
        tags: ["swarm-pressure", "corrosive"],
        dropTableId: "drop-table/fume-wraiths-regular",
      },
      {
        enemyTemplateId: "enemy/acetone-shade",
        familyId: "enemy-family/fume-wraiths",
        name: "Acetone Shade",
        description:
          "A human-shaped concentration of solvent fumes. It moves like someone walking between stations, and it dissolves anything it embraces. The smell alone causes dizziness.",
        attack: 17,
        defense: 8,
        hp: 40,
        speed: 14,
        threat: 42,
        actions: [
          {
            id: "action/acetone-shade/solvent-embrace",
            name: "Solvent Embrace",
            weight: 4,
            basePower: 18,
            targeting: "single",
            tags: ["corrosive", "entangle"],
          },
          {
            id: "action/acetone-shade/fume-cloud",
            name: "Fume Cloud",
            weight: 3,
            basePower: 10,
            targeting: "all",
            tags: ["hazard-synergy", "suppression"],
          },
          {
            id: "action/acetone-shade/nail-file-slash",
            name: "Nail File Slash",
            weight: 3,
            basePower: 14,
            targeting: "weakest",
            tags: ["hit-and-run"],
          },
        ],
        tags: ["corrosive", "hazard-synergy", "entangle"],
        dropTableId: "drop-table/fume-wraiths-elite",
      },
    ],
  },

  {
    familyId: "enemy-family/rust-creepers",
    name: "Rust Creepers",
    description:
      "The fire escape metalwork learned to move. Handrails slither, bolts unscrew themselves and orbit in threatening patterns, and entire landing platforms detach and reattach at wrong heights. They are territorial about vertical space.",
    siteConceptIds: ["site/condemned-fire-escape"],
    members: [
      {
        enemyTemplateId: "enemy/railing-serpent",
        familyId: "enemy-family/rust-creepers",
        name: "Railing Serpent",
        description:
          "A detached handrail that moves like a metal snake. Whips around corners and strikes from above. The rust makes it worse — every hit leaves particulate in the wound.",
        attack: 12,
        defense: 8,
        hp: 28,
        speed: 16,
        threat: 28,
        actions: [
          {
            id: "action/railing-serpent/rust-lash",
            name: "Rust Lash",
            weight: 5,
            basePower: 14,
            targeting: "single",
            tags: ["corrosive"],
          },
          {
            id: "action/railing-serpent/coil-drop",
            name: "Coil Drop",
            weight: 5,
            basePower: 10,
            targeting: "single",
            tags: ["ambush"],
          },
        ],
        tags: ["ambush", "corrosive"],
        dropTableId: "drop-table/rust-creepers-regular",
      },
      {
        enemyTemplateId: "enemy/landing-crusher",
        familyId: "enemy-family/rust-creepers",
        name: "Landing Crusher",
        description:
          "An entire fire escape landing that folded itself into a heavy, centipede-like shape. It moves vertically and drops on targets from above. The impact is structural.",
        attack: 18,
        defense: 16,
        hp: 52,
        speed: 8,
        threat: 50,
        actions: [
          {
            id: "action/landing-crusher/gravity-drop",
            name: "Gravity Drop",
            weight: 4,
            basePower: 22,
            targeting: "single",
            tags: ["heavy"],
          },
          {
            id: "action/landing-crusher/scaffold-grind",
            name: "Scaffold Grind",
            weight: 3,
            basePower: 12,
            targeting: "all",
            tags: ["armor-break"],
          },
          {
            id: "action/landing-crusher/bolt-spray",
            name: "Bolt Spray",
            weight: 3,
            basePower: 10,
            targeting: "weakest",
            tags: ["ranged"],
          },
        ],
        tags: ["heavy", "armor-break"],
        dropTableId: "drop-table/rust-creepers-elite",
      },
    ],
  },

  {
    familyId: "enemy-family/display-mimics",
    name: "Display Mimics",
    description:
      "Pawned objects that absorbed too much ambient rift energy. Jewelry that bites, electronics that shock, instruments that play themselves and the frequencies hurt. Everything behind the glass has an opinion about being sold.",
    siteConceptIds: ["site/shuttered-pawn-shop"],
    members: [
      {
        enemyTemplateId: "enemy/ring-cluster",
        familyId: "enemy-family/display-mimics",
        name: "Ring Cluster",
        description:
          "A dozen gold rings fused into a spinning mass that orbits the display case. Fast, sharp, and attracted to fingers. The inscription on each one is different and none of them are real.",
        attack: 10,
        defense: 4,
        hp: 20,
        speed: 22,
        threat: 22,
        actions: [
          {
            id: "action/ring-cluster/band-slash",
            name: "Band Slash",
            weight: 6,
            basePower: 11,
            targeting: "single",
            tags: ["hit-and-run"],
          },
          {
            id: "action/ring-cluster/orbit-scatter",
            name: "Orbit Scatter",
            weight: 4,
            basePower: 7,
            targeting: "all",
            tags: ["swarm-pressure"],
          },
        ],
        tags: ["hit-and-run", "swarm-pressure"],
        dropTableId: "drop-table/display-mimics-regular",
      },
      {
        enemyTemplateId: "enemy/guitar-case-maw",
        familyId: "enemy-family/display-mimics",
        name: "Guitar Case Maw",
        description:
          "A guitar case that opens like a mouth. The instrument inside is gone but the strings remain, and they reach. Slow to close, fast to grab. The velvet lining is wet.",
        attack: 14,
        defense: 12,
        hp: 44,
        speed: 10,
        threat: 42,
        actions: [
          {
            id: "action/guitar-case-maw/string-snare",
            name: "String Snare",
            weight: 4,
            basePower: 16,
            targeting: "single",
            tags: ["entangle"],
          },
          {
            id: "action/guitar-case-maw/case-slam",
            name: "Case Slam",
            weight: 3,
            basePower: 18,
            targeting: "single",
            tags: ["heavy"],
          },
          {
            id: "action/guitar-case-maw/resonance-howl",
            name: "Resonance Howl",
            weight: 3,
            basePower: 10,
            targeting: "all",
            tags: ["suppression"],
          },
        ],
        tags: ["entangle", "heavy", "suppression"],
        dropTableId: "drop-table/display-mimics-elite",
      },
    ],
  },
  // ── E-rank families (continued) ────────────────────────────────────

  {
    familyId: "enemy-family/reel-phantoms",
    name: "Reel Phantoms",
    description:
      "The projectors in this condemned multiplex never stopped running. Film stock has unspooled into animate strips that whip through darkened aisles, the seats fold and bite, and the light from the projector burns at frequencies that leave afterimages in your memory, not your retinas.",
    siteConceptIds: ["site/abandoned-movie-theater"],
    members: [
      {
        enemyTemplateId: "enemy/film-strip-lash",
        familyId: "enemy-family/reel-phantoms",
        name: "Film Strip Lash",
        description:
          "Unspooled 35mm film that moves like a bullwhip. The frames show scenes from movies that were never made. Getting wrapped in it means watching them up close.",
        attack: 14,
        defense: 8,
        hp: 30,
        speed: 20,
        threat: 34,
        actions: [
          {
            id: "action/film-strip-lash/reel-whip",
            name: "Reel Whip",
            weight: 5,
            basePower: 14,
            targeting: "single",
            tags: ["hit-and-run"],
          },
          {
            id: "action/film-strip-lash/tangle-wrap",
            name: "Tangle Wrap",
            weight: 5,
            basePower: 10,
            targeting: "single",
            tags: ["entangle"],
          },
        ],
        tags: ["hit-and-run", "entangle"],
        dropTableId: "drop-table/reel-phantoms-regular",
      },
      {
        enemyTemplateId: "enemy/seat-chomper",
        familyId: "enemy-family/reel-phantoms",
        name: "Seat Chomper",
        description:
          "A row of theater seats that folds and unfolds like a jaw. The upholstery is sticky with old butter and something else. Rows behind you fold closed when you're not looking.",
        attack: 16,
        defense: 14,
        hp: 42,
        speed: 10,
        threat: 40,
        actions: [
          {
            id: "action/seat-chomper/fold-crush",
            name: "Fold Crush",
            weight: 4,
            basePower: 18,
            targeting: "single",
            tags: ["heavy"],
          },
          {
            id: "action/seat-chomper/armrest-snap",
            name: "Armrest Snap",
            weight: 3,
            basePower: 12,
            targeting: "all",
            tags: ["armor-break"],
          },
          {
            id: "action/seat-chomper/sticky-trap",
            name: "Sticky Trap",
            weight: 3,
            basePower: 8,
            targeting: "weakest",
            tags: ["entangle"],
          },
        ],
        tags: ["heavy", "armor-break", "entangle"],
        dropTableId: "drop-table/reel-phantoms-regular",
      },
      {
        enemyTemplateId: "enemy/projector-beast",
        familyId: "enemy-family/reel-phantoms",
        name: "Projector Beast",
        description:
          "A ceiling-mounted projector that detached and grew legs from film reels. Crawls across the ceiling and fires concentrated light that burns skin and leaves afterimages of scenes from impossible films.",
        attack: 22,
        defense: 14,
        hp: 58,
        speed: 16,
        threat: 55,
        actions: [
          {
            id: "action/projector-beast/burn-reel",
            name: "Burn Reel",
            weight: 4,
            basePower: 22,
            targeting: "single",
            tags: ["ranged"],
          },
          {
            id: "action/projector-beast/flicker-barrage",
            name: "Flicker Barrage",
            weight: 3,
            basePower: 14,
            targeting: "all",
            tags: ["suppression"],
          },
          {
            id: "action/projector-beast/preview-flash",
            name: "Preview Flash",
            weight: 3,
            basePower: 10,
            targeting: "all",
            tags: ["hazard-synergy"],
          },
        ],
        tags: ["ranged", "suppression", "hazard-synergy"],
        dropTableId: "drop-table/reel-phantoms-elite",
      },
    ],
  },

  {
    familyId: "enemy-family/cistern-dwellers",
    name: "Cistern Dwellers",
    description:
      "The water tower on the roof stopped being a water tower when the rift hit. Now it's an enclosed aquatic ecosystem running on rules that would make a marine biologist resign. The algae is animate, the barnacles fire projectiles, and something in the dark water uses bioluminescence to hunt.",
    siteConceptIds: ["site/decommissioned-water-tower"],
    members: [
      {
        enemyTemplateId: "enemy/algae-crawler",
        familyId: "enemy-family/cistern-dwellers",
        name: "Algae Crawler",
        description:
          "A thick mat of animate algae that slides across wet surfaces and pulls targets into standing water. Smells like a swimming pool that has been closed for a decade. The grip is surprisingly strong.",
        attack: 12,
        defense: 10,
        hp: 32,
        speed: 14,
        threat: 32,
        actions: [
          {
            id: "action/algae-crawler/slime-pull",
            name: "Slime Pull",
            weight: 5,
            basePower: 12,
            targeting: "single",
            tags: ["entangle"],
          },
          {
            id: "action/algae-crawler/spore-burst",
            name: "Spore Burst",
            weight: 5,
            basePower: 8,
            targeting: "all",
            tags: ["hazard-synergy"],
          },
        ],
        tags: ["entangle", "hazard-synergy"],
        dropTableId: "drop-table/cistern-dwellers-regular",
      },
      {
        enemyTemplateId: "enemy/pipe-barnacle",
        familyId: "enemy-family/cistern-dwellers",
        name: "Pipe Barnacle",
        description:
          "Clusters of calcified organisms that cling to pipes and fire hardened spines when anything approaches. They creak when building pressure. Smart operators learn to listen.",
        attack: 15,
        defense: 16,
        hp: 36,
        speed: 8,
        threat: 36,
        actions: [
          {
            id: "action/pipe-barnacle/spine-volley",
            name: "Spine Volley",
            weight: 4,
            basePower: 16,
            targeting: "single",
            tags: ["ranged"],
          },
          {
            id: "action/pipe-barnacle/calcified-shell",
            name: "Calcified Shell",
            weight: 6,
            basePower: 10,
            targeting: "single",
            tags: ["heavy"],
          },
        ],
        tags: ["ranged", "heavy"],
        dropTableId: "drop-table/cistern-dwellers-regular",
      },
      {
        enemyTemplateId: "enemy/rust-angler",
        familyId: "enemy-family/cistern-dwellers",
        name: "Rust Angler",
        description:
          "A predatory structure of corroded metal and bioluminescent algae that lurks in dark water. Uses false light to lure targets close, then strikes with pipe-jaw mandibles. The glow is beautiful until you understand what it means.",
        attack: 24,
        defense: 16,
        hp: 62,
        speed: 14,
        threat: 58,
        actions: [
          {
            id: "action/rust-angler/lure-flash",
            name: "Lure Flash",
            weight: 3,
            basePower: 10,
            targeting: "all",
            tags: ["suppression"],
          },
          {
            id: "action/rust-angler/pipe-jaw-clamp",
            name: "Pipe-Jaw Clamp",
            weight: 4,
            basePower: 24,
            targeting: "single",
            tags: ["heavy", "entangle"],
          },
          {
            id: "action/rust-angler/depth-drag",
            name: "Depth Drag",
            weight: 3,
            basePower: 16,
            targeting: "weakest",
            tags: ["ambush"],
          },
        ],
        tags: ["heavy", "entangle", "ambush"],
        dropTableId: "drop-table/cistern-dwellers-elite",
      },
    ],
  },

  // ── D-rank families ──────────────────────────────────────────────────

  {
    familyId: "enemy-family/astral-parasites",
    name: "Astral Parasites",
    description:
      "The observatory telescope connected to somewhere it shouldn't. Now the things on the other side of the lens are climbing through. They feed on observation itself — the act of looking at them makes them stronger. Light bends wrong around them and shadows point toward the dome.",
    siteConceptIds: ["site/warped-rooftop-observatory"],
    members: [
      {
        enemyTemplateId: "enemy/lens-mite",
        familyId: "enemy-family/astral-parasites",
        name: "Lens Mite",
        description:
          "Tiny crystalline organisms that cluster on reflective surfaces. Each one refracts light into spectrums that don't exist. In groups, the combined refraction causes migraines and spatial confusion. They're attracted to eyes.",
        attack: 18,
        defense: 10,
        hp: 38,
        speed: 22,
        threat: 42,
        actions: [
          {
            id: "action/lens-mite/prismatic-scatter",
            name: "Prismatic Scatter",
            weight: 5,
            basePower: 16,
            targeting: "all",
            tags: ["swarm-pressure"],
          },
          {
            id: "action/lens-mite/refraction-sting",
            name: "Refraction Sting",
            weight: 5,
            basePower: 18,
            targeting: "single",
            tags: ["hit-and-run"],
          },
        ],
        tags: ["swarm-pressure", "hit-and-run"],
        dropTableId: "drop-table/astral-parasites-regular",
      },
      {
        enemyTemplateId: "enemy/constellation-stalker",
        familyId: "enemy-family/astral-parasites",
        name: "Constellation Stalker",
        description:
          "A shadow that exists between pinpoints of wrong starlight. It moves by connecting dots — appearing at one light source, vanishing, reappearing at another closer to you. The light is cold and the shadow is colder.",
        attack: 28,
        defense: 16,
        hp: 72,
        speed: 20,
        threat: 68,
        actions: [
          {
            id: "action/constellation-stalker/star-step",
            name: "Star Step",
            weight: 4,
            basePower: 26,
            targeting: "single",
            tags: ["ambush"],
          },
          {
            id: "action/constellation-stalker/void-chill",
            name: "Void Chill",
            weight: 3,
            basePower: 18,
            targeting: "all",
            tags: ["suppression"],
          },
          {
            id: "action/constellation-stalker/gravity-well",
            name: "Gravity Well",
            weight: 3,
            basePower: 14,
            targeting: "weakest",
            tags: ["entangle"],
          },
        ],
        tags: ["ambush", "suppression", "entangle"],
        dropTableId: "drop-table/astral-parasites-elite",
      },
    ],
  },

  {
    familyId: "enemy-family/pressure-spawn",
    name: "Pressure Spawn",
    description:
      "The pumping station under the East River was supposed to move water. Now the water moves itself, and the things growing in the pressurized pipes have adapted to densities that would crush normal matter. They exist at pressures that don't occur naturally on Earth's surface.",
    siteConceptIds: ["site/flooded-pumping-station"],
    members: [
      {
        enemyTemplateId: "enemy/surge-pod",
        familyId: "enemy-family/pressure-spawn",
        name: "Surge Pod",
        description:
          "A pressurized water sac the size of a beach ball, held together by a membrane that shouldn't exist. Floats through flooded corridors and detonates on contact. The water inside is denser than mercury.",
        attack: 20,
        defense: 6,
        hp: 30,
        speed: 18,
        threat: 38,
        actions: [
          {
            id: "action/surge-pod/pressure-burst",
            name: "Pressure Burst",
            weight: 5,
            basePower: 22,
            targeting: "all",
            tags: ["hazard-synergy"],
          },
          {
            id: "action/surge-pod/density-slam",
            name: "Density Slam",
            weight: 5,
            basePower: 18,
            targeting: "single",
            tags: ["heavy"],
          },
        ],
        tags: ["hazard-synergy", "heavy"],
        dropTableId: "drop-table/pressure-spawn-regular",
      },
      {
        enemyTemplateId: "enemy/turbine-eel",
        familyId: "enemy-family/pressure-spawn",
        name: "Turbine Eel",
        description:
          "A creature that evolved inside pressurized pipes — elongated, armored in turbine blades, and fast enough to create wake turbulence in flooded corridors. The spinning blade segments along its body can shear through steel.",
        attack: 30,
        defense: 20,
        hp: 82,
        speed: 18,
        threat: 74,
        actions: [
          {
            id: "action/turbine-eel/blade-pass",
            name: "Blade Pass",
            weight: 4,
            basePower: 28,
            targeting: "single",
            tags: ["armor-break"],
          },
          {
            id: "action/turbine-eel/wake-turbulence",
            name: "Wake Turbulence",
            weight: 3,
            basePower: 16,
            targeting: "all",
            tags: ["hazard-synergy"],
          },
          {
            id: "action/turbine-eel/pipe-constrict",
            name: "Pipe Constrict",
            weight: 3,
            basePower: 22,
            targeting: "weakest",
            tags: ["entangle"],
          },
        ],
        tags: ["armor-break", "hazard-synergy", "entangle"],
        dropTableId: "drop-table/pressure-spawn-elite",
      },
    ],
  },

  {
    familyId: "enemy-family/stage-haunts",
    name: "Stage Haunts",
    description:
      "The rigging loft of a condemned theater where the fly system operates itself. Sandbags swing with lethal precision, costumes move with remembered choreography, and the spotlights track living targets with predatory intent. Six decades of accumulated performances have seeped into the machinery and the machinery has opinions about the blocking.",
    siteConceptIds: ["site/condemned-theater-fly-loft"],
    members: [
      {
        enemyTemplateId: "enemy/sandbag-pendulum",
        familyId: "enemy-family/stage-haunts",
        name: "Sandbag Pendulum",
        description:
          "A counterweight sandbag on a fly line that swings with lethal momentum through the rigging loft. It changes trajectory mid-swing in ways that violate physics. The rope is warm.",
        attack: 20,
        defense: 12,
        hp: 44,
        speed: 16,
        threat: 44,
        actions: [
          {
            id: "action/sandbag-pendulum/pendulum-strike",
            name: "Pendulum Strike",
            weight: 5,
            basePower: 22,
            targeting: "single",
            tags: ["heavy"],
          },
          {
            id: "action/sandbag-pendulum/rope-snap",
            name: "Rope Snap",
            weight: 5,
            basePower: 14,
            targeting: "single",
            tags: ["ranged"],
          },
        ],
        tags: ["heavy", "ranged"],
        dropTableId: "drop-table/stage-haunts-regular",
      },
      {
        enemyTemplateId: "enemy/spotlight-hunter",
        familyId: "enemy-family/stage-haunts",
        name: "Spotlight Hunter",
        description:
          "A follow-spot that detached from its mount and stalks the catwalks on articulated legs made from lighting gels and cable. The beam it projects burns at temperatures that shouldn't come from a theatrical lamp. It tracks movement with predatory focus.",
        attack: 32,
        defense: 18,
        hp: 76,
        speed: 14,
        threat: 70,
        actions: [
          {
            id: "action/spotlight-hunter/focused-burn",
            name: "Focused Burn",
            weight: 4,
            basePower: 30,
            targeting: "single",
            tags: ["ranged"],
          },
          {
            id: "action/spotlight-hunter/strobe-barrage",
            name: "Strobe Barrage",
            weight: 3,
            basePower: 16,
            targeting: "all",
            tags: ["suppression"],
          },
          {
            id: "action/spotlight-hunter/gel-snare",
            name: "Gel Snare",
            weight: 3,
            basePower: 12,
            targeting: "weakest",
            tags: ["entangle"],
          },
        ],
        tags: ["ranged", "suppression", "entangle"],
        dropTableId: "drop-table/stage-haunts-elite",
      },
    ],
  },

  {
    familyId: "enemy-family/lab-specimens",
    name: "Lab Specimens",
    description:
      "A biotech startup's lab kept running after the building was evacuated. The automated systems continued their experiments, and the rift energy supercharged everything in the incubators. Cell cultures became organisms. Centrifuges became predators. The lab equipment has been iterating on its own designs for months and the results are not peer-reviewed.",
    siteConceptIds: ["site/sealed-biotech-lab"],
    members: [
      {
        enemyTemplateId: "enemy/culture-crawler",
        familyId: "enemy-family/lab-specimens",
        name: "Culture Crawler",
        description:
          "An organism that escaped a petri dish and kept growing. Translucent, multi-limbed, and fast. It leaves a trail of rift-reactive fluid that eats through boot soles. The cell structure visible through its skin is wrong in ways that are hard to articulate.",
        attack: 19,
        defense: 8,
        hp: 36,
        speed: 22,
        threat: 42,
        actions: [
          {
            id: "action/culture-crawler/acid-trail",
            name: "Acid Trail",
            weight: 5,
            basePower: 16,
            targeting: "all",
            tags: ["corrosive"],
          },
          {
            id: "action/culture-crawler/pseudopod-lash",
            name: "Pseudopod Lash",
            weight: 5,
            basePower: 18,
            targeting: "single",
            tags: ["hit-and-run"],
          },
        ],
        tags: ["corrosive", "hit-and-run"],
        dropTableId: "drop-table/lab-specimens-regular",
      },
      {
        enemyTemplateId: "enemy/centrifuge-spinner",
        familyId: "enemy-family/lab-specimens",
        name: "Centrifuge Spinner",
        description:
          "A laboratory centrifuge that detached from its mount and learned to move. Spins its rotor at lethal speeds and charges on caster wheels. The samples still loaded in the rotor glow with rift energy and spray on impact.",
        attack: 30,
        defense: 22,
        hp: 84,
        speed: 12,
        threat: 72,
        actions: [
          {
            id: "action/centrifuge-spinner/rotor-charge",
            name: "Rotor Charge",
            weight: 4,
            basePower: 28,
            targeting: "single",
            tags: ["heavy", "armor-break"],
          },
          {
            id: "action/centrifuge-spinner/sample-spray",
            name: "Sample Spray",
            weight: 3,
            basePower: 16,
            targeting: "all",
            tags: ["corrosive", "hazard-synergy"],
          },
          {
            id: "action/centrifuge-spinner/spin-deflect",
            name: "Spin Deflect",
            weight: 3,
            basePower: 12,
            targeting: "single",
            tags: ["suppression"],
          },
        ],
        tags: ["heavy", "armor-break", "corrosive"],
        dropTableId: "drop-table/lab-specimens-elite",
      },
    ],
  },

  {
    familyId: "enemy-family/gravity-lice",
    name: "Gravity Lice",
    description:
      "Dock parasites that adapted to the inverted dry dock's reversed gravity — barnacle-centipede hybrids that cling to ceilings, scuttle across exposed hulls, and drop upward. They colonized the keels of ships that will never launch again and defend the territory with the mindless aggression of organisms that don't know which way down is.",
    siteConceptIds: ["site/inverted-dry-dock"],
    members: [
      {
        enemyTemplateId: "enemy/ceiling-crawler",
        familyId: "enemy-family/gravity-lice",
        name: "Ceiling Crawler",
        description:
          "A segmented arthropod the length of an arm, fused from barnacle shell and centipede legs. Navigates upside-down surfaces at full speed and drops onto operators from above — or below, depending on which gravity is winning. The mandibles click at a frequency that sets teeth on edge.",
        attack: 15,
        defense: 10,
        hp: 36,
        speed: 18,
        threat: 34,
        actions: [
          {
            id: "action/ceiling-crawler/inverted-drop",
            name: "Inverted Drop",
            weight: 5,
            basePower: 16,
            targeting: "single",
            tags: ["ambush"],
          },
          {
            id: "action/ceiling-crawler/mandible-rake",
            name: "Mandible Rake",
            weight: 5,
            basePower: 12,
            targeting: "single",
            tags: ["hit-and-run"],
          },
        ],
        tags: ["ambush", "hit-and-run", "swarm-pressure"],
        dropTableId: "drop-table/gravity-lice-regular",
      },
      {
        enemyTemplateId: "enemy/hull-borer",
        familyId: "enemy-family/gravity-lice",
        name: "Hull Borer",
        description:
          "A drill-headed parasite that chews through ship hulls and dock plating with a rotating calcium bit. Burrows into steel like it's driftwood and emerges from surfaces operators assumed were solid. The entry holes are perfectly circular and disturbingly warm.",
        attack: 18,
        defense: 14,
        hp: 48,
        speed: 12,
        threat: 44,
        actions: [
          {
            id: "action/hull-borer/bore-charge",
            name: "Bore Charge",
            weight: 4,
            basePower: 20,
            targeting: "single",
            tags: ["ambush"],
          },
          {
            id: "action/hull-borer/shell-grind",
            name: "Shell Grind",
            weight: 3,
            basePower: 14,
            targeting: "single",
            tags: ["hit-and-run"],
          },
          {
            id: "action/hull-borer/swarm-call",
            name: "Swarm Call",
            weight: 3,
            basePower: 10,
            targeting: "all",
            tags: ["swarm-pressure"],
          },
        ],
        tags: ["ambush", "hit-and-run", "swarm-pressure"],
        dropTableId: "drop-table/gravity-lice-regular",
      },
      {
        enemyTemplateId: "enemy/keel-tick",
        familyId: "enemy-family/gravity-lice",
        name: "Keel Tick",
        description:
          "A bloated parasitic mass that anchors itself to ship keels with gravity-defiant adhesion. Engorged with something that isn't blood — a luminous fluid that weighs more than it should. When disturbed it detaches and lunges with surprising speed for something that size.",
        attack: 16,
        defense: 16,
        hp: 52,
        speed: 14,
        threat: 48,
        actions: [
          {
            id: "action/keel-tick/anchor-lunge",
            name: "Anchor Lunge",
            weight: 4,
            basePower: 18,
            targeting: "single",
            tags: ["ambush"],
          },
          {
            id: "action/keel-tick/gravity-pulse",
            name: "Gravity Pulse",
            weight: 3,
            basePower: 14,
            targeting: "all",
            tags: ["swarm-pressure"],
          },
          {
            id: "action/keel-tick/leech-grip",
            name: "Leech Grip",
            weight: 3,
            basePower: 12,
            targeting: "weakest",
            tags: ["hit-and-run"],
          },
        ],
        tags: ["ambush", "hit-and-run", "swarm-pressure"],
        dropTableId: "drop-table/gravity-lice-regular",
      },
    ],
  },

  {
    familyId: "enemy-family/fold-walkers",
    name: "Fold Walkers",
    description:
      "Former warehouse inventory that walks through spatial folds. The warehouse row's geometry folded in on itself and the contents adapted — clipboard-faced things assembled from packing material and shipping manifests that step through walls like the walls aren't there. They still follow delivery routes that no longer connect to real addresses.",
    siteConceptIds: ["site/folded-warehouse-row"],
    members: [
      {
        enemyTemplateId: "enemy/packing-shade",
        familyId: "enemy-family/fold-walkers",
        name: "Packing Shade",
        description:
          "A humanoid silhouette made of crumpled packing paper and bubble wrap, held together by tape that reseals itself when cut. Steps sideways through spatial folds and arrives behind operators who were watching the doorway. The bubble wrap pops in sequence when it moves — a countdown nobody asked for.",
        attack: 14,
        defense: 12,
        hp: 40,
        speed: 16,
        threat: 36,
        actions: [
          {
            id: "action/packing-shade/fold-step-strike",
            name: "Fold-Step Strike",
            weight: 5,
            basePower: 16,
            targeting: "single",
            tags: ["heavy"],
          },
          {
            id: "action/packing-shade/tape-bind",
            name: "Tape Bind",
            weight: 5,
            basePower: 12,
            targeting: "single",
            tags: ["entangle"],
          },
        ],
        tags: ["heavy", "suppression", "entangle"],
        dropTableId: "drop-table/fold-walkers-regular",
      },
      {
        enemyTemplateId: "enemy/manifest-crawler",
        familyId: "enemy-family/fold-walkers",
        name: "Manifest Crawler",
        description:
          "A low-slung mass of shipping manifests and invoices that crawls along walls and floors. The paper edges are rigid enough to slice and the text rearranges itself to list the names of operators it touches. It navigates by following addresses that exist in folded space.",
        attack: 16,
        defense: 10,
        hp: 38,
        speed: 16,
        threat: 38,
        actions: [
          {
            id: "action/manifest-crawler/paper-laceration",
            name: "Paper Laceration",
            weight: 4,
            basePower: 18,
            targeting: "single",
            tags: ["suppression"],
          },
          {
            id: "action/manifest-crawler/manifest-wrap",
            name: "Manifest Wrap",
            weight: 3,
            basePower: 14,
            targeting: "single",
            tags: ["entangle"],
          },
          {
            id: "action/manifest-crawler/route-scramble",
            name: "Route Scramble",
            weight: 3,
            basePower: 10,
            targeting: "all",
            tags: ["suppression"],
          },
        ],
        tags: ["heavy", "suppression", "entangle"],
        dropTableId: "drop-table/fold-walkers-regular",
      },
      {
        enemyTemplateId: "enemy/crate-golem",
        familyId: "enemy-family/fold-walkers",
        name: "Crate Golem",
        description:
          "A walking stack of shipping crates held together by cargo straps and spatial impossibility. Each crate opens into a different fold of warehouse space — the contents shift and rearrange between impacts. Hits with the weight of inventory that exists in more than one place at once.",
        attack: 20,
        defense: 16,
        hp: 55,
        speed: 12,
        threat: 50,
        actions: [
          {
            id: "action/crate-golem/freight-slam",
            name: "Freight Slam",
            weight: 4,
            basePower: 22,
            targeting: "single",
            tags: ["heavy"],
          },
          {
            id: "action/crate-golem/strap-snare",
            name: "Strap Snare",
            weight: 3,
            basePower: 14,
            targeting: "weakest",
            tags: ["entangle"],
          },
          {
            id: "action/crate-golem/cargo-crush",
            name: "Cargo Crush",
            weight: 3,
            basePower: 16,
            targeting: "all",
            tags: ["suppression"],
          },
        ],
        tags: ["heavy", "suppression", "entangle"],
        dropTableId: "drop-table/fold-walkers-regular",
      },
    ],
  },

  {
    familyId: "enemy-family/ledger-wraiths",
    name: "Ledger Wraiths",
    description:
      "Bureaucratic paper entities from the sunken revenue office. Filing cabinets that move on their own, forms sharp enough to sever tendons, and receipt tape that binds like wire. The office sank into the harbor bedrock but the paperwork kept processing itself, and now it enforces compliance on anything that enters the flooded corridors.",
    siteConceptIds: ["site/sunken-revenue-office"],
    members: [
      {
        enemyTemplateId: "enemy/filing-swarm",
        familyId: "enemy-family/ledger-wraiths",
        name: "Filing Swarm",
        description:
          "A cloud of loose tax forms and carbon copies that moves with coordinated malice. Individual sheets are razor-edged and the swarm reshuffles itself mid-attack to present fresh cutting surfaces. The forms are dated decades apart but all reference the same overdue account.",
        attack: 14,
        defense: 10,
        hp: 35,
        speed: 18,
        threat: 32,
        actions: [
          {
            id: "action/filing-swarm/paper-storm",
            name: "Paper Storm",
            weight: 5,
            basePower: 14,
            targeting: "all",
            tags: ["ranged"],
          },
          {
            id: "action/filing-swarm/form-cut",
            name: "Form Cut",
            weight: 5,
            basePower: 16,
            targeting: "single",
            tags: ["suppression"],
          },
        ],
        tags: ["suppression", "entangle", "ranged"],
        dropTableId: "drop-table/ledger-wraiths-regular",
      },
      {
        enemyTemplateId: "enemy/receipt-binder",
        familyId: "enemy-family/ledger-wraiths",
        name: "Receipt Binder",
        description:
          "A filing cabinet drawer that extrudes endless receipt tape from its slot like a mechanical tongue. The tape wraps around limbs and tightens with the sound of a dot-matrix printer. The receipts itemize things that haven't happened yet.",
        attack: 16,
        defense: 14,
        hp: 46,
        speed: 14,
        threat: 42,
        actions: [
          {
            id: "action/receipt-binder/tape-lash",
            name: "Tape Lash",
            weight: 4,
            basePower: 16,
            targeting: "single",
            tags: ["ranged"],
          },
          {
            id: "action/receipt-binder/receipt-bind",
            name: "Receipt Bind",
            weight: 3,
            basePower: 14,
            targeting: "single",
            tags: ["entangle"],
          },
          {
            id: "action/receipt-binder/audit-rattle",
            name: "Audit Rattle",
            weight: 3,
            basePower: 10,
            targeting: "all",
            tags: ["suppression"],
          },
        ],
        tags: ["suppression", "entangle", "ranged"],
        dropTableId: "drop-table/ledger-wraiths-regular",
      },
      {
        enemyTemplateId: "enemy/audit-shade",
        familyId: "enemy-family/ledger-wraiths",
        name: "Audit Shade",
        description:
          "A figure composed of stacked ledger books and binder clips, wearing a filing cabinet as a torso. Moves with the deliberate pace of someone who knows you owe them money. The stamps it applies leave bruises shaped like 'PAST DUE' and the ink doesn't wash off.",
        attack: 20,
        defense: 16,
        hp: 54,
        speed: 12,
        threat: 50,
        actions: [
          {
            id: "action/audit-shade/stamp-strike",
            name: "Stamp Strike",
            weight: 4,
            basePower: 22,
            targeting: "single",
            tags: ["suppression"],
          },
          {
            id: "action/audit-shade/ledger-barrage",
            name: "Ledger Barrage",
            weight: 3,
            basePower: 14,
            targeting: "all",
            tags: ["ranged"],
          },
          {
            id: "action/audit-shade/compliance-hold",
            name: "Compliance Hold",
            weight: 3,
            basePower: 16,
            targeting: "weakest",
            tags: ["entangle"],
          },
        ],
        tags: ["suppression", "entangle", "ranged"],
        dropTableId: "drop-table/ledger-wraiths-regular",
      },
    ],
  },

  {
    familyId: "enemy-family/loop-echoes",
    name: "Loop Echoes",
    description:
      "Temporal echoes from the freight elevator that loops through decades instead of floors. Workers from different eras overlap in the shaft — longshoremen from the 1940s, container handlers from the 1980s, gig workers from last year — all faded but solid enough to swing a hook or throw a punch. They don't know they're dead and they don't know what year it is.",
    siteConceptIds: ["site/loop-line-freight-elevator"],
    members: [
      {
        enemyTemplateId: "enemy/decade-echo",
        familyId: "enemy-family/loop-echoes",
        name: "Decade Echo",
        description:
          "A translucent dockworker from an indeterminate decade, wearing clothes from multiple eras at once. Flickers between time frames mid-stride — one moment in suspenders and a flat cap, the next in a hi-vis vest and hard hat. Swings tools from whichever era has the heaviest option.",
        attack: 16,
        defense: 12,
        hp: 42,
        speed: 16,
        threat: 40,
        actions: [
          {
            id: "action/decade-echo/temporal-hook",
            name: "Temporal Hook",
            weight: 5,
            basePower: 18,
            targeting: "single",
            tags: ["ambush"],
          },
          {
            id: "action/decade-echo/era-shift",
            name: "Era Shift",
            weight: 5,
            basePower: 12,
            targeting: "single",
            tags: ["hit-and-run"],
          },
        ],
        tags: ["ambush", "hit-and-run", "hazard-synergy"],
        dropTableId: "drop-table/loop-echoes-regular",
      },
      {
        enemyTemplateId: "enemy/shift-ghost",
        familyId: "enemy-family/loop-echoes",
        name: "Shift Ghost",
        description:
          "The echo of a shift change — a crowd of overlapping workers all punching the same time clock at once. Appears as a dense blur of hard hats and lunch pails that surges through corridors. Individual faces are visible for fractions of a second before being replaced by others.",
        attack: 14,
        defense: 10,
        hp: 38,
        speed: 18,
        threat: 36,
        actions: [
          {
            id: "action/shift-ghost/rush-hour-surge",
            name: "Rush Hour Surge",
            weight: 4,
            basePower: 14,
            targeting: "all",
            tags: ["hazard-synergy"],
          },
          {
            id: "action/shift-ghost/clock-punch",
            name: "Clock Punch",
            weight: 3,
            basePower: 16,
            targeting: "single",
            tags: ["ambush"],
          },
          {
            id: "action/shift-ghost/whistle-blast",
            name: "Whistle Blast",
            weight: 3,
            basePower: 10,
            targeting: "all",
            tags: ["hit-and-run"],
          },
        ],
        tags: ["ambush", "hit-and-run", "hazard-synergy"],
        dropTableId: "drop-table/loop-echoes-regular",
      },
      {
        enemyTemplateId: "enemy/timelock-sentry",
        familyId: "enemy-family/loop-echoes",
        name: "Timelock Sentry",
        description:
          "A security guard from every era the elevator has visited, compressed into one figure. Carries a nightstick, a walkie-talkie, and a lantern simultaneously. The uniform changes every time you blink. Patrols the elevator shaft with the certainty of someone who has been doing this job forever — because it has.",
        attack: 20,
        defense: 16,
        hp: 54,
        speed: 14,
        threat: 50,
        actions: [
          {
            id: "action/timelock-sentry/nightstick-loop",
            name: "Nightstick Loop",
            weight: 4,
            basePower: 22,
            targeting: "single",
            tags: ["ambush"],
          },
          {
            id: "action/timelock-sentry/temporal-lockdown",
            name: "Temporal Lockdown",
            weight: 3,
            basePower: 14,
            targeting: "all",
            tags: ["hazard-synergy"],
          },
          {
            id: "action/timelock-sentry/era-blink",
            name: "Era Blink",
            weight: 3,
            basePower: 16,
            targeting: "weakest",
            tags: ["hit-and-run"],
          },
        ],
        tags: ["ambush", "hit-and-run", "hazard-synergy"],
        dropTableId: "drop-table/loop-echoes-regular",
      },
    ],
  },

  {
    familyId: "enemy-family/pressure-hulks",
    name: "Pressure Hulks",
    description:
      "Steel organisms formed from compressed ballast water and hull metal in the pressurized ballast tank. Living pressure differentials shaped like dock equipment — cranes, winches, and valve assemblies that move with hydraulic force and bleed seawater from every joint. The tank pressure keeps climbing and so do they.",
    siteConceptIds: ["site/pressurized-ballast-tank"],
    members: [
      {
        enemyTemplateId: "enemy/ballast-drone",
        familyId: "enemy-family/pressure-hulks",
        name: "Ballast Drone",
        description:
          "A spherical mass of compressed hull plating and salt water, held together by pressure alone. Floats at chest height and rams targets with the momentum of a wrecking ball made of seawater. When punctured it doesn't deflate — the water inside is under enough pressure to cut steel.",
        attack: 16,
        defense: 14,
        hp: 44,
        speed: 14,
        threat: 40,
        actions: [
          {
            id: "action/ballast-drone/pressure-ram",
            name: "Pressure Ram",
            weight: 5,
            basePower: 18,
            targeting: "single",
            tags: ["heavy"],
          },
          {
            id: "action/ballast-drone/jet-spray",
            name: "Jet Spray",
            weight: 5,
            basePower: 14,
            targeting: "all",
            tags: ["corrosive"],
          },
        ],
        tags: ["heavy", "armor-break", "corrosive"],
        dropTableId: "drop-table/pressure-hulks-regular",
      },
      {
        enemyTemplateId: "enemy/hull-press",
        familyId: "enemy-family/pressure-hulks",
        name: "Hull Press",
        description:
          "A hydraulic press assembled from ballast tank infrastructure — valve handles for arms, pipe sections for a spine, and a pressing plate for a face. Moves by extending and retracting hydraulic cylinders. The compression force it applies to operators exceeds anything the original equipment was rated for.",
        attack: 20,
        defense: 16,
        hp: 55,
        speed: 12,
        threat: 48,
        actions: [
          {
            id: "action/hull-press/hydraulic-crush",
            name: "Hydraulic Crush",
            weight: 4,
            basePower: 22,
            targeting: "single",
            tags: ["heavy", "armor-break"],
          },
          {
            id: "action/hull-press/pipe-sweep",
            name: "Pipe Sweep",
            weight: 3,
            basePower: 14,
            targeting: "all",
            tags: ["heavy"],
          },
          {
            id: "action/hull-press/brine-bleed",
            name: "Brine Bleed",
            weight: 3,
            basePower: 12,
            targeting: "weakest",
            tags: ["corrosive"],
          },
        ],
        tags: ["heavy", "armor-break", "corrosive"],
        dropTableId: "drop-table/pressure-hulks-regular",
      },
      {
        enemyTemplateId: "enemy/valve-brute",
        familyId: "enemy-family/pressure-hulks",
        name: "Valve Brute",
        description:
          "A massive gate valve that tore itself out of the ballast system and learned to walk on pipe-leg stilts. The valve wheel on its chest spins open before every attack, releasing pressurized seawater that corrodes everything it touches. Closing the valve would require strength that doesn't exist in human arms.",
        attack: 18,
        defense: 14,
        hp: 50,
        speed: 14,
        threat: 46,
        actions: [
          {
            id: "action/valve-brute/valve-release",
            name: "Valve Release",
            weight: 4,
            basePower: 20,
            targeting: "all",
            tags: ["corrosive"],
          },
          {
            id: "action/valve-brute/pipe-stilt-kick",
            name: "Pipe Stilt Kick",
            weight: 3,
            basePower: 18,
            targeting: "single",
            tags: ["armor-break"],
          },
          {
            id: "action/valve-brute/pressure-vent",
            name: "Pressure Vent",
            weight: 3,
            basePower: 14,
            targeting: "weakest",
            tags: ["heavy"],
          },
        ],
        tags: ["heavy", "armor-break", "corrosive"],
        dropTableId: "drop-table/pressure-hulks-regular",
      },
    ],
  },

  {
    familyId: "enemy-family/signal-phantoms",
    name: "Signal Phantoms",
    description:
      "Light-based entities refracted through the condemned signal tower's rotating geometry. The tower's lens array still turns but the light it refracts comes from somewhere else — afterimages that solidify into striking distance, fog signals that hit like freight, and beam patterns that leave burns shaped like navigational charts. The harbor hasn't used this tower in forty years but something is still signaling.",
    siteConceptIds: ["site/condemned-signal-tower"],
    members: [
      {
        enemyTemplateId: "enemy/beam-flicker",
        familyId: "enemy-family/signal-phantoms",
        name: "Beam Flicker",
        description:
          "An afterimage left by the rotating signal beam, burned into the air and given weight. Appears as a strobing silhouette that darts between surfaces at the speed of a lighthouse sweep. The light it's made of is cold and leaves retinal burns that show navigational coordinates.",
        attack: 16,
        defense: 10,
        hp: 36,
        speed: 18,
        threat: 36,
        actions: [
          {
            id: "action/beam-flicker/strobe-dash",
            name: "Strobe Dash",
            weight: 5,
            basePower: 16,
            targeting: "single",
            tags: ["ambush"],
          },
          {
            id: "action/beam-flicker/afterimage-cut",
            name: "Afterimage Cut",
            weight: 5,
            basePower: 14,
            targeting: "single",
            tags: ["ranged"],
          },
        ],
        tags: ["ranged", "ambush", "hazard-synergy"],
        dropTableId: "drop-table/signal-phantoms-regular",
      },
      {
        enemyTemplateId: "enemy/fog-signal",
        familyId: "enemy-family/signal-phantoms",
        name: "Fog Signal",
        description:
          "A dense mass of harbor fog compressed into a vaguely humanoid shape by the tower's rotating lens. Emits a low-frequency blast that operators feel in their teeth before they hear it. The fog is luminous and warm and the blast carries the physical force of a foghorn that learned to aim.",
        attack: 18,
        defense: 14,
        hp: 48,
        speed: 14,
        threat: 44,
        actions: [
          {
            id: "action/fog-signal/concussion-blast",
            name: "Concussion Blast",
            weight: 4,
            basePower: 20,
            targeting: "all",
            tags: ["ranged"],
          },
          {
            id: "action/fog-signal/fog-smother",
            name: "Fog Smother",
            weight: 3,
            basePower: 14,
            targeting: "single",
            tags: ["hazard-synergy"],
          },
          {
            id: "action/fog-signal/low-frequency-pulse",
            name: "Low Frequency Pulse",
            weight: 3,
            basePower: 12,
            targeting: "all",
            tags: ["ambush"],
          },
        ],
        tags: ["ranged", "ambush", "hazard-synergy"],
        dropTableId: "drop-table/signal-phantoms-regular",
      },
      {
        enemyTemplateId: "enemy/lighthouse-revenant",
        familyId: "enemy-family/signal-phantoms",
        name: "Lighthouse Revenant",
        description:
          "The signal tower's rotating lens assembly, detached and ambulatory. A massive Fresnel lens on articulated brass legs, focusing impossible light into a beam that sweeps the interior like a searchlight with intent. Whatever it illuminates, it damages. The lens is cracked and the light that leaks through the fractures is worse than the beam.",
        attack: 20,
        defense: 16,
        hp: 54,
        speed: 12,
        threat: 50,
        actions: [
          {
            id: "action/lighthouse-revenant/focused-beam",
            name: "Focused Beam",
            weight: 4,
            basePower: 22,
            targeting: "single",
            tags: ["ranged"],
          },
          {
            id: "action/lighthouse-revenant/sweep-burn",
            name: "Sweep Burn",
            weight: 3,
            basePower: 16,
            targeting: "all",
            tags: ["hazard-synergy"],
          },
          {
            id: "action/lighthouse-revenant/fractured-light",
            name: "Fractured Light",
            weight: 3,
            basePower: 14,
            targeting: "weakest",
            tags: ["ambush"],
          },
        ],
        tags: ["ranged", "ambush", "hazard-synergy"],
        dropTableId: "drop-table/signal-phantoms-regular",
      },
    ],
  },
];

export const enemyFamilyById: ReadonlyMap<string, EnemyFamilyTemplate> = new Map(
  enemyFamilyTemplates.map((f) => [f.familyId, f]),
);
