import type { EventTemplate } from "./shared";

export const eventTemplates = [
  {
    id: "event/breach_emergency",
    kind: "event",
    name: "Breach Emergency",
    tags: ["event:response", "pressure:time"],
    description: "A sudden loss of control that demands immediate staffing and attention.",
    category: "breach_emergency",
    pressureTags: ["pressure:reputation", "pressure:casualty"],
    weight: 1,
  },
  {
    id: "event/personnel_conflict",
    kind: "event",
    name: "Personnel Conflict",
    tags: ["event:staff", "pressure:morale"],
    description: "Interpersonal strain disrupts the guild's operational rhythm.",
    category: "personnel_conflict",
    pressureTags: ["pressure:morale", "pressure:loyalty"],
    weight: 1,
  },
  {
    id: "event/contract_deadline",
    kind: "event",
    name: "Contract Deadline",
    tags: ["event:operations", "pressure:time"],
    description: "A deadline tightens and forces clearer mission prioritization.",
    category: "contract_deadline",
    pressureTags: ["pressure:time", "pressure:cash"],
    weight: 1,
  },
  {
    id: "event/economic_pressure",
    kind: "event",
    name: "Economic Pressure",
    tags: ["event:economy", "pressure:cash"],
    description: "Operational costs rise faster than the guild's buffer can absorb.",
    category: "economic_pressure",
    pressureTags: ["pressure:cash", "pressure:time"],
    weight: 1,
  },
  {
    id: "event/regulatory_scrutiny",
    kind: "event",
    name: "Regulatory Scrutiny",
    tags: ["event:external", "pressure:reputation"],
    description: "Visibility invites auditors, officials, or rivals to look closer.",
    category: "regulatory_scrutiny",
    pressureTags: ["pressure:reputation", "pressure:morale"],
    weight: 1,
  },
  {
    id: "event/team_friction",
    kind: "event",
    name: "Team Friction",
    tags: ["event:staff", "pressure:morale", "pressure:loyalty"],
    description: "Social strain within a recurring team threatens cohesion.",
    category: "team_friction",
    pressureTags: ["pressure:morale", "pressure:loyalty"],
    weight: 1,
  },
  {
    id: "event/injury_setback",
    kind: "event",
    name: "Injury Setback",
    tags: ["event:response", "pressure:casualty", "pressure:time"],
    description: "An operator's recovery takes a turn for the worse.",
    category: "injury_setback",
    pressureTags: ["pressure:casualty", "pressure:time"],
    weight: 1,
  },
  {
    id: "event/departure_warning",
    kind: "event",
    name: "Departure Warning",
    tags: ["event:staff", "pressure:loyalty", "pressure:morale"],
    description: "An operator is threatening to leave the guild.",
    category: "departure_warning",
    pressureTags: ["pressure:loyalty", "pressure:morale"],
    weight: 1,
  },
  {
    id: "event/room_tension",
    kind: "event",
    name: "Room Tension",
    tags: ["event:staff", "pressure:morale"],
    description: "The culture in a shared room is deteriorating.",
    category: "room_tension",
    pressureTags: ["pressure:morale"],
    weight: 1,
  },
  {
    id: "event/supply_shortage",
    kind: "event",
    name: "Supply Shortage",
    tags: ["event:economy", "pressure:cash"],
    description: "A gear or resource shortage strains operational readiness.",
    category: "supply_shortage",
    pressureTags: ["pressure:cash"],
    weight: 1,
  },
  {
    id: "event/rival_poaching",
    kind: "event",
    name: "Rival Poaching",
    tags: ["event:external", "pressure:loyalty", "pressure:reputation"],
    description: "A rival guild is trying to recruit your best operators.",
    category: "rival_poaching",
    pressureTags: ["pressure:loyalty", "pressure:reputation"],
    weight: 1,
  },
  {
    id: "event/morale_surge",
    kind: "event",
    name: "Morale Surge",
    tags: ["event:staff", "pressure:morale"],
    description: "A wave of positive morale follows a recent success.",
    category: "morale_surge",
    pressureTags: ["pressure:morale"],
    weight: 1,
  },
  {
    id: "event/contract_opportunity",
    kind: "event",
    name: "Contract Opportunity",
    tags: ["event:operations", "pressure:reputation"],
    description: "A new contract offer arrives, bringing both reward and scrutiny.",
    category: "contract_opportunity",
    pressureTags: ["pressure:reputation"],
    weight: 1,
  },
] satisfies readonly EventTemplate[];
