import type { EventTemplate } from "./shared";

export const eventTemplates = [
  {
    id: "event/breach_emergency",
    kind: "event",
    name: "Breach Emergency",
    tags: ["event:response", "pressure:urgent"],
    description: "A sudden loss of control that demands immediate staffing and attention.",
    category: "breach_emergency",
    pressureTags: ["pressure:reputation", "pressure:casualty"],
    weight: 1,
  },
  {
    id: "event/personnel_conflict",
    kind: "event",
    name: "Personnel Conflict",
    tags: ["event:staff", "pressure:internal"],
    description: "Interpersonal strain disrupts the guild's operational rhythm.",
    category: "personnel_conflict",
    pressureTags: ["pressure:morale", "pressure:loyalty"],
    weight: 1,
  },
  {
    id: "event/contract_deadline",
    kind: "event",
    name: "Contract Deadline",
    tags: ["event:operations", "pressure:time"],
    description: "A deadline tightens and forces clearer mission prioritization.",
    category: "contract_deadline",
    pressureTags: ["pressure:time", "pressure:cash"],
    weight: 1,
  },
  {
    id: "event/economic_pressure",
    kind: "event",
    name: "Economic Pressure",
    tags: ["event:economy", "pressure:cash"],
    description: "Operational costs rise faster than the guild's buffer can absorb.",
    category: "economic_pressure",
    pressureTags: ["pressure:cash", "pressure:payroll"],
    weight: 1,
  },
  {
    id: "event/regulatory_scrutiny",
    kind: "event",
    name: "Regulatory Scrutiny",
    tags: ["event:external", "pressure:reputation"],
    description: "Visibility invites auditors, officials, or rivals to look closer.",
    category: "regulatory_scrutiny",
    pressureTags: ["pressure:reputation", "pressure:public"],
    weight: 1,
  },
] satisfies readonly EventTemplate[];
