import type { DropTable, ItemTemplate, PrepRecipeTemplate } from "./shared";

export const itemTemplates = [
  // --- Weapons ---
  {
    id: "weapon/pipe-wrench",
    kind: "item",
    name: "Pipe Wrench",
    tags: ["rank:f"],
    description: "A heavy wrench repurposed for close combat.",
    category: "weapon",
    rank: "f",
    buyPrice: 30,
    sellPrice: 12,
    statEffects: [{ stat: "strength", value: 3 }],
  },
  {
    id: "weapon/kitchen-knife",
    kind: "item",
    name: "Kitchen Knife",
    tags: ["rank:f"],
    description: "A sharp blade from the bodega kitchen drawer.",
    category: "weapon",
    rank: "f",
    buyPrice: 25,
    sellPrice: 10,
    statEffects: [
      { stat: "speed", value: 2 },
      { stat: "strength", value: 1 },
    ],
  },
  {
    id: "weapon/baseball-bat",
    kind: "item",
    name: "Baseball Bat",
    tags: ["rank:f"],
    description: "Reliable blunt force in a familiar shape.",
    category: "weapon",
    rank: "f",
    buyPrice: 35,
    sellPrice: 14,
    statEffects: [{ stat: "strength", value: 4 }],
  },
  {
    id: "weapon/tactical-knife",
    kind: "item",
    name: "Tactical Knife",
    tags: ["rank:e"],
    description: "A purpose-built combat knife with a reinforced grip.",
    category: "weapon",
    rank: "e",
    buyPrice: 60,
    sellPrice: 25,
    statEffects: [
      { stat: "speed", value: 3 },
      { stat: "strength", value: 2 },
    ],
  },
  {
    id: "weapon/machete",
    kind: "item",
    name: "Machete",
    tags: ["rank:e"],
    description: "A long, heavy blade suited for clearing paths and threats.",
    category: "weapon",
    rank: "e",
    buyPrice: 75,
    sellPrice: 30,
    statEffects: [{ stat: "strength", value: 5 }],
  },
  {
    id: "weapon/compact-crossbow",
    kind: "item",
    name: "Compact Crossbow",
    tags: ["rank:e"],
    description: "A small crossbow offering ranged precision at short distances.",
    category: "weapon",
    rank: "e",
    buyPrice: 85,
    sellPrice: 35,
    statEffects: [
      { stat: "speed", value: 2 },
      { stat: "perception", value: 2 },
      { stat: "strength", value: 2 },
    ],
  },
  {
    id: "weapon/reinforced-bat",
    kind: "item",
    name: "Reinforced Bat",
    tags: ["rank:d"],
    description: "A steel-core bat wrapped in shock-absorbing tape.",
    category: "weapon",
    rank: "d",
    buyPrice: 120,
    sellPrice: 50,
    statEffects: [
      { stat: "strength", value: 6 },
      { stat: "resilience", value: 2 },
    ],
  },
  {
    id: "weapon/katana",
    kind: "item",
    name: "Katana",
    tags: ["rank:d"],
    description: "A balanced blade that rewards skilled hands.",
    category: "weapon",
    rank: "d",
    buyPrice: 150,
    sellPrice: 60,
    statEffects: [
      { stat: "speed", value: 4 },
      { stat: "strength", value: 5 },
    ],
  },
  {
    id: "weapon/tactical-rifle",
    kind: "item",
    name: "Tactical Rifle",
    tags: ["rank:d"],
    description: "A modular rifle platform built for field operations.",
    category: "weapon",
    rank: "d",
    buyPrice: 180,
    sellPrice: 75,
    statEffects: [
      { stat: "strength", value: 4 },
      { stat: "speed", value: 3 },
      { stat: "perception", value: 3 },
    ],
  },
  {
    id: "weapon/dual-daggers",
    kind: "item",
    name: "Dual Daggers",
    tags: ["rank:d"],
    description: "A matched pair of lightweight combat daggers.",
    category: "weapon",
    rank: "d",
    buyPrice: 140,
    sellPrice: 55,
    statEffects: [
      { stat: "speed", value: 6 },
      { stat: "strength", value: 3 },
    ],
  },

  {
    id: "weapon/crowbar",
    kind: "item",
    name: "Crowbar",
    tags: ["rank:f"],
    description: "A pry bar heavy enough to discourage anything with joints.",
    category: "weapon",
    rank: "f",
    buyPrice: 30,
    sellPrice: 12,
    statEffects: [
      { stat: "strength", value: 2 },
      { stat: "resilience", value: 1 },
    ],
  },
  {
    id: "weapon/box-cutter",
    kind: "item",
    name: "Box Cutter",
    tags: ["rank:f"],
    description: "A retractable utility blade. Fast, disposable, unpleasant.",
    category: "weapon",
    rank: "f",
    buyPrice: 20,
    sellPrice: 8,
    statEffects: [{ stat: "speed", value: 3 }],
  },
  {
    id: "weapon/hand-axe",
    kind: "item",
    name: "Hand Axe",
    tags: ["rank:e"],
    description: "A compact hatchet built for clearing obstacles and threats alike.",
    category: "weapon",
    rank: "e",
    buyPrice: 70,
    sellPrice: 28,
    statEffects: [
      { stat: "strength", value: 4 },
      { stat: "speed", value: 1 },
    ],
  },
  {
    id: "weapon/sidearm",
    kind: "item",
    name: "Sidearm",
    tags: ["rank:d"],
    description: "A reliable semi-automatic pistol for operators who prefer range over reach.",
    category: "weapon",
    rank: "d",
    buyPrice: 160,
    sellPrice: 65,
    statEffects: [
      { stat: "speed", value: 4 },
      { stat: "perception", value: 3 },
      { stat: "strength", value: 2 },
    ],
  },

  // --- Outfit Overlays ---
  {
    id: "outfit-overlay/padded-jacket",
    kind: "item",
    name: "Padded Jacket",
    tags: ["rank:f"],
    description: "A thick jacket offering basic protection against impacts.",
    category: "outfit-overlay",
    rank: "f",
    buyPrice: 40,
    sellPrice: 16,
    statEffects: [
      { stat: "resilience", value: 2 },
      { stat: "endurance", value: 1 },
    ],
  },
  {
    id: "outfit-overlay/leather-vest",
    kind: "item",
    name: "Leather Vest",
    tags: ["rank:f"],
    description: "A rugged leather vest that absorbs light blows.",
    category: "outfit-overlay",
    rank: "f",
    buyPrice: 35,
    sellPrice: 14,
    statEffects: [{ stat: "resilience", value: 3 }],
  },
  {
    id: "outfit-overlay/tactical-vest",
    kind: "item",
    name: "Tactical Vest",
    tags: ["rank:e"],
    description: "A purpose-built vest with plating and utility pockets.",
    category: "outfit-overlay",
    rank: "e",
    buyPrice: 80,
    sellPrice: 32,
    statEffects: [
      { stat: "resilience", value: 4 },
      { stat: "endurance", value: 2 },
    ],
  },
  {
    id: "outfit-overlay/stealth-cloak",
    kind: "item",
    name: "Stealth Cloak",
    tags: ["rank:e"],
    description: "A lightweight cloak that dampens sound and movement.",
    category: "outfit-overlay",
    rank: "e",
    buyPrice: 90,
    sellPrice: 36,
    statEffects: [
      { stat: "speed", value: 3 },
      { stat: "resilience", value: 2 },
    ],
  },
  {
    id: "outfit-overlay/heavy-plate",
    kind: "item",
    name: "Heavy Plate",
    tags: ["rank:d"],
    description: "A layered armor plate that trades mobility for serious protection.",
    category: "outfit-overlay",
    rank: "d",
    buyPrice: 160,
    sellPrice: 65,
    statEffects: [
      { stat: "resilience", value: 7 },
      { stat: "endurance", value: 3 },
    ],
  },
  {
    id: "outfit-overlay/field-medic-coat",
    kind: "item",
    name: "Field Medic Coat",
    tags: ["rank:d"],
    description: "A reinforced medical coat with integrated supply pouches.",
    category: "outfit-overlay",
    rank: "d",
    buyPrice: 140,
    sellPrice: 55,
    statEffects: [
      { stat: "resilience", value: 4 },
      { stat: "endurance", value: 4 },
      { stat: "perception", value: 2 },
    ],
  },

  {
    id: "outfit-overlay/work-coveralls",
    kind: "item",
    name: "Work Coveralls",
    tags: ["rank:f"],
    description:
      "Tough full-body coveralls meant for industrial sites. Not fashionable. Functional.",
    category: "outfit-overlay",
    rank: "f",
    buyPrice: 30,
    sellPrice: 12,
    statEffects: [
      { stat: "endurance", value: 2 },
      { stat: "resilience", value: 1 },
    ],
  },
  {
    id: "outfit-overlay/reinforced-hoodie",
    kind: "item",
    name: "Reinforced Hoodie",
    tags: ["rank:e"],
    description:
      "A lined hoodie with concealed plating. Moves like street clothes, stops like armor.",
    category: "outfit-overlay",
    rank: "e",
    buyPrice: 75,
    sellPrice: 30,
    statEffects: [
      { stat: "resilience", value: 3 },
      { stat: "speed", value: 2 },
    ],
  },
  {
    id: "outfit-overlay/ballistic-vest",
    kind: "item",
    name: "Ballistic Vest",
    tags: ["rank:d"],
    description: "A rated protective vest with ceramic inserts. Heavy but confidence-inspiring.",
    category: "outfit-overlay",
    rank: "d",
    buyPrice: 150,
    sellPrice: 60,
    statEffects: [
      { stat: "resilience", value: 6 },
      { stat: "endurance", value: 2 },
      { stat: "speed", value: 1 },
    ],
  },

  // --- Accessories ---
  {
    id: "accessory/comm-earpiece",
    kind: "item",
    name: "Comm Earpiece",
    tags: ["rank:f"],
    description: "A discreet earpiece for field communication.",
    category: "accessory",
    rank: "f",
    buyPrice: 20,
    sellPrice: 8,
    statEffects: [{ stat: "perception", value: 2 }],
  },
  {
    id: "accessory/tactical-scarf",
    kind: "item",
    name: "Tactical Scarf",
    tags: ["rank:f"],
    description: "A multi-purpose scarf that shields against dust and debris.",
    category: "accessory",
    rank: "f",
    buyPrice: 15,
    sellPrice: 6,
    statEffects: [
      { stat: "resilience", value: 1 },
      { stat: "speed", value: 1 },
    ],
  },
  {
    id: "accessory/eye-visor",
    kind: "item",
    name: "Eye Visor",
    tags: ["rank:e"],
    description: "An optical visor that enhances threat detection.",
    category: "accessory",
    rank: "e",
    buyPrice: 55,
    sellPrice: 22,
    statEffects: [{ stat: "perception", value: 4 }],
  },
  {
    id: "accessory/medkit-pouch",
    kind: "item",
    name: "Medkit Pouch",
    tags: ["rank:e"],
    description: "A compact medical pouch worn on the belt.",
    category: "accessory",
    rank: "e",
    buyPrice: 65,
    sellPrice: 26,
    statEffects: [
      { stat: "resilience", value: 2 },
      { stat: "endurance", value: 2 },
    ],
  },
  {
    id: "accessory/scout-binocs",
    kind: "item",
    name: "Scout Binocs",
    tags: ["rank:e"],
    description: "Lightweight binoculars for long-range reconnaissance.",
    category: "accessory",
    rank: "e",
    buyPrice: 50,
    sellPrice: 20,
    statEffects: [{ stat: "perception", value: 5 }],
  },
  {
    id: "accessory/field-lead-badge",
    kind: "item",
    name: "Field Lead Badge",
    tags: ["rank:e"],
    description: "An authority badge that bolsters composure under pressure.",
    category: "accessory",
    rank: "e",
    buyPrice: 45,
    sellPrice: 18,
    statEffects: [
      { stat: "resilience", value: 3 },
      { stat: "endurance", value: 1 },
    ],
  },
  {
    id: "accessory/reinforced-gloves",
    kind: "item",
    name: "Reinforced Gloves",
    tags: ["rank:d"],
    description: "Hardened gloves that protect hands and improve grip strength.",
    category: "accessory",
    rank: "d",
    buyPrice: 100,
    sellPrice: 40,
    statEffects: [
      { stat: "strength", value: 3 },
      { stat: "resilience", value: 3 },
    ],
  },

  {
    id: "accessory/wrist-brace",
    kind: "item",
    name: "Wrist Brace",
    tags: ["rank:f"],
    description: "A rigid wrist support that keeps hands steady under impact.",
    category: "accessory",
    rank: "f",
    buyPrice: 18,
    sellPrice: 7,
    statEffects: [{ stat: "endurance", value: 2 }],
  },
  {
    id: "accessory/shoulder-lamp",
    kind: "item",
    name: "Shoulder Lamp",
    tags: ["rank:e"],
    description: "A clip-on tactical light that keeps both hands free in dark sites.",
    category: "accessory",
    rank: "e",
    buyPrice: 50,
    sellPrice: 20,
    statEffects: [
      { stat: "perception", value: 3 },
      { stat: "speed", value: 1 },
    ],
  },
  {
    id: "accessory/utility-belt",
    kind: "item",
    name: "Utility Belt",
    tags: ["rank:d"],
    description: "A modular tool belt with quick-access pouches for field supplies.",
    category: "accessory",
    rank: "d",
    buyPrice: 105,
    sellPrice: 42,
    statEffects: [
      { stat: "endurance", value: 2 },
      { stat: "perception", value: 2 },
      { stat: "speed", value: 2 },
    ],
  },
  {
    id: "accessory/trauma-kit",
    kind: "item",
    name: "Trauma Kit",
    tags: ["rank:d"],
    description:
      "A field-grade trauma response kit worn on the hip. Standard issue for medic-adjacent operators.",
    category: "accessory",
    rank: "d",
    buyPrice: 95,
    sellPrice: 38,
    statEffects: [
      { stat: "endurance", value: 3 },
      { stat: "resilience", value: 2 },
      { stat: "perception", value: 1 },
    ],
  },

  // --- Monster Part Loot ---
  {
    id: "loot/monster-part/fang",
    kind: "item",
    name: "Fang",
    tags: ["loot:monster_part", "loot:crafting_input"],
    description: "A sharp tooth ripped from a hostile creature.",
    category: "loot",
    rank: "f",
    buyPrice: 0,
    sellPrice: 8,
    statEffects: [],
  },
  {
    id: "loot/monster-part/carapace",
    kind: "item",
    name: "Carapace",
    tags: ["loot:monster_part", "loot:crafting_input"],
    description: "A thick shell fragment that once shielded a threat.",
    category: "loot",
    rank: "f",
    buyPrice: 0,
    sellPrice: 12,
    statEffects: [],
  },
  {
    id: "loot/monster-part/ichor",
    kind: "item",
    name: "Ichor",
    tags: ["loot:monster_part", "loot:crafting_input"],
    description: "A viscous fluid harvested from a defeated anomaly.",
    category: "loot",
    rank: "f",
    buyPrice: 0,
    sellPrice: 6,
    statEffects: [],
  },
  {
    id: "loot/monster-part/bone-shard",
    kind: "item",
    name: "Bone Shard",
    tags: ["loot:monster_part", "loot:crafting_input"],
    description: "A jagged bone fragment from a large creature.",
    category: "loot",
    rank: "f",
    buyPrice: 0,
    sellPrice: 10,
    statEffects: [],
  },
  {
    id: "loot/monster-part/sinew",
    kind: "item",
    name: "Sinew",
    tags: ["loot:monster_part", "loot:crafting_input"],
    description: "Tough connective tissue with residual tension.",
    category: "loot",
    rank: "f",
    buyPrice: 0,
    sellPrice: 7,
    statEffects: [],
  },
  {
    id: "loot/monster-part/crystal-eye",
    kind: "item",
    name: "Crystal Eye",
    tags: ["loot:monster_part", "loot:crafting_input", "rank:e"],
    description: "A crystallized eye that refracts ambient light.",
    category: "loot",
    rank: "e",
    buyPrice: 0,
    sellPrice: 18,
    statEffects: [],
  },
  {
    id: "loot/monster-part/void-residue",
    kind: "item",
    name: "Void Residue",
    tags: ["loot:monster_part", "loot:crafting_input", "rank:d"],
    description: "A dark, shimmering substance from a powerful entity.",
    category: "loot",
    rank: "d",
    buyPrice: 0,
    sellPrice: 25,
    statEffects: [],
  },
  {
    id: "loot/monster-part/threat-gland",
    kind: "item",
    name: "Threat Gland",
    tags: ["loot:monster_part", "loot:crafting_input", "rank:e"],
    description: "A glandular organ that once powered a creature's aggression.",
    category: "loot",
    rank: "e",
    buyPrice: 0,
    sellPrice: 15,
    statEffects: [],
  },

  // ── Themed family loot: tunnel-crawlers ───────────────────────────────
  {
    id: "loot/monster-part/drain-sludge",
    kind: "item",
    name: "Drain Sludge",
    tags: ["loot:monster_part", "loot:sell_only", "loot:auto_sell_junk", "loot:dungeon_drop"],
    description: "Viscous residue scraped from tunnel-crawler carapaces. Warm to the touch.",
    category: "loot",
    rank: "f",
    buyPrice: 0,
    sellPrice: 7,
    statEffects: [],
  },
  {
    id: "loot/monster-part/pipe-scale",
    kind: "item",
    name: "Pipe Scale",
    tags: ["loot:monster_part", "loot:crafting_input", "loot:dungeon_drop"],
    description: "Mineral-encrusted plating shed inside flooded pipes. Rings when struck.",
    category: "loot",
    rank: "f",
    buyPrice: 0,
    sellPrice: 11,
    statEffects: [],
  },

  // ── Themed family loot: concrete-sentinels ────────────────────────────
  {
    id: "loot/monster-part/ramp-gravel",
    kind: "item",
    name: "Ramp Gravel",
    tags: ["loot:monster_part", "loot:sell_only", "loot:auto_sell_junk", "loot:dungeon_drop"],
    description: "Animate concrete fragments from parking structure entities. Still vibrates.",
    category: "loot",
    rank: "f",
    buyPrice: 0,
    sellPrice: 8,
    statEffects: [],
  },
  {
    id: "loot/monster-part/bollard-core",
    kind: "item",
    name: "Bollard Core",
    tags: ["loot:monster_part", "loot:crafting_input", "loot:dungeon_drop"],
    description: "Dense core material from structural sentinel entities. Heavier than it looks.",
    category: "loot",
    rank: "f",
    buyPrice: 0,
    sellPrice: 11,
    statEffects: [],
  },

  // ── Themed family loot: chalk-swarms ──────────────────────────────────
  {
    id: "loot/monster-part/chalk-filament",
    kind: "item",
    name: "Chalk Filament",
    tags: ["loot:monster_part", "loot:sell_only", "loot:auto_sell_junk", "loot:dungeon_drop"],
    description: "Fibrous chalk threads from swarm creatures. Crumbles if you grip too hard.",
    category: "loot",
    rank: "f",
    buyPrice: 0,
    sellPrice: 7,
    statEffects: [],
  },
  {
    id: "loot/monster-part/lesson-fragment",
    kind: "item",
    name: "Lesson Fragment",
    tags: ["loot:monster_part", "loot:crafting_input", "loot:dungeon_drop"],
    description: "Crystallized educational residue. Words shift when you try to read them.",
    category: "loot",
    rank: "f",
    buyPrice: 0,
    sellPrice: 12,
    statEffects: [],
  },

  // ── Themed family loot: vine-constructs ───────────────────────────────
  {
    id: "loot/monster-part/root-fiber",
    kind: "item",
    name: "Root Fiber",
    tags: ["loot:monster_part", "loot:sell_only", "loot:auto_sell_junk", "loot:dungeon_drop"],
    description: "Tough fibers from animate root systems. Tries to grow if left in water.",
    category: "loot",
    rank: "f",
    buyPrice: 0,
    sellPrice: 6,
    statEffects: [],
  },
  {
    id: "loot/monster-part/pollen-sac",
    kind: "item",
    name: "Pollen Sac",
    tags: ["loot:monster_part", "loot:crafting_input", "loot:dungeon_drop"],
    description: "Intact sac from botanical constructs. Glows faintly in the dark.",
    category: "loot",
    rank: "f",
    buyPrice: 0,
    sellPrice: 12,
    statEffects: [],
  },

  // ── Themed family loot: suds-constructs ───────────────────────────────
  {
    id: "loot/monster-part/lint-clump",
    kind: "item",
    name: "Lint Clump",
    tags: ["loot:monster_part", "loot:sell_only", "loot:auto_sell_junk", "loot:dungeon_drop"],
    description: "Condensed lint matter from laundered entities. Smells like industrial detergent.",
    category: "loot",
    rank: "f",
    buyPrice: 0,
    sellPrice: 7,
    statEffects: [],
  },
  {
    id: "loot/monster-part/detergent-crystal",
    kind: "item",
    name: "Detergent Crystal",
    tags: ["loot:monster_part", "loot:crafting_input", "loot:dungeon_drop"],
    description: "Crystallized chemical compound from suds constructs. Caustic if cracked.",
    category: "loot",
    rank: "f",
    buyPrice: 0,
    sellPrice: 10,
    statEffects: [],
  },

  // ── Themed family loot: cellar-dwellers ───────────────────────────────
  {
    id: "loot/monster-part/radiator-ash",
    kind: "item",
    name: "Radiator Ash",
    tags: ["loot:monster_part", "loot:sell_only", "loot:auto_sell_junk", "loot:dungeon_drop"],
    description: "Hot ash from heat-dwelling basement creatures. Stays warm for days.",
    category: "loot",
    rank: "f",
    buyPrice: 0,
    sellPrice: 8,
    statEffects: [],
  },
  {
    id: "loot/monster-part/basement-mold",
    kind: "item",
    name: "Basement Mold",
    tags: ["loot:monster_part", "loot:crafting_input", "loot:dungeon_drop"],
    description: "Animate fungal matter from sub-level dwellers. Pulses slowly.",
    category: "loot",
    rank: "f",
    buyPrice: 0,
    sellPrice: 10,
    statEffects: [],
  },

  // ── Themed family loot: court-echoes ──────────────────────────────────
  {
    id: "loot/monster-part/echo-resin",
    kind: "item",
    name: "Echo Resin",
    tags: ["loot:monster_part", "loot:sell_only", "loot:auto_sell_junk", "loot:dungeon_drop"],
    description: "Solidified sound residue from athletic ghosts. Hums when thrown.",
    category: "loot",
    rank: "f",
    buyPrice: 0,
    sellPrice: 7,
    statEffects: [],
  },
  {
    id: "loot/monster-part/rubber-fragment",
    kind: "item",
    name: "Rubber Fragment",
    tags: ["loot:monster_part", "loot:crafting_input", "loot:dungeon_drop"],
    description: "Warped rubber shed by court echo entities. Bounces at wrong angles.",
    category: "loot",
    rank: "f",
    buyPrice: 0,
    sellPrice: 11,
    statEffects: [],
  },

  // ── Themed family loot: freezer-fauna ─────────────────────────────────
  {
    id: "loot/monster-part/frost-shard",
    kind: "item",
    name: "Frost Shard",
    tags: ["loot:monster_part", "loot:sell_only", "loot:dungeon_drop"],
    description: "Razor-sharp ice crystal from cold-adapted fauna. Does not melt.",
    category: "loot",
    rank: "f",
    buyPrice: 0,
    sellPrice: 8,
    statEffects: [],
  },
  {
    id: "loot/monster-part/preserved-marrow",
    kind: "item",
    name: "Preserved Marrow",
    tags: ["loot:monster_part", "loot:sell_only", "loot:dungeon_drop"],
    description: "Unnaturally preserved organic core from freezer fauna. Cold to the bone.",
    category: "loot",
    rank: "f",
    buyPrice: 0,
    sellPrice: 12,
    statEffects: [],
  },
  // ── Consumables (Prep Room products) ─────────────────────────────────
  {
    id: "consumable/rift-tonic",
    kind: "item",
    name: "Rift Tonic",
    tags: ["consumable:raid_aid", "buff:strength"],
    description:
      "A crude stimulant brewed from monster parts. Sharpens aggression for a few hours.",
    category: "consumable",
    rank: "f",
    buyPrice: 0,
    sellPrice: 5,
    statEffects: [],
    consumableBuff: { stat: "strength", value: 3, durationMinutes: 120 },
  },
  {
    id: "consumable/recovery-salve",
    kind: "item",
    name: "Recovery Salve",
    tags: ["consumable:raid_aid", "buff:resilience"],
    description:
      "A thick ointment that numbs pain and accelerates clotting. Apply before deployment.",
    category: "consumable",
    rank: "f",
    buyPrice: 0,
    sellPrice: 5,
    statEffects: [],
    consumableBuff: { stat: "resilience", value: 3, durationMinutes: 120 },
  },
  {
    id: "consumable/phase-ward",
    kind: "item",
    name: "Phase Ward",
    tags: ["consumable:raid_aid", "buff:speed"],
    description:
      "A treated bandage wrap that reacts to spatial distortion. Keeps the wearer grounded.",
    category: "consumable",
    rank: "f",
    buyPrice: 0,
    sellPrice: 5,
    statEffects: [],
    consumableBuff: { stat: "speed", value: 3, durationMinutes: 120 },
  },
  {
    id: "consumable/endurance-draught",
    kind: "item",
    name: "Endurance Draught",
    tags: ["consumable:raid_aid", "buff:endurance"],
    description: "A bitter drink that delays fatigue. Tastes like wet copper and works anyway.",
    category: "consumable",
    rank: "f",
    buyPrice: 0,
    sellPrice: 5,
    statEffects: [],
    consumableBuff: { stat: "endurance", value: 3, durationMinutes: 120 },
  },
] satisfies readonly ItemTemplate[];

// ── Prep Recipes ──────────────────────────────────────────────────────
export const prepRecipeTemplates: readonly PrepRecipeTemplate[] = [
  {
    id: "prep-recipe/rift-tonic",
    name: "Rift Tonic",
    description: "Combine fangs and ichor into a crude stimulant.",
    inputs: [
      { itemId: "loot/monster-part/fang", quantity: 2 },
      { itemId: "loot/monster-part/ichor", quantity: 1 },
    ],
    outputItemId: "consumable/rift-tonic",
    outputQuantity: 1,
    requiredRoomTag: "ops:staging",
  },
  {
    id: "prep-recipe/recovery-salve",
    name: "Recovery Salve",
    description: "Grind carapace fragments into a protective ointment.",
    inputs: [
      { itemId: "loot/monster-part/carapace", quantity: 2 },
      { itemId: "loot/monster-part/sinew", quantity: 1 },
    ],
    outputItemId: "consumable/recovery-salve",
    outputQuantity: 1,
    requiredRoomTag: "ops:staging",
  },
  {
    id: "prep-recipe/phase-ward",
    name: "Phase Ward",
    description: "Treat bandages with crystal-eye extract for spatial stability.",
    inputs: [
      { itemId: "loot/monster-part/crystal-eye", quantity: 1 },
      { itemId: "loot/monster-part/bone-shard", quantity: 2 },
    ],
    outputItemId: "consumable/phase-ward",
    outputQuantity: 1,
    requiredRoomTag: "ops:staging",
  },
  {
    id: "prep-recipe/endurance-draught",
    name: "Endurance Draught",
    description: "Boil sinew and ichor into a fatigue-delaying drink.",
    inputs: [
      { itemId: "loot/monster-part/sinew", quantity: 2 },
      { itemId: "loot/monster-part/ichor", quantity: 2 },
    ],
    outputItemId: "consumable/endurance-draught",
    outputQuantity: 1,
    requiredRoomTag: "ops:staging",
  },
];

export const dropTables = [
  {
    id: "drop-table/dungeon-f-regular",
    entries: [
      { itemId: "loot/monster-part/fang", weight: 30, minQuantity: 1, maxQuantity: 2 },
      { itemId: "loot/monster-part/carapace", weight: 20, minQuantity: 1, maxQuantity: 1 },
      { itemId: "loot/monster-part/ichor", weight: 25, minQuantity: 1, maxQuantity: 3 },
      { itemId: "loot/monster-part/bone-shard", weight: 15, minQuantity: 1, maxQuantity: 1 },
      { itemId: "loot/monster-part/sinew", weight: 10, minQuantity: 1, maxQuantity: 2 },
    ],
  },
  {
    id: "drop-table/dungeon-f-elite",
    entries: [
      { itemId: "loot/monster-part/crystal-eye", weight: 15, minQuantity: 1, maxQuantity: 1 },
      { itemId: "loot/monster-part/threat-gland", weight: 20, minQuantity: 1, maxQuantity: 1 },
      { itemId: "loot/monster-part/carapace", weight: 25, minQuantity: 1, maxQuantity: 2 },
      { itemId: "loot/monster-part/fang", weight: 20, minQuantity: 1, maxQuantity: 3 },
      { itemId: "loot/monster-part/bone-shard", weight: 20, minQuantity: 1, maxQuantity: 2 },
    ],
  },
  {
    id: "drop-table/dungeon-f-boss",
    entries: [
      { itemId: "loot/monster-part/void-residue", weight: 20, minQuantity: 1, maxQuantity: 1 },
      { itemId: "loot/monster-part/crystal-eye", weight: 25, minQuantity: 1, maxQuantity: 2 },
      { itemId: "weapon/pipe-wrench", weight: 4, minQuantity: 1, maxQuantity: 1 },
      { itemId: "weapon/kitchen-knife", weight: 3, minQuantity: 1, maxQuantity: 1 },
      { itemId: "weapon/crowbar", weight: 4, minQuantity: 1, maxQuantity: 1 },
      { itemId: "weapon/box-cutter", weight: 3, minQuantity: 1, maxQuantity: 1 },
      { itemId: "outfit-overlay/padded-jacket", weight: 2, minQuantity: 1, maxQuantity: 1 },
      { itemId: "outfit-overlay/work-coveralls", weight: 2, minQuantity: 1, maxQuantity: 1 },
      { itemId: "accessory/comm-earpiece", weight: 1, minQuantity: 1, maxQuantity: 1 },
      { itemId: "accessory/wrist-brace", weight: 1, minQuantity: 1, maxQuantity: 1 },
      { itemId: "loot/monster-part/carapace", weight: 20, minQuantity: 1, maxQuantity: 3 },
      { itemId: "loot/monster-part/fang", weight: 20, minQuantity: 2, maxQuantity: 4 },
    ],
  },
  // ── Per-family regular tables ────────────────────────────────────────
  {
    id: "drop-table/tunnel-crawlers-regular",
    entries: [
      { itemId: "loot/monster-part/drain-sludge", weight: 30, minQuantity: 1, maxQuantity: 2 },
      { itemId: "loot/monster-part/pipe-scale", weight: 15, minQuantity: 1, maxQuantity: 1 },
      { itemId: "loot/monster-part/fang", weight: 20, minQuantity: 1, maxQuantity: 2 },
      { itemId: "loot/monster-part/carapace", weight: 15, minQuantity: 1, maxQuantity: 1 },
      { itemId: "loot/monster-part/ichor", weight: 20, minQuantity: 1, maxQuantity: 3 },
    ],
  },
  {
    id: "drop-table/concrete-sentinels-regular",
    entries: [
      { itemId: "loot/monster-part/ramp-gravel", weight: 30, minQuantity: 1, maxQuantity: 2 },
      { itemId: "loot/monster-part/bollard-core", weight: 15, minQuantity: 1, maxQuantity: 1 },
      { itemId: "loot/monster-part/fang", weight: 20, minQuantity: 1, maxQuantity: 2 },
      { itemId: "loot/monster-part/bone-shard", weight: 15, minQuantity: 1, maxQuantity: 1 },
      { itemId: "loot/monster-part/ichor", weight: 20, minQuantity: 1, maxQuantity: 3 },
    ],
  },
  {
    id: "drop-table/chalk-swarms-regular",
    entries: [
      { itemId: "loot/monster-part/chalk-filament", weight: 30, minQuantity: 1, maxQuantity: 2 },
      { itemId: "loot/monster-part/lesson-fragment", weight: 15, minQuantity: 1, maxQuantity: 1 },
      { itemId: "loot/monster-part/fang", weight: 20, minQuantity: 1, maxQuantity: 2 },
      { itemId: "loot/monster-part/sinew", weight: 15, minQuantity: 1, maxQuantity: 1 },
      { itemId: "loot/monster-part/ichor", weight: 20, minQuantity: 1, maxQuantity: 3 },
    ],
  },
  {
    id: "drop-table/vine-constructs-regular",
    entries: [
      { itemId: "loot/monster-part/root-fiber", weight: 30, minQuantity: 1, maxQuantity: 2 },
      { itemId: "loot/monster-part/pollen-sac", weight: 15, minQuantity: 1, maxQuantity: 1 },
      { itemId: "loot/monster-part/fang", weight: 20, minQuantity: 1, maxQuantity: 2 },
      { itemId: "loot/monster-part/carapace", weight: 15, minQuantity: 1, maxQuantity: 1 },
      { itemId: "loot/monster-part/sinew", weight: 20, minQuantity: 1, maxQuantity: 3 },
    ],
  },
  {
    id: "drop-table/suds-constructs-regular",
    entries: [
      { itemId: "loot/monster-part/lint-clump", weight: 30, minQuantity: 1, maxQuantity: 2 },
      { itemId: "loot/monster-part/detergent-crystal", weight: 15, minQuantity: 1, maxQuantity: 1 },
      { itemId: "loot/monster-part/fang", weight: 20, minQuantity: 1, maxQuantity: 2 },
      { itemId: "loot/monster-part/ichor", weight: 15, minQuantity: 1, maxQuantity: 1 },
      { itemId: "loot/monster-part/sinew", weight: 20, minQuantity: 1, maxQuantity: 3 },
    ],
  },
  {
    id: "drop-table/cellar-dwellers-regular",
    entries: [
      { itemId: "loot/monster-part/radiator-ash", weight: 30, minQuantity: 1, maxQuantity: 2 },
      { itemId: "loot/monster-part/basement-mold", weight: 15, minQuantity: 1, maxQuantity: 1 },
      { itemId: "loot/monster-part/fang", weight: 20, minQuantity: 1, maxQuantity: 2 },
      { itemId: "loot/monster-part/bone-shard", weight: 15, minQuantity: 1, maxQuantity: 1 },
      { itemId: "loot/monster-part/ichor", weight: 20, minQuantity: 1, maxQuantity: 3 },
    ],
  },
  {
    id: "drop-table/court-echoes-regular",
    entries: [
      { itemId: "loot/monster-part/echo-resin", weight: 30, minQuantity: 1, maxQuantity: 2 },
      { itemId: "loot/monster-part/rubber-fragment", weight: 15, minQuantity: 1, maxQuantity: 1 },
      { itemId: "loot/monster-part/fang", weight: 20, minQuantity: 1, maxQuantity: 2 },
      { itemId: "loot/monster-part/sinew", weight: 15, minQuantity: 1, maxQuantity: 1 },
      { itemId: "loot/monster-part/bone-shard", weight: 20, minQuantity: 1, maxQuantity: 3 },
    ],
  },
  {
    id: "drop-table/freezer-fauna-regular",
    entries: [
      { itemId: "loot/monster-part/frost-shard", weight: 30, minQuantity: 1, maxQuantity: 2 },
      { itemId: "loot/monster-part/preserved-marrow", weight: 15, minQuantity: 1, maxQuantity: 1 },
      { itemId: "loot/monster-part/fang", weight: 20, minQuantity: 1, maxQuantity: 2 },
      { itemId: "loot/monster-part/carapace", weight: 15, minQuantity: 1, maxQuantity: 1 },
      { itemId: "loot/monster-part/bone-shard", weight: 20, minQuantity: 1, maxQuantity: 3 },
    ],
  },

  // ── Per-family elite tables ─────────────────────────────────────────
  {
    id: "drop-table/tunnel-crawlers-elite",
    entries: [
      { itemId: "loot/monster-part/pipe-scale", weight: 25, minQuantity: 1, maxQuantity: 2 },
      { itemId: "loot/monster-part/drain-sludge", weight: 15, minQuantity: 1, maxQuantity: 3 },
      { itemId: "loot/monster-part/crystal-eye", weight: 15, minQuantity: 1, maxQuantity: 1 },
      { itemId: "loot/monster-part/threat-gland", weight: 20, minQuantity: 1, maxQuantity: 1 },
      { itemId: "loot/monster-part/bone-shard", weight: 15, minQuantity: 1, maxQuantity: 2 },
      { itemId: "loot/monster-part/fang", weight: 10, minQuantity: 1, maxQuantity: 2 },
    ],
  },
  {
    id: "drop-table/concrete-sentinels-elite",
    entries: [
      { itemId: "loot/monster-part/bollard-core", weight: 25, minQuantity: 1, maxQuantity: 2 },
      { itemId: "loot/monster-part/ramp-gravel", weight: 15, minQuantity: 1, maxQuantity: 3 },
      { itemId: "loot/monster-part/crystal-eye", weight: 15, minQuantity: 1, maxQuantity: 1 },
      { itemId: "loot/monster-part/threat-gland", weight: 20, minQuantity: 1, maxQuantity: 1 },
      { itemId: "loot/monster-part/carapace", weight: 15, minQuantity: 1, maxQuantity: 2 },
      { itemId: "loot/monster-part/fang", weight: 10, minQuantity: 1, maxQuantity: 2 },
    ],
  },
  {
    id: "drop-table/chalk-swarms-elite",
    entries: [
      { itemId: "loot/monster-part/lesson-fragment", weight: 25, minQuantity: 1, maxQuantity: 2 },
      { itemId: "loot/monster-part/chalk-filament", weight: 15, minQuantity: 1, maxQuantity: 3 },
      { itemId: "loot/monster-part/crystal-eye", weight: 15, minQuantity: 1, maxQuantity: 1 },
      { itemId: "loot/monster-part/threat-gland", weight: 20, minQuantity: 1, maxQuantity: 1 },
      { itemId: "loot/monster-part/bone-shard", weight: 15, minQuantity: 1, maxQuantity: 2 },
      { itemId: "loot/monster-part/fang", weight: 10, minQuantity: 1, maxQuantity: 2 },
    ],
  },
  {
    id: "drop-table/vine-constructs-elite",
    entries: [
      { itemId: "loot/monster-part/pollen-sac", weight: 25, minQuantity: 1, maxQuantity: 2 },
      { itemId: "loot/monster-part/root-fiber", weight: 15, minQuantity: 1, maxQuantity: 3 },
      { itemId: "loot/monster-part/crystal-eye", weight: 15, minQuantity: 1, maxQuantity: 1 },
      { itemId: "loot/monster-part/threat-gland", weight: 20, minQuantity: 1, maxQuantity: 1 },
      { itemId: "loot/monster-part/sinew", weight: 15, minQuantity: 1, maxQuantity: 2 },
      { itemId: "loot/monster-part/fang", weight: 10, minQuantity: 1, maxQuantity: 2 },
    ],
  },
  {
    id: "drop-table/suds-constructs-elite",
    entries: [
      { itemId: "loot/monster-part/detergent-crystal", weight: 25, minQuantity: 1, maxQuantity: 2 },
      { itemId: "loot/monster-part/lint-clump", weight: 15, minQuantity: 1, maxQuantity: 3 },
      { itemId: "loot/monster-part/crystal-eye", weight: 15, minQuantity: 1, maxQuantity: 1 },
      { itemId: "loot/monster-part/threat-gland", weight: 20, minQuantity: 1, maxQuantity: 1 },
      { itemId: "loot/monster-part/carapace", weight: 15, minQuantity: 1, maxQuantity: 2 },
      { itemId: "loot/monster-part/fang", weight: 10, minQuantity: 1, maxQuantity: 2 },
    ],
  },
  {
    id: "drop-table/cellar-dwellers-elite",
    entries: [
      { itemId: "loot/monster-part/basement-mold", weight: 25, minQuantity: 1, maxQuantity: 2 },
      { itemId: "loot/monster-part/radiator-ash", weight: 15, minQuantity: 1, maxQuantity: 3 },
      { itemId: "loot/monster-part/crystal-eye", weight: 15, minQuantity: 1, maxQuantity: 1 },
      { itemId: "loot/monster-part/threat-gland", weight: 20, minQuantity: 1, maxQuantity: 1 },
      { itemId: "loot/monster-part/bone-shard", weight: 15, minQuantity: 1, maxQuantity: 2 },
      { itemId: "loot/monster-part/fang", weight: 10, minQuantity: 1, maxQuantity: 2 },
    ],
  },
  {
    id: "drop-table/court-echoes-elite",
    entries: [
      { itemId: "loot/monster-part/rubber-fragment", weight: 25, minQuantity: 1, maxQuantity: 2 },
      { itemId: "loot/monster-part/echo-resin", weight: 15, minQuantity: 1, maxQuantity: 3 },
      { itemId: "loot/monster-part/crystal-eye", weight: 15, minQuantity: 1, maxQuantity: 1 },
      { itemId: "loot/monster-part/threat-gland", weight: 20, minQuantity: 1, maxQuantity: 1 },
      { itemId: "loot/monster-part/sinew", weight: 15, minQuantity: 1, maxQuantity: 2 },
      { itemId: "loot/monster-part/fang", weight: 10, minQuantity: 1, maxQuantity: 2 },
    ],
  },
  {
    id: "drop-table/freezer-fauna-elite",
    entries: [
      { itemId: "loot/monster-part/preserved-marrow", weight: 25, minQuantity: 1, maxQuantity: 2 },
      { itemId: "loot/monster-part/frost-shard", weight: 15, minQuantity: 1, maxQuantity: 3 },
      { itemId: "loot/monster-part/crystal-eye", weight: 15, minQuantity: 1, maxQuantity: 1 },
      { itemId: "loot/monster-part/threat-gland", weight: 20, minQuantity: 1, maxQuantity: 1 },
      { itemId: "loot/monster-part/carapace", weight: 15, minQuantity: 1, maxQuantity: 2 },
      { itemId: "loot/monster-part/fang", weight: 10, minQuantity: 1, maxQuantity: 2 },
    ],
  },

  // ── Per-boss tables ─────────────────────────────────────────────────
  {
    id: "drop-table/tunneler-brood-mother",
    entries: [
      { itemId: "loot/monster-part/pipe-scale", weight: 20, minQuantity: 1, maxQuantity: 2 },
      { itemId: "loot/monster-part/drain-sludge", weight: 15, minQuantity: 2, maxQuantity: 4 },
      { itemId: "loot/monster-part/void-residue", weight: 15, minQuantity: 1, maxQuantity: 1 },
      { itemId: "loot/monster-part/crystal-eye", weight: 15, minQuantity: 1, maxQuantity: 2 },
      { itemId: "weapon/pipe-wrench", weight: 8, minQuantity: 1, maxQuantity: 1 },
      { itemId: "outfit-overlay/padded-jacket", weight: 5, minQuantity: 1, maxQuantity: 1 },
      { itemId: "loot/monster-part/carapace", weight: 12, minQuantity: 1, maxQuantity: 3 },
      { itemId: "loot/monster-part/fang", weight: 10, minQuantity: 2, maxQuantity: 4 },
    ],
  },
  {
    id: "drop-table/sewer-warden",
    entries: [
      { itemId: "loot/monster-part/bollard-core", weight: 20, minQuantity: 1, maxQuantity: 2 },
      { itemId: "loot/monster-part/ramp-gravel", weight: 15, minQuantity: 2, maxQuantity: 4 },
      { itemId: "loot/monster-part/void-residue", weight: 15, minQuantity: 1, maxQuantity: 1 },
      { itemId: "loot/monster-part/crystal-eye", weight: 15, minQuantity: 1, maxQuantity: 2 },
      { itemId: "weapon/crowbar", weight: 8, minQuantity: 1, maxQuantity: 1 },
      { itemId: "outfit-overlay/work-coveralls", weight: 5, minQuantity: 1, maxQuantity: 1 },
      { itemId: "loot/monster-part/bone-shard", weight: 12, minQuantity: 1, maxQuantity: 3 },
      { itemId: "loot/monster-part/fang", weight: 10, minQuantity: 2, maxQuantity: 4 },
    ],
  },
  {
    id: "drop-table/phantom-stalker",
    entries: [
      { itemId: "loot/monster-part/lesson-fragment", weight: 20, minQuantity: 1, maxQuantity: 2 },
      { itemId: "loot/monster-part/chalk-filament", weight: 15, minQuantity: 2, maxQuantity: 4 },
      { itemId: "loot/monster-part/void-residue", weight: 15, minQuantity: 1, maxQuantity: 1 },
      { itemId: "loot/monster-part/crystal-eye", weight: 15, minQuantity: 1, maxQuantity: 2 },
      { itemId: "weapon/kitchen-knife", weight: 8, minQuantity: 1, maxQuantity: 1 },
      { itemId: "accessory/comm-earpiece", weight: 5, minQuantity: 1, maxQuantity: 1 },
      { itemId: "loot/monster-part/sinew", weight: 12, minQuantity: 1, maxQuantity: 3 },
      { itemId: "loot/monster-part/fang", weight: 10, minQuantity: 2, maxQuantity: 4 },
    ],
  },
  {
    id: "drop-table/the-curator",
    entries: [
      { itemId: "loot/monster-part/pollen-sac", weight: 20, minQuantity: 1, maxQuantity: 2 },
      { itemId: "loot/monster-part/root-fiber", weight: 15, minQuantity: 2, maxQuantity: 4 },
      { itemId: "loot/monster-part/void-residue", weight: 15, minQuantity: 1, maxQuantity: 1 },
      { itemId: "loot/monster-part/crystal-eye", weight: 15, minQuantity: 1, maxQuantity: 2 },
      { itemId: "weapon/box-cutter", weight: 8, minQuantity: 1, maxQuantity: 1 },
      { itemId: "outfit-overlay/leather-vest", weight: 5, minQuantity: 1, maxQuantity: 1 },
      { itemId: "loot/monster-part/sinew", weight: 12, minQuantity: 1, maxQuantity: 3 },
      { itemId: "loot/monster-part/fang", weight: 10, minQuantity: 2, maxQuantity: 4 },
    ],
  },
  {
    id: "drop-table/the-attendant",
    entries: [
      { itemId: "loot/monster-part/detergent-crystal", weight: 20, minQuantity: 1, maxQuantity: 2 },
      { itemId: "loot/monster-part/lint-clump", weight: 15, minQuantity: 2, maxQuantity: 4 },
      { itemId: "loot/monster-part/void-residue", weight: 15, minQuantity: 1, maxQuantity: 1 },
      { itemId: "loot/monster-part/crystal-eye", weight: 15, minQuantity: 1, maxQuantity: 2 },
      { itemId: "weapon/pipe-wrench", weight: 8, minQuantity: 1, maxQuantity: 1 },
      { itemId: "outfit-overlay/work-coveralls", weight: 5, minQuantity: 1, maxQuantity: 1 },
      { itemId: "loot/monster-part/carapace", weight: 12, minQuantity: 1, maxQuantity: 3 },
      { itemId: "loot/monster-part/fang", weight: 10, minQuantity: 2, maxQuantity: 4 },
    ],
  },
  {
    id: "drop-table/the-super",
    entries: [
      { itemId: "loot/monster-part/basement-mold", weight: 20, minQuantity: 1, maxQuantity: 2 },
      { itemId: "loot/monster-part/radiator-ash", weight: 15, minQuantity: 2, maxQuantity: 4 },
      { itemId: "loot/monster-part/void-residue", weight: 15, minQuantity: 1, maxQuantity: 1 },
      { itemId: "loot/monster-part/crystal-eye", weight: 15, minQuantity: 1, maxQuantity: 2 },
      { itemId: "weapon/crowbar", weight: 8, minQuantity: 1, maxQuantity: 1 },
      { itemId: "accessory/wrist-brace", weight: 5, minQuantity: 1, maxQuantity: 1 },
      { itemId: "loot/monster-part/bone-shard", weight: 12, minQuantity: 1, maxQuantity: 3 },
      { itemId: "loot/monster-part/fang", weight: 10, minQuantity: 2, maxQuantity: 4 },
    ],
  },
  {
    id: "drop-table/the-referee",
    entries: [
      { itemId: "loot/monster-part/rubber-fragment", weight: 20, minQuantity: 1, maxQuantity: 2 },
      { itemId: "loot/monster-part/echo-resin", weight: 15, minQuantity: 2, maxQuantity: 4 },
      { itemId: "loot/monster-part/void-residue", weight: 15, minQuantity: 1, maxQuantity: 1 },
      { itemId: "loot/monster-part/crystal-eye", weight: 15, minQuantity: 1, maxQuantity: 2 },
      { itemId: "weapon/baseball-bat", weight: 8, minQuantity: 1, maxQuantity: 1 },
      { itemId: "accessory/tactical-scarf", weight: 5, minQuantity: 1, maxQuantity: 1 },
      { itemId: "loot/monster-part/sinew", weight: 12, minQuantity: 1, maxQuantity: 3 },
      { itemId: "loot/monster-part/fang", weight: 10, minQuantity: 2, maxQuantity: 4 },
    ],
  },
  {
    id: "drop-table/the-stockkeeper",
    entries: [
      { itemId: "loot/monster-part/preserved-marrow", weight: 20, minQuantity: 1, maxQuantity: 2 },
      { itemId: "loot/monster-part/frost-shard", weight: 15, minQuantity: 2, maxQuantity: 4 },
      { itemId: "loot/monster-part/void-residue", weight: 15, minQuantity: 1, maxQuantity: 1 },
      { itemId: "loot/monster-part/crystal-eye", weight: 15, minQuantity: 1, maxQuantity: 2 },
      { itemId: "weapon/kitchen-knife", weight: 8, minQuantity: 1, maxQuantity: 1 },
      { itemId: "outfit-overlay/padded-jacket", weight: 5, minQuantity: 1, maxQuantity: 1 },
      { itemId: "loot/monster-part/carapace", weight: 12, minQuantity: 1, maxQuantity: 3 },
      { itemId: "loot/monster-part/fang", weight: 10, minQuantity: 2, maxQuantity: 4 },
    ],
  },
] satisfies readonly DropTable[];
