import type { DropTable, ItemTemplate } from "./shared";

export const itemTemplates = [
  // --- Weapons ---
  {
    id: "weapon/pipe-wrench",
    kind: "item",
    name: "Pipe Wrench",
    tags: ["rank:f"],
    description: "A heavy wrench repurposed for close combat.",
    category: "weapon",
    rank: "f",
    buyPrice: 30,
    sellPrice: 12,
    statEffects: [{ stat: "strength", value: 3 }],
  },
  {
    id: "weapon/kitchen-knife",
    kind: "item",
    name: "Kitchen Knife",
    tags: ["rank:f"],
    description: "A sharp blade from the bodega kitchen drawer.",
    category: "weapon",
    rank: "f",
    buyPrice: 25,
    sellPrice: 10,
    statEffects: [
      { stat: "speed", value: 2 },
      { stat: "strength", value: 1 },
    ],
  },
  {
    id: "weapon/baseball-bat",
    kind: "item",
    name: "Baseball Bat",
    tags: ["rank:f"],
    description: "Reliable blunt force in a familiar shape.",
    category: "weapon",
    rank: "f",
    buyPrice: 35,
    sellPrice: 14,
    statEffects: [{ stat: "strength", value: 4 }],
  },
  {
    id: "weapon/tactical-knife",
    kind: "item",
    name: "Tactical Knife",
    tags: ["rank:e"],
    description: "A purpose-built combat knife with a reinforced grip.",
    category: "weapon",
    rank: "e",
    buyPrice: 60,
    sellPrice: 25,
    statEffects: [
      { stat: "speed", value: 3 },
      { stat: "strength", value: 2 },
    ],
  },
  {
    id: "weapon/machete",
    kind: "item",
    name: "Machete",
    tags: ["rank:e"],
    description: "A long, heavy blade suited for clearing paths and threats.",
    category: "weapon",
    rank: "e",
    buyPrice: 75,
    sellPrice: 30,
    statEffects: [{ stat: "strength", value: 5 }],
  },
  {
    id: "weapon/compact-crossbow",
    kind: "item",
    name: "Compact Crossbow",
    tags: ["rank:e"],
    description: "A small crossbow offering ranged precision at short distances.",
    category: "weapon",
    rank: "e",
    buyPrice: 85,
    sellPrice: 35,
    statEffects: [
      { stat: "speed", value: 2 },
      { stat: "perception", value: 2 },
      { stat: "strength", value: 2 },
    ],
  },
  {
    id: "weapon/reinforced-bat",
    kind: "item",
    name: "Reinforced Bat",
    tags: ["rank:d"],
    description: "A steel-core bat wrapped in shock-absorbing tape.",
    category: "weapon",
    rank: "d",
    buyPrice: 120,
    sellPrice: 50,
    statEffects: [
      { stat: "strength", value: 6 },
      { stat: "resilience", value: 2 },
    ],
  },
  {
    id: "weapon/katana",
    kind: "item",
    name: "Katana",
    tags: ["rank:d"],
    description: "A balanced blade that rewards skilled hands.",
    category: "weapon",
    rank: "d",
    buyPrice: 150,
    sellPrice: 60,
    statEffects: [
      { stat: "speed", value: 4 },
      { stat: "strength", value: 5 },
    ],
  },
  {
    id: "weapon/tactical-rifle",
    kind: "item",
    name: "Tactical Rifle",
    tags: ["rank:d"],
    description: "A modular rifle platform built for field operations.",
    category: "weapon",
    rank: "d",
    buyPrice: 180,
    sellPrice: 75,
    statEffects: [
      { stat: "strength", value: 4 },
      { stat: "speed", value: 3 },
      { stat: "perception", value: 3 },
    ],
  },
  {
    id: "weapon/dual-daggers",
    kind: "item",
    name: "Dual Daggers",
    tags: ["rank:d"],
    description: "A matched pair of lightweight combat daggers.",
    category: "weapon",
    rank: "d",
    buyPrice: 140,
    sellPrice: 55,
    statEffects: [
      { stat: "speed", value: 6 },
      { stat: "strength", value: 3 },
    ],
  },

  // --- Outfit Overlays ---
  {
    id: "outfit-overlay/padded-jacket",
    kind: "item",
    name: "Padded Jacket",
    tags: ["rank:f"],
    description: "A thick jacket offering basic protection against impacts.",
    category: "outfit-overlay",
    rank: "f",
    buyPrice: 40,
    sellPrice: 16,
    statEffects: [
      { stat: "resilience", value: 2 },
      { stat: "endurance", value: 1 },
    ],
  },
  {
    id: "outfit-overlay/leather-vest",
    kind: "item",
    name: "Leather Vest",
    tags: ["rank:f"],
    description: "A rugged leather vest that absorbs light blows.",
    category: "outfit-overlay",
    rank: "f",
    buyPrice: 35,
    sellPrice: 14,
    statEffects: [{ stat: "resilience", value: 3 }],
  },
  {
    id: "outfit-overlay/tactical-vest",
    kind: "item",
    name: "Tactical Vest",
    tags: ["rank:e"],
    description: "A purpose-built vest with plating and utility pockets.",
    category: "outfit-overlay",
    rank: "e",
    buyPrice: 80,
    sellPrice: 32,
    statEffects: [
      { stat: "resilience", value: 4 },
      { stat: "endurance", value: 2 },
    ],
  },
  {
    id: "outfit-overlay/stealth-cloak",
    kind: "item",
    name: "Stealth Cloak",
    tags: ["rank:e"],
    description: "A lightweight cloak that dampens sound and movement.",
    category: "outfit-overlay",
    rank: "e",
    buyPrice: 90,
    sellPrice: 36,
    statEffects: [
      { stat: "speed", value: 3 },
      { stat: "resilience", value: 2 },
    ],
  },
  {
    id: "outfit-overlay/heavy-plate",
    kind: "item",
    name: "Heavy Plate",
    tags: ["rank:d"],
    description: "A layered armor plate that trades mobility for serious protection.",
    category: "outfit-overlay",
    rank: "d",
    buyPrice: 160,
    sellPrice: 65,
    statEffects: [
      { stat: "resilience", value: 7 },
      { stat: "endurance", value: 3 },
    ],
  },
  {
    id: "outfit-overlay/field-medic-coat",
    kind: "item",
    name: "Field Medic Coat",
    tags: ["rank:d"],
    description: "A reinforced medical coat with integrated supply pouches.",
    category: "outfit-overlay",
    rank: "d",
    buyPrice: 140,
    sellPrice: 55,
    statEffects: [
      { stat: "resilience", value: 4 },
      { stat: "endurance", value: 4 },
      { stat: "perception", value: 2 },
    ],
  },

  // --- Accessories ---
  {
    id: "accessory/comm-earpiece",
    kind: "item",
    name: "Comm Earpiece",
    tags: ["rank:f"],
    description: "A discreet earpiece for field communication.",
    category: "accessory",
    rank: "f",
    buyPrice: 20,
    sellPrice: 8,
    statEffects: [{ stat: "perception", value: 2 }],
  },
  {
    id: "accessory/tactical-scarf",
    kind: "item",
    name: "Tactical Scarf",
    tags: ["rank:f"],
    description: "A multi-purpose scarf that shields against dust and debris.",
    category: "accessory",
    rank: "f",
    buyPrice: 15,
    sellPrice: 6,
    statEffects: [
      { stat: "resilience", value: 1 },
      { stat: "speed", value: 1 },
    ],
  },
  {
    id: "accessory/eye-visor",
    kind: "item",
    name: "Eye Visor",
    tags: ["rank:e"],
    description: "An optical visor that enhances threat detection.",
    category: "accessory",
    rank: "e",
    buyPrice: 55,
    sellPrice: 22,
    statEffects: [{ stat: "perception", value: 4 }],
  },
  {
    id: "accessory/medkit-pouch",
    kind: "item",
    name: "Medkit Pouch",
    tags: ["rank:e"],
    description: "A compact medical pouch worn on the belt.",
    category: "accessory",
    rank: "e",
    buyPrice: 65,
    sellPrice: 26,
    statEffects: [
      { stat: "resilience", value: 2 },
      { stat: "endurance", value: 2 },
    ],
  },
  {
    id: "accessory/scout-binocs",
    kind: "item",
    name: "Scout Binocs",
    tags: ["rank:e"],
    description: "Lightweight binoculars for long-range reconnaissance.",
    category: "accessory",
    rank: "e",
    buyPrice: 50,
    sellPrice: 20,
    statEffects: [{ stat: "perception", value: 5 }],
  },
  {
    id: "accessory/field-lead-badge",
    kind: "item",
    name: "Field Lead Badge",
    tags: ["rank:e"],
    description: "An authority badge that bolsters composure under pressure.",
    category: "accessory",
    rank: "e",
    buyPrice: 45,
    sellPrice: 18,
    statEffects: [
      { stat: "resilience", value: 3 },
      { stat: "endurance", value: 1 },
    ],
  },
  {
    id: "accessory/reinforced-gloves",
    kind: "item",
    name: "Reinforced Gloves",
    tags: ["rank:d"],
    description: "Hardened gloves that protect hands and improve grip strength.",
    category: "accessory",
    rank: "d",
    buyPrice: 100,
    sellPrice: 40,
    statEffects: [
      { stat: "strength", value: 3 },
      { stat: "resilience", value: 3 },
    ],
  },

  // --- Monster Part Loot ---
  {
    id: "loot/monster-part/fang",
    kind: "item",
    name: "Fang",
    tags: ["loot:monster_part", "loot:sell_only"],
    description: "A sharp tooth ripped from a hostile creature.",
    category: "loot",
    rank: "f",
    buyPrice: 0,
    sellPrice: 8,
    statEffects: [],
  },
  {
    id: "loot/monster-part/carapace",
    kind: "item",
    name: "Carapace",
    tags: ["loot:monster_part", "loot:sell_only"],
    description: "A thick shell fragment that once shielded a threat.",
    category: "loot",
    rank: "f",
    buyPrice: 0,
    sellPrice: 12,
    statEffects: [],
  },
  {
    id: "loot/monster-part/ichor",
    kind: "item",
    name: "Ichor",
    tags: ["loot:monster_part", "loot:sell_only"],
    description: "A viscous fluid harvested from a defeated anomaly.",
    category: "loot",
    rank: "f",
    buyPrice: 0,
    sellPrice: 6,
    statEffects: [],
  },
  {
    id: "loot/monster-part/bone-shard",
    kind: "item",
    name: "Bone Shard",
    tags: ["loot:monster_part", "loot:sell_only"],
    description: "A jagged bone fragment from a large creature.",
    category: "loot",
    rank: "f",
    buyPrice: 0,
    sellPrice: 10,
    statEffects: [],
  },
  {
    id: "loot/monster-part/sinew",
    kind: "item",
    name: "Sinew",
    tags: ["loot:monster_part", "loot:sell_only"],
    description: "Tough connective tissue with residual tension.",
    category: "loot",
    rank: "f",
    buyPrice: 0,
    sellPrice: 7,
    statEffects: [],
  },
  {
    id: "loot/monster-part/crystal-eye",
    kind: "item",
    name: "Crystal Eye",
    tags: ["loot:monster_part", "loot:sell_only", "rank:e"],
    description: "A crystallized eye that refracts ambient light.",
    category: "loot",
    rank: "e",
    buyPrice: 0,
    sellPrice: 18,
    statEffects: [],
  },
  {
    id: "loot/monster-part/void-residue",
    kind: "item",
    name: "Void Residue",
    tags: ["loot:monster_part", "loot:sell_only", "rank:d"],
    description: "A dark, shimmering substance from a powerful entity.",
    category: "loot",
    rank: "d",
    buyPrice: 0,
    sellPrice: 25,
    statEffects: [],
  },
  {
    id: "loot/monster-part/threat-gland",
    kind: "item",
    name: "Threat Gland",
    tags: ["loot:monster_part", "loot:sell_only", "rank:e"],
    description: "A glandular organ that once powered a creature's aggression.",
    category: "loot",
    rank: "e",
    buyPrice: 0,
    sellPrice: 15,
    statEffects: [],
  },
] satisfies readonly ItemTemplate[];

export const dropTables = [
  {
    id: "drop-table/dungeon-f-regular",
    entries: [
      { itemId: "loot/monster-part/fang", weight: 30, minQuantity: 1, maxQuantity: 2 },
      { itemId: "loot/monster-part/carapace", weight: 20, minQuantity: 1, maxQuantity: 1 },
      { itemId: "loot/monster-part/ichor", weight: 25, minQuantity: 1, maxQuantity: 3 },
      { itemId: "loot/monster-part/bone-shard", weight: 15, minQuantity: 1, maxQuantity: 1 },
      { itemId: "loot/monster-part/sinew", weight: 10, minQuantity: 1, maxQuantity: 2 },
    ],
  },
  {
    id: "drop-table/dungeon-f-elite",
    entries: [
      { itemId: "loot/monster-part/crystal-eye", weight: 15, minQuantity: 1, maxQuantity: 1 },
      { itemId: "loot/monster-part/threat-gland", weight: 20, minQuantity: 1, maxQuantity: 1 },
      { itemId: "loot/monster-part/carapace", weight: 25, minQuantity: 1, maxQuantity: 2 },
      { itemId: "loot/monster-part/fang", weight: 20, minQuantity: 1, maxQuantity: 3 },
      { itemId: "loot/monster-part/bone-shard", weight: 20, minQuantity: 1, maxQuantity: 2 },
    ],
  },
  {
    id: "drop-table/dungeon-f-boss",
    entries: [
      { itemId: "loot/monster-part/void-residue", weight: 20, minQuantity: 1, maxQuantity: 1 },
      { itemId: "loot/monster-part/crystal-eye", weight: 25, minQuantity: 1, maxQuantity: 2 },
      { itemId: "weapon/pipe-wrench", weight: 5, minQuantity: 1, maxQuantity: 1 },
      { itemId: "weapon/kitchen-knife", weight: 5, minQuantity: 1, maxQuantity: 1 },
      { itemId: "outfit-overlay/padded-jacket", weight: 3, minQuantity: 1, maxQuantity: 1 },
      { itemId: "accessory/comm-earpiece", weight: 2, minQuantity: 1, maxQuantity: 1 },
      { itemId: "loot/monster-part/carapace", weight: 20, minQuantity: 1, maxQuantity: 3 },
      { itemId: "loot/monster-part/fang", weight: 20, minQuantity: 2, maxQuantity: 4 },
    ],
  },
] satisfies readonly DropTable[];
