import type { MissionTemplate } from "./shared";

export const missionTemplates = [
  {
    id: "mission/clearance",
    kind: "mission",
    name: "Clearance",
    tags: ["mission:combat", "objective:clear"],
    description: "Remove an entrenched threat from a known site.",
    objectiveType: "clearance",
    expectedThreatTags: ["threat:clustered", "threat:hostile"],
    rewardShape: "hybrid",
    intelConfidenceFloor: "medium",
    baseDurationHours: 6,
    combatProfile: {
      enemyGroups: [
        { threat: 30, count: 3, dropTableId: "drop-table/dungeon-f-regular" },
        { threat: 55, count: 1, dropTableId: "drop-table/dungeon-f-elite" },
      ],
      boss: {
        bossId: "boss/tunneler-brood-mother",
        name: "Tunneler Brood-Mother",
        rank: "f",
        phases: 2,
        tags: ["boss:area-damage", "boss:summon-pressure"],
        weaknesses: [{ kind: "role", target: "role:field_lead", multiplier: 1.3 }],
        attack: 35,
        defense: 25,
        hp: 100,
        speed: 20,
        threat: 60,
        dropTableId: "drop-table/dungeon-f-boss",
      },
    },
  },
  {
    id: "mission/containment",
    kind: "mission",
    name: "Containment",
    tags: ["mission:stability", "objective:hold"],
    description: "Stabilize a volatile site before it escalates or spills.",
    objectiveType: "containment",
    expectedThreatTags: ["threat:unstable", "threat:hazard"],
    rewardShape: "cash",
    intelConfidenceFloor: "low",
    baseDurationHours: 4,
    combatProfile: {
      enemyGroups: [{ threat: 25, count: 2, dropTableId: "drop-table/dungeon-f-regular" }],
      boss: {
        bossId: "boss/sewer-warden",
        name: "Sewer Warden",
        rank: "f",
        phases: 1,
        tags: ["boss:resilience-pierce", "boss:recovery-suppress"],
        weaknesses: [{ kind: "stat", target: "resilience", multiplier: 1.25 }],
        attack: 28,
        defense: 35,
        hp: 80,
        speed: 15,
        threat: 50,
        dropTableId: "drop-table/dungeon-f-boss",
      },
    },
  },
  {
    id: "mission/extraction",
    kind: "mission",
    name: "Extraction",
    tags: ["mission:retrieval", "objective:escort"],
    description: "Recover a target under pressure and bring them out intact.",
    objectiveType: "extraction",
    expectedThreatTags: ["threat:mobile", "threat:ambush"],
    rewardShape: "loot",
    intelConfidenceFloor: "high",
    baseDurationHours: 5,
    combatProfile: {
      enemyGroups: [{ threat: 40, count: 2, dropTableId: "drop-table/dungeon-f-elite" }],
      boss: {
        bossId: "boss/phantom-stalker",
        name: "Phantom Stalker",
        rank: "f",
        phases: 2,
        tags: ["boss:speed-drain", "boss:intel-resist"],
        weaknesses: [
          { kind: "role", target: "role:scout", multiplier: 1.35 },
          { kind: "stat", target: "perception", multiplier: 1.2 },
        ],
        attack: 40,
        defense: 20,
        hp: 70,
        speed: 45,
        threat: 55,
        dropTableId: "drop-table/dungeon-f-boss",
      },
    },
  },
] satisfies readonly MissionTemplate[];
