import type { ResourceTemplate } from "./shared";

export const resourceTemplates = [
  {
    id: "resource/cash",
    kind: "resource",
    name: "Cash",
    tags: ["resource:liquid", "economy:core"],
    description: "The base liquid budget for payroll, supplies, and building work.",
    startingAmount: 250,
  },
  {
    id: "resource/reputation",
    kind: "resource",
    name: "Reputation",
    tags: ["resource:pressure", "progression:external"],
    description: "Visibility and scrutiny generated by guild performance.",
    startingAmount: 0,
  },
  {
    id: "resource/intel",
    kind: "resource",
    name: "Intel",
    tags: ["resource:knowledge", "ops:planning"],
    description: "Structured knowledge used to judge likely mission conditions.",
    startingAmount: 1,
  },
] satisfies readonly ResourceTemplate[];
