import type { RoomTemplate } from "./shared";

export const roomTemplates = [
  {
    id: "room/register:tier_1",
    kind: "room",
    name: "The Register",
    tags: ["room:operations", "staff:reception"],
    description: "The checkout counter where intake, paperwork, and walk-in visitors all collide.",
    tier: 1,
    baseCapacity: 2,
    availableInBuildings: ["building/bodega"],
  },
  {
    id: "room/counter:tier_1",
    kind: "room",
    name: "The Counter",
    tags: ["room:social", "ops:recruitment"],
    description:
      "The deli counter where Boss sells food, talks people up, and recruits whoever lingers.",
    tier: 1,
    baseCapacity: 2,
    availableInBuildings: ["building/bodega"],
  },
  {
    id: "room/dining_area:tier_1",
    kind: "room",
    name: "The Dining Area",
    tags: ["room:recovery", "room:social"],
    description:
      "The shared table where operators eat, decompress, and get patched up when the day goes bad.",
    tier: 1,
    baseCapacity: 3,
    availableInBuildings: ["building/bodega"],
  },
  {
    id: "room/supply_closet:tier_1",
    kind: "room",
    name: "Supply Closet",
    tags: ["room:staffing", "staff:logistics"],
    description:
      "A cramped back-room closet for gear, stock, paperwork overflow, and whatever else fits on the shelf.",
    tier: 1,
    baseCapacity: 2,
    availableInBuildings: ["building/bodega"],
  },
  {
    id: "room/front_desk:tier_1",
    kind: "room",
    name: "Front Desk",
    tags: ["room:operations", "staff:reception"],
    description:
      "A proper public-facing operations desk for intake, scheduling, and contract traffic.",
    tier: 1,
    baseCapacity: 2,
    availableInBuildings: ["building/union_hall"],
  },
  {
    id: "room/recruitment_office:tier_1",
    kind: "room",
    name: "Recruitment Office",
    tags: ["room:social", "ops:recruitment", "staff:admin"],
    description:
      "A real office for interviews, onboarding, and scheduled recruitment conversations.",
    tier: 1,
    baseCapacity: 2,
    availableInBuildings: ["building/union_hall"],
  },
  {
    id: "room/infirmary:tier_1",
    kind: "room",
    name: "Infirmary",
    tags: ["room:recovery", "staff:medical"],
    description: "Dedicated medical and recovery space for injured operators.",
    tier: 1,
    baseCapacity: 3,
    availableInBuildings: ["building/union_hall"],
  },
  {
    id: "room/break_room:tier_1",
    kind: "room",
    name: "Break Room",
    tags: ["room:recovery", "room:social"],
    description: "A separate room for meals, downtime, and ordinary decompression.",
    tier: 1,
    baseCapacity: 3,
    availableInBuildings: ["building/union_hall"],
  },
  {
    id: "room/lounge:tier_1",
    kind: "room",
    name: "Lounge",
    tags: ["room:social"],
    description: "A comfortable social space that helps operators feel like people again.",
    tier: 1,
    baseCapacity: 4,
    availableInBuildings: ["building/bodega", "building/union_hall"],
  },
  {
    id: "room/gym:tier_1",
    kind: "room",
    name: "Gym",
    tags: ["room:training"],
    description: "A scrappy but real training room with enough equipment to matter.",
    tier: 1,
    baseCapacity: 2,
    availableInBuildings: ["building/bodega", "building/union_hall"],
  },
  {
    id: "room/sparring_room:tier_1",
    kind: "room",
    name: "Sparring Room",
    tags: ["room:training"],
    description: "A dedicated combat training space for advanced operator drills.",
    tier: 1,
    baseCapacity: 2,
    availableInBuildings: ["building/union_hall"],
  },
] satisfies readonly RoomTemplate[];
