/**
 * HQ static scene composition data.
 *
 * Each building owns one exterior scene composition expressed as grid-anchored
 * placements. All positions use isometric col/row coordinates — no raw screen
 * x/y. The projection function in hq-world.ts converts these to screen-space
 * HqSpritePlacement records at composition time.
 *
 * Placement contract:
 * - Every placement specifies `svgMeta` with the asset's viewBox and an anchor
 *   point in SVG user-space.  The renderer derives screen dimensions from
 *   `viewBox × scale` and maps the SVG anchor to the grid point (col, row).
 * - `width`/`height` mirror the viewBox dimensions for documentation only.
 * - `scale` adjusts visual size relative to the grid (1.0 = SVG natural size).
 * - `offsetX`/`offsetY` are small fine-tuning corrections, not the primary contract.
 * - `footprintCols`/`footprintRows` are builder metadata (not used by renderer).
 */

import type { HqSceneComposition, HqStaticPlacementDef } from "./types";

// Exported from the scene builder. Keep this composition aligned with the
// canonical builder output rather than hand-tuning it here.

const BODEGA_EXTERIOR_PLACEMENTS: readonly HqStaticPlacementDef[] = [
  {
    id: "scenery/back-alley",
    assetId: "background/iso-bg-back-alley",
    assetUrl: "/data/svg-environments/hq/bodega/parts/background/iso-bg-back-alley.svg",
    kind: "exterior",
    col: 0,
    row: 10,
    anchorMode: "iso-bottom",
    width: 600,
    height: 310,
    zIndex: 2,
    opacity: 1,
    scale: 1,
    svgMeta: {
      svgAnchorX: 300,
      svgAnchorY: 310,
      viewBox: [0, 0, 600, 310],
    },
    tags: ["alley", "behind"],
  },
  {
    id: "scenery/trash-bags",
    assetId: "background/iso-bg-trash-bags",
    assetUrl: "/data/svg-environments/hq/bodega/parts/background/iso-bg-trash-bags.svg",
    kind: "exterior",
    col: -5.5,
    row: 4.5,
    anchorMode: "iso-bottom",
    width: 64,
    height: 44,
    zIndex: 2,
    opacity: 1,
    scale: 1,
    svgMeta: {
      svgAnchorX: 32,
      svgAnchorY: 44,
      viewBox: [0, 0, 64, 44],
    },
    tags: ["trash", "behind"],
  },
  {
    id: "scenery/main-tree-left",
    assetId: "background/iso-bg-tree-street",
    assetUrl: "/data/svg-environments/hq/bodega/parts/background/iso-bg-tree-street.svg",
    kind: "exterior",
    col: -7,
    row: 20,
    anchorMode: "iso-bottom",
    width: 60,
    height: 100,
    zIndex: 9,
    opacity: 0.82,
    scale: 2,
    svgMeta: {
      svgAnchorX: 30,
      svgAnchorY: 100,
      viewBox: [0, 0, 60, 100],
    },
    tags: ["tree", "sidewalk", "main-street"],
  },
  {
    id: "scenery/main-lamp-left",
    assetId: "background/iso-bg-lamppost",
    assetUrl: "/data/svg-environments/hq/bodega/parts/background/iso-bg-lamppost.svg",
    kind: "exterior",
    col: -3,
    row: 20,
    anchorMode: "iso-bottom",
    width: 48,
    height: 180,
    zIndex: 10,
    opacity: 0.82,
    scale: 0.88,
    svgMeta: {
      svgAnchorX: 24,
      svgAnchorY: 180,
      viewBox: [0, 0, 48, 180],
    },
    tags: ["lamppost", "sidewalk", "main-street"],
  },
  {
    id: "scenery/main-lamp-center",
    assetId: "background/iso-bg-lamppost",
    assetUrl: "/data/svg-environments/hq/bodega/parts/background/iso-bg-lamppost.svg",
    kind: "exterior",
    col: 5,
    row: 20,
    anchorMode: "iso-bottom",
    width: 48,
    height: 180,
    zIndex: 10,
    opacity: 0.82,
    scale: 0.88,
    svgMeta: {
      svgAnchorX: 24,
      svgAnchorY: 180,
      viewBox: [0, 0, 48, 180],
    },
    tags: ["lamppost", "sidewalk", "main-street"],
  },
  {
    id: "scenery/main-bench",
    assetId: "background/iso-bg-bench",
    assetUrl: "/data/svg-environments/hq/bodega/parts/background/iso-bg-bench.svg",
    kind: "exterior",
    col: 1,
    row: 20,
    anchorMode: "iso-bottom",
    width: 72,
    height: 58,
    zIndex: 9,
    opacity: 1,
    scale: 1,
    svgMeta: {
      svgAnchorX: 36,
      svgAnchorY: 58,
      viewBox: [0, 0, 72, 58],
    },
    tags: ["bench", "sidewalk", "main-street"],
  },
  {
    id: "scenery/main-mailbox",
    assetId: "background/iso-bg-mailbox",
    assetUrl: "/data/svg-environments/hq/bodega/parts/background/iso-bg-mailbox.svg",
    kind: "exterior",
    col: 3.5,
    row: 20,
    anchorMode: "iso-bottom",
    width: 36,
    height: 52,
    zIndex: 9,
    opacity: 1,
    scale: 1,
    svgMeta: {
      svgAnchorX: 18,
      svgAnchorY: 52,
      viewBox: [0, 0, 36, 52],
    },
    tags: ["mailbox", "sidewalk", "main-street"],
  },
  {
    id: "scenery/main-trash-can",
    assetId: "background/iso-bg-trash-can-wire",
    assetUrl: "/data/svg-environments/hq/bodega/parts/background/iso-bg-trash-can-wire.svg",
    kind: "exterior",
    col: 7,
    row: 20,
    anchorMode: "iso-bottom",
    width: 36,
    height: 56,
    zIndex: 9,
    opacity: 1,
    scale: 1,
    svgMeta: {
      svgAnchorX: 18,
      svgAnchorY: 52,
      viewBox: [0, 0, 36, 56],
    },
    tags: ["trash-can", "sidewalk", "main-street"],
  },
  {
    id: "scenery/main-hydrant",
    assetId: "background/iso-bg-hydrant",
    assetUrl: "/data/svg-environments/hq/bodega/parts/background/iso-bg-hydrant.svg",
    kind: "exterior",
    col: 9.5,
    row: 20,
    anchorMode: "iso-bottom",
    width: 40,
    height: 56,
    zIndex: 9,
    opacity: 1,
    scale: 1,
    svgMeta: {
      svgAnchorX: 20,
      svgAnchorY: 56,
      viewBox: [0, 0, 40, 56],
    },
    tags: ["hydrant", "sidewalk", "main-street"],
  },
  {
    id: "scenery/traffic-light-nw",
    assetId: "background/iso-bg-traffic-light",
    assetUrl: "/data/svg-environments/hq/bodega/parts/background/iso-bg-traffic-light.svg",
    kind: "exterior",
    col: 13,
    row: 21.5,
    anchorMode: "iso-bottom",
    width: 64,
    height: 210,
    zIndex: 11,
    opacity: 0.9,
    scale: 0.9,
    svgMeta: {
      svgAnchorX: 24,
      svgAnchorY: 205,
      viewBox: [0, 0, 64, 210],
    },
    tags: ["traffic-light", "intersection", "nw-corner"],
  },
  {
    id: "scenery/traffic-light-sw",
    assetId: "background/iso-bg-traffic-light",
    assetUrl: "/data/svg-environments/hq/bodega/parts/background/iso-bg-traffic-light.svg",
    kind: "exterior",
    col: 13,
    row: 33,
    anchorMode: "iso-bottom",
    width: 64,
    height: 210,
    zIndex: 11,
    opacity: 0.75,
    scale: 0.9,
    svgMeta: {
      svgAnchorX: 24,
      svgAnchorY: 205,
      viewBox: [0, 0, 64, 210],
    },
    tags: ["traffic-light", "intersection", "sw-corner"],
  },
  {
    id: "scenery/traffic-light-ne",
    assetId: "background/iso-bg-traffic-light",
    assetUrl: "/data/svg-environments/hq/bodega/parts/background/iso-bg-traffic-light.svg",
    kind: "exterior",
    col: 25,
    row: 21,
    anchorMode: "iso-bottom",
    width: 64,
    height: 210,
    zIndex: 11,
    opacity: 0.75,
    scale: 0.9,
    svgMeta: {
      svgAnchorX: 24,
      svgAnchorY: 205,
      viewBox: [0, 0, 64, 210],
    },
    tags: ["traffic-light", "intersection", "ne-corner"],
  },
  {
    id: "scenery/traffic-light-se",
    assetId: "background/iso-bg-traffic-light",
    assetUrl: "/data/svg-environments/hq/bodega/parts/background/iso-bg-traffic-light.svg",
    kind: "exterior",
    col: 25,
    row: 33,
    anchorMode: "iso-bottom",
    width: 64,
    height: 210,
    zIndex: 11,
    opacity: 0.6,
    scale: 0.9,
    svgMeta: {
      svgAnchorX: 24,
      svgAnchorY: 205,
      viewBox: [0, 0, 64, 210],
    },
    tags: ["traffic-light", "intersection", "se-corner"],
  },
  {
    id: "scenery/intersection-street-sign",
    assetId: "background/iso-bg-street-sign",
    assetUrl: "/data/svg-environments/hq/bodega/parts/background/iso-bg-street-sign.svg",
    kind: "exterior",
    col: 13,
    row: 20,
    anchorMode: "iso-bottom",
    width: 56,
    height: 185,
    zIndex: 10,
    opacity: 0.85,
    scale: 0.85,
    svgMeta: {
      svgAnchorX: 20,
      svgAnchorY: 180,
      viewBox: [0, 0, 56, 185],
    },
    tags: ["street-sign", "intersection"],
  },
  {
    id: "scenery/side-lamp-upper",
    assetId: "background/iso-bg-lamppost",
    assetUrl: "/data/svg-environments/hq/bodega/parts/background/iso-bg-lamppost.svg",
    kind: "exterior",
    col: 12,
    row: 5,
    anchorMode: "iso-bottom",
    width: 48,
    height: 180,
    zIndex: 10,
    opacity: 0.82,
    scale: 0.88,
    svgMeta: {
      svgAnchorX: 24,
      svgAnchorY: 180,
      viewBox: [0, 0, 48, 180],
    },
    tags: ["lamppost", "sidewalk", "side-street"],
  },
  {
    id: "scenery/side-lamp-lower",
    assetId: "background/iso-bg-lamppost",
    assetUrl: "/data/svg-environments/hq/bodega/parts/background/iso-bg-lamppost.svg",
    kind: "exterior",
    col: 12,
    row: 13,
    anchorMode: "iso-bottom",
    width: 48,
    height: 180,
    zIndex: 10,
    opacity: 0.82,
    scale: 0.88,
    svgMeta: {
      svgAnchorX: 24,
      svgAnchorY: 180,
      viewBox: [0, 0, 48, 180],
    },
    tags: ["lamppost", "sidewalk", "side-street"],
  },
  {
    id: "scenery/side-tree",
    assetId: "background/iso-bg-tree-street",
    assetUrl: "/data/svg-environments/hq/bodega/parts/background/iso-bg-tree-street.svg",
    kind: "exterior",
    col: 12.5,
    row: 9,
    anchorMode: "iso-bottom",
    width: 60,
    height: 100,
    zIndex: 9,
    opacity: 0.82,
    scale: 1.8,
    svgMeta: {
      svgAnchorX: 30,
      svgAnchorY: 100,
      viewBox: [0, 0, 60, 100],
    },
    tags: ["tree", "sidewalk", "side-street"],
  },
  {
    id: "scenery/side-hydrant",
    assetId: "background/iso-bg-hydrant",
    assetUrl: "/data/svg-environments/hq/bodega/parts/background/iso-bg-hydrant.svg",
    kind: "exterior",
    col: 12,
    row: 3,
    anchorMode: "iso-bottom",
    width: 40,
    height: 56,
    zIndex: 9,
    opacity: 1,
    scale: 1,
    svgMeta: {
      svgAnchorX: 20,
      svgAnchorY: 56,
      viewBox: [0, 0, 40, 56],
    },
    tags: ["hydrant", "sidewalk", "side-street"],
  },
  {
    id: "scenery/side-trash-can",
    assetId: "background/iso-bg-trash-can-wire",
    assetUrl: "/data/svg-environments/hq/bodega/parts/background/iso-bg-trash-can-wire.svg",
    kind: "exterior",
    col: 12,
    row: 16,
    anchorMode: "iso-bottom",
    width: 36,
    height: 56,
    zIndex: 9,
    opacity: 1,
    scale: 1,
    svgMeta: {
      svgAnchorX: 18,
      svgAnchorY: 52,
      viewBox: [0, 0, 36, 56],
    },
    tags: ["trash-can", "sidewalk", "side-street"],
  },
  {
    id: "scenery/main-far-tree",
    assetId: "background/iso-bg-tree-street",
    assetUrl: "/data/svg-environments/hq/bodega/parts/background/iso-bg-tree-street.svg",
    kind: "exterior",
    col: -16,
    row: 20.5,
    anchorMode: "iso-bottom",
    width: 60,
    height: 100,
    zIndex: 9,
    opacity: 0.7,
    scale: 1.8,
    svgMeta: {
      svgAnchorX: 30,
      svgAnchorY: 100,
      viewBox: [0, 0, 60, 100],
    },
    tags: ["tree", "sidewalk", "main-street", "far"],
  },
  {
    id: "scenery/main-far-lamp",
    assetId: "background/iso-bg-lamppost",
    assetUrl: "/data/svg-environments/hq/bodega/parts/background/iso-bg-lamppost.svg",
    kind: "exterior",
    col: -11.5,
    row: 20,
    anchorMode: "iso-bottom",
    width: 48,
    height: 180,
    zIndex: 10,
    opacity: 0.7,
    scale: 0.88,
    svgMeta: {
      svgAnchorX: 24,
      svgAnchorY: 180,
      viewBox: [0, 0, 48, 180],
    },
    tags: ["lamppost", "sidewalk", "main-street", "far"],
  },
  {
    id: "placement/background-iso-bg-building-tall-2",
    assetId: "background/iso-bg-building-tall",
    assetUrl: "/data/svg-environments/hq/bodega/parts/background/iso-bg-building-tall.svg",
    kind: "exterior",
    col: -2,
    row: 19.5,
    anchorMode: "iso-bottom",
    width: 760,
    height: 905,
    zIndex: 2,
    opacity: 1,
    scale: 1,
    svgMeta: {
      svgAnchorX: 380,
      svgAnchorY: 750,
      viewBox: [0, -155, 760, 905],
    },
  },
  {
    id: "placement/background-iso-bg-walk-up-4",
    assetId: "background/iso-bg-walk-up",
    assetUrl: "/data/svg-environments/hq/bodega/parts/background/iso-bg-walk-up.svg",
    kind: "exterior",
    col: 0,
    row: 18.5,
    anchorMode: "iso-bottom",
    width: 330,
    height: 375,
    zIndex: 2,
    opacity: 1,
    scale: 1,
    svgMeta: {
      svgAnchorX: 155,
      svgAnchorY: 395,
      viewBox: [-10, 20, 330, 375],
    },
  },
  {
    id: "placement/background-iso-bg-garden-6",
    assetId: "background/iso-bg-garden",
    assetUrl: "/data/svg-environments/hq/bodega/parts/background/iso-bg-garden.svg",
    kind: "exterior",
    col: 3,
    row: 18.5,
    anchorMode: "iso-bottom",
    width: 300,
    height: 220,
    zIndex: 0,
    opacity: 1,
    scale: 2,
    svgMeta: {
      svgAnchorX: 150,
      svgAnchorY: 220,
      viewBox: [0, 0, 300, 220],
    },
  },
  {
    id: "placement/background-iso-bg-building-tall-8",
    assetId: "background/iso-bg-building-tall",
    assetUrl: "/data/svg-environments/hq/bodega/parts/background/iso-bg-building-tall.svg",
    kind: "exterior",
    col: -9.5,
    row: 19.5,
    anchorMode: "iso-bottom",
    width: 760,
    height: 905,
    zIndex: 0,
    opacity: 1,
    scale: 1,
    svgMeta: {
      svgAnchorX: 380,
      svgAnchorY: 750,
      viewBox: [0, -155, 760, 905],
    },
  },
  {
    id: "placement/background-iso-bg-walk-up-right-10",
    assetId: "background/iso-bg-walk-up-right",
    assetUrl: "/data/svg-environments/hq/bodega/parts/background/iso-bg-walk-up-right.svg",
    kind: "exterior",
    col: 10.5,
    row: 39,
    anchorMode: "iso-bottom",
    width: 330,
    height: 375,
    zIndex: 2,
    opacity: 1,
    scale: 1,
    svgMeta: {
      svgAnchorX: 155,
      svgAnchorY: 395,
      viewBox: [-10, 20, 330, 375],
    },
  },
  {
    id: "placement/background-iso-bg-building-tall-right-12",
    assetId: "background/iso-bg-building-tall-right",
    assetUrl: "/data/svg-environments/hq/bodega/parts/background/iso-bg-building-tall-right.svg",
    kind: "exterior",
    col: 7.5,
    row: 44.5,
    anchorMode: "iso-bottom",
    width: 760,
    height: 905,
    zIndex: 1,
    opacity: 1,
    scale: 1,
    svgMeta: {
      svgAnchorX: 380,
      svgAnchorY: 750,
      viewBox: [0, -155, 760, 905],
    },
  },
  {
    id: "placement/background-iso-bg-lowrise-14",
    assetId: "background/iso-bg-lowrise",
    assetUrl: "/data/svg-environments/hq/bodega/parts/background/iso-bg-lowrise.svg",
    kind: "exterior",
    col: 0,
    row: 0,
    anchorMode: "iso-bottom",
    width: 340,
    height: 280,
    zIndex: 0,
    opacity: 1,
    scale: 1,
    svgMeta: {
      svgAnchorX: 170,
      svgAnchorY: 280,
      viewBox: [0, 0, 340, 280],
    },
  },
  {
    id: "placement/background-iso-bg-highrise-16",
    assetId: "background/iso-bg-highrise",
    assetUrl: "/data/svg-environments/hq/bodega/parts/background/iso-bg-highrise.svg",
    kind: "exterior",
    col: 0.5,
    row: 4,
    anchorMode: "iso-bottom",
    width: 480,
    height: 780,
    zIndex: 2,
    opacity: 1,
    scale: 1,
    svgMeta: {
      svgAnchorX: 240,
      svgAnchorY: 700,
      viewBox: [0, -80, 480, 780],
    },
  },
  {
    id: "placement/background-iso-bg-highrise-18",
    assetId: "background/iso-bg-highrise",
    assetUrl: "/data/svg-environments/hq/bodega/parts/background/iso-bg-highrise.svg",
    kind: "exterior",
    col: 32,
    row: 18,
    anchorMode: "iso-bottom",
    width: 480,
    height: 780,
    zIndex: 2,
    opacity: 1,
    scale: 1,
    svgMeta: {
      svgAnchorX: 240,
      svgAnchorY: 700,
      viewBox: [0, -80, 480, 780],
    },
  },
  {
    id: "placement/background-iso-bg-walk-up-right-20",
    assetId: "background/iso-bg-walk-up-right",
    assetUrl: "/data/svg-environments/hq/bodega/parts/background/iso-bg-walk-up-right.svg",
    kind: "exterior",
    col: 31,
    row: 13,
    anchorMode: "iso-bottom",
    width: 330,
    height: 375,
    zIndex: 0,
    opacity: 1,
    scale: 1,
    svgMeta: {
      svgAnchorX: 155,
      svgAnchorY: 395,
      viewBox: [-10, 20, 330, 375],
    },
  },
  {
    id: "placement/background-iso-bg-building-tall-right-22",
    assetId: "background/iso-bg-building-tall-right",
    assetUrl: "/data/svg-environments/hq/bodega/parts/background/iso-bg-building-tall-right.svg",
    kind: "exterior",
    col: -2,
    row: 44.5,
    anchorMode: "iso-bottom",
    width: 760,
    height: 905,
    zIndex: 0,
    opacity: 1,
    scale: 1,
    svgMeta: {
      svgAnchorX: 380,
      svgAnchorY: 750,
      viewBox: [0, -155, 760, 905],
    },
  },
  {
    id: "placement/background-iso-bg-tenement-left-24",
    assetId: "background/iso-bg-tenement-left",
    assetUrl: "/data/svg-environments/hq/bodega/parts/background/iso-bg-tenement-left.svg",
    kind: "exterior",
    col: 30.5,
    row: 7,
    anchorMode: "iso-bottom",
    width: 280,
    height: 480,
    zIndex: 0,
    opacity: 1,
    scale: 1,
    svgMeta: {
      svgAnchorX: 140,
      svgAnchorY: 480,
      viewBox: [0, 0, 280, 480],
    },
  },
  {
    id: "placement/background-iso-bg-tenement-right-26",
    assetId: "background/iso-bg-tenement-right",
    assetUrl: "/data/svg-environments/hq/bodega/parts/background/iso-bg-tenement-right.svg",
    kind: "exterior",
    col: -4,
    row: 8,
    anchorMode: "iso-bottom",
    width: 280,
    height: 480,
    zIndex: 0,
    opacity: 1,
    scale: 1,
    svgMeta: {
      svgAnchorX: 140,
      svgAnchorY: 480,
      viewBox: [0, 0, 280, 480],
    },
  },
  {
    id: "placement/background-iso-bg-trash-can-wire-30",
    assetId: "background/iso-bg-trash-can-wire",
    assetUrl: "/data/svg-environments/hq/bodega/parts/background/iso-bg-trash-can-wire.svg",
    kind: "exterior",
    col: 28,
    row: 6.5,
    anchorMode: "iso-bottom",
    width: 36,
    height: 56,
    zIndex: 2,
    opacity: 1,
    scale: 1,
    svgMeta: {
      svgAnchorX: 18,
      svgAnchorY: 56,
      viewBox: [0, 0, 36, 56],
    },
  },
];

const BODEGA_EXTERIOR_SCENE: HqSceneComposition = {
  buildingId: "building/bodega",
  sceneId: "bodega-exterior",
  placements: BODEGA_EXTERIOR_PLACEMENTS,
};

// ── Scene lookup ─────────────────────────────────────────────────────────

const EXTERIOR_SCENES: Readonly<Record<string, HqSceneComposition>> = {
  "building/bodega": BODEGA_EXTERIOR_SCENE,
};

/** Return the exterior scene composition for a building, or undefined if none exists. */
export function getExteriorScene(buildingId: string): HqSceneComposition | undefined {
  return EXTERIOR_SCENES[buildingId];
}
