/**
 * HQ static scene composition data.
 *
 * Each building owns one exterior scene composition expressed as grid-anchored
 * placements. All positions use isometric col/row coordinates — no raw screen
 * x/y. The projection function in hq-world.ts converts these to screen-space
 * HqSpritePlacement records at composition time.
 *
 * Placement contract:
 * - Every placement specifies `svgMeta` with the asset's viewBox and an anchor
 *   point in SVG user-space.  The renderer derives screen dimensions from
 *   `viewBox × scale` and maps the SVG anchor to the grid point (col, row).
 * - `width`/`height` mirror the viewBox dimensions for documentation only.
 * - `scale` adjusts visual size relative to the grid (1.0 = SVG natural size).
 * - `offsetX`/`offsetY` are small fine-tuning corrections, not the primary contract.
 * - `footprintCols`/`footprintRows` are builder metadata (not used by renderer).
 */

import { resolveHqEnvironmentAssetUrl } from "lib/svg-asset-contract";

import type { HqSceneComposition, HqStaticPlacementDef } from "./types";

// Exported from the scene builder. Keep this composition aligned with the
// canonical builder output rather than hand-tuning it here.

const BODEGA_EXTERIOR_PLACEMENTS: readonly HqStaticPlacementDef[] = [
  {
    id: "scenery/back-alley",
    assetId: "background/iso-bg-back-alley",
    assetUrl: "/data/svg-environments/hq/bodega/parts/background/iso-bg-back-alley.svg",
    kind: "exterior",
    col: 0,
    row: 10,
    anchorMode: "iso-bottom",
    width: 600,
    height: 310,
    zIndex: 2,
    opacity: 1,
    scale: 1,
    svgMeta: {
      svgAnchorX: 300,
      svgAnchorY: 310,
      viewBox: [0, 0, 600, 310],
    },
    tags: ["alley", "behind"],
  },
  {
    id: "scenery/trash-bags",
    assetId: "background/iso-bg-trash-bags",
    assetUrl: "/data/svg-environments/hq/bodega/parts/background/iso-bg-trash-bags.svg",
    kind: "exterior",
    col: -5.5,
    row: 4.5,
    anchorMode: "iso-bottom",
    width: 64,
    height: 44,
    zIndex: 2,
    opacity: 1,
    scale: 1,
    svgMeta: {
      svgAnchorX: 32,
      svgAnchorY: 44,
      viewBox: [0, 0, 64, 44],
    },
    tags: ["trash", "behind"],
  },
  {
    id: "scenery/main-tree-left",
    assetId: "background/iso-bg-tree-street",
    assetUrl: "/data/svg-environments/hq/bodega/parts/background/iso-bg-tree-street.svg",
    kind: "exterior",
    col: -7,
    row: 20,
    anchorMode: "iso-bottom",
    width: 60,
    height: 100,
    zIndex: 9,
    opacity: 0.82,
    scale: 2,
    svgMeta: {
      svgAnchorX: 30,
      svgAnchorY: 100,
      viewBox: [0, 0, 60, 100],
    },
    tags: ["tree", "sidewalk", "main-street"],
  },
  {
    id: "scenery/main-lamp-left",
    assetId: "background/iso-bg-lamppost",
    assetUrl: "/data/svg-environments/hq/bodega/parts/background/iso-bg-lamppost.svg",
    kind: "exterior",
    col: -3,
    row: 20,
    anchorMode: "iso-bottom",
    width: 48,
    height: 180,
    zIndex: 10,
    opacity: 0.82,
    scale: 0.88,
    svgMeta: {
      svgAnchorX: 24,
      svgAnchorY: 180,
      viewBox: [0, 0, 48, 180],
    },
    tags: ["lamppost", "sidewalk", "main-street"],
  },
  {
    id: "scenery/main-lamp-center",
    assetId: "background/iso-bg-lamppost",
    assetUrl: "/data/svg-environments/hq/bodega/parts/background/iso-bg-lamppost.svg",
    kind: "exterior",
    col: 5,
    row: 20,
    anchorMode: "iso-bottom",
    width: 48,
    height: 180,
    zIndex: 10,
    opacity: 0.82,
    scale: 0.88,
    svgMeta: {
      svgAnchorX: 24,
      svgAnchorY: 180,
      viewBox: [0, 0, 48, 180],
    },
    tags: ["lamppost", "sidewalk", "main-street"],
  },
  {
    id: "scenery/main-bench",
    assetId: "background/iso-bg-bench",
    assetUrl: "/data/svg-environments/hq/bodega/parts/background/iso-bg-bench.svg",
    kind: "exterior",
    col: 1,
    row: 20,
    anchorMode: "iso-bottom",
    width: 72,
    height: 58,
    zIndex: 9,
    opacity: 1,
    scale: 1,
    svgMeta: {
      svgAnchorX: 36,
      svgAnchorY: 58,
      viewBox: [0, 0, 72, 58],
    },
    tags: ["bench", "sidewalk", "main-street"],
  },
  {
    id: "scenery/main-mailbox",
    assetId: "background/iso-bg-mailbox",
    assetUrl: "/data/svg-environments/hq/bodega/parts/background/iso-bg-mailbox.svg",
    kind: "exterior",
    col: 3.5,
    row: 20,
    anchorMode: "iso-bottom",
    width: 36,
    height: 52,
    zIndex: 9,
    opacity: 1,
    scale: 1,
    svgMeta: {
      svgAnchorX: 18,
      svgAnchorY: 52,
      viewBox: [0, 0, 36, 52],
    },
    tags: ["mailbox", "sidewalk", "main-street"],
  },
  {
    id: "scenery/main-trash-can",
    assetId: "background/iso-bg-trash-can-wire",
    assetUrl: "/data/svg-environments/hq/bodega/parts/background/iso-bg-trash-can-wire.svg",
    kind: "exterior",
    col: 7,
    row: 20,
    anchorMode: "iso-bottom",
    width: 36,
    height: 56,
    zIndex: 9,
    opacity: 1,
    scale: 1,
    svgMeta: {
      svgAnchorX: 18,
      svgAnchorY: 52,
      viewBox: [0, 0, 36, 56],
    },
    tags: ["trash-can", "sidewalk", "main-street"],
  },
  {
    id: "scenery/main-hydrant",
    assetId: "background/iso-bg-hydrant",
    assetUrl: "/data/svg-environments/hq/bodega/parts/background/iso-bg-hydrant.svg",
    kind: "exterior",
    col: 9.5,
    row: 20,
    anchorMode: "iso-bottom",
    width: 40,
    height: 56,
    zIndex: 9,
    opacity: 1,
    scale: 1,
    svgMeta: {
      svgAnchorX: 20,
      svgAnchorY: 56,
      viewBox: [0, 0, 40, 56],
    },
    tags: ["hydrant", "sidewalk", "main-street"],
  },
  {
    id: "scenery/traffic-light-nw",
    assetId: "background/iso-bg-traffic-light",
    assetUrl: "/data/svg-environments/hq/bodega/parts/background/iso-bg-traffic-light.svg",
    kind: "exterior",
    col: 13,
    row: 21.5,
    anchorMode: "iso-bottom",
    width: 64,
    height: 210,
    zIndex: 11,
    opacity: 0.9,
    scale: 0.9,
    svgMeta: {
      svgAnchorX: 24,
      svgAnchorY: 205,
      viewBox: [0, 0, 64, 210],
    },
    tags: ["traffic-light", "intersection", "nw-corner"],
  },
  {
    id: "scenery/traffic-light-sw",
    assetId: "background/iso-bg-traffic-light",
    assetUrl: "/data/svg-environments/hq/bodega/parts/background/iso-bg-traffic-light.svg",
    kind: "exterior",
    col: 13,
    row: 33,
    anchorMode: "iso-bottom",
    width: 64,
    height: 210,
    zIndex: 11,
    opacity: 0.75,
    scale: 0.9,
    svgMeta: {
      svgAnchorX: 24,
      svgAnchorY: 205,
      viewBox: [0, 0, 64, 210],
    },
    tags: ["traffic-light", "intersection", "sw-corner"],
  },
  {
    id: "scenery/traffic-light-ne",
    assetId: "background/iso-bg-traffic-light",
    assetUrl: "/data/svg-environments/hq/bodega/parts/background/iso-bg-traffic-light.svg",
    kind: "exterior",
    col: 25,
    row: 21,
    anchorMode: "iso-bottom",
    width: 64,
    height: 210,
    zIndex: 11,
    opacity: 0.75,
    scale: 0.9,
    svgMeta: {
      svgAnchorX: 24,
      svgAnchorY: 205,
      viewBox: [0, 0, 64, 210],
    },
    tags: ["traffic-light", "intersection", "ne-corner"],
  },
  {
    id: "scenery/traffic-light-se",
    assetId: "background/iso-bg-traffic-light",
    assetUrl: "/data/svg-environments/hq/bodega/parts/background/iso-bg-traffic-light.svg",
    kind: "exterior",
    col: 25,
    row: 33,
    anchorMode: "iso-bottom",
    width: 64,
    height: 210,
    zIndex: 11,
    opacity: 0.6,
    scale: 0.9,
    svgMeta: {
      svgAnchorX: 24,
      svgAnchorY: 205,
      viewBox: [0, 0, 64, 210],
    },
    tags: ["traffic-light", "intersection", "se-corner"],
  },
  {
    id: "scenery/intersection-street-sign",
    assetId: "background/iso-bg-street-sign",
    assetUrl: "/data/svg-environments/hq/bodega/parts/background/iso-bg-street-sign.svg",
    kind: "exterior",
    col: 13,
    row: 20,
    anchorMode: "iso-bottom",
    width: 56,
    height: 185,
    zIndex: 10,
    opacity: 0.85,
    scale: 0.85,
    svgMeta: {
      svgAnchorX: 20,
      svgAnchorY: 180,
      viewBox: [0, 0, 56, 185],
    },
    tags: ["street-sign", "intersection"],
  },
  {
    id: "scenery/side-lamp-upper",
    assetId: "background/iso-bg-lamppost",
    assetUrl: "/data/svg-environments/hq/bodega/parts/background/iso-bg-lamppost.svg",
    kind: "exterior",
    col: 12,
    row: 5,
    anchorMode: "iso-bottom",
    width: 48,
    height: 180,
    zIndex: 10,
    opacity: 0.82,
    scale: 0.88,
    svgMeta: {
      svgAnchorX: 24,
      svgAnchorY: 180,
      viewBox: [0, 0, 48, 180],
    },
    tags: ["lamppost", "sidewalk", "side-street"],
  },
  {
    id: "scenery/side-lamp-lower",
    assetId: "background/iso-bg-lamppost",
    assetUrl: "/data/svg-environments/hq/bodega/parts/background/iso-bg-lamppost.svg",
    kind: "exterior",
    col: 12,
    row: 13,
    anchorMode: "iso-bottom",
    width: 48,
    height: 180,
    zIndex: 10,
    opacity: 0.82,
    scale: 0.88,
    svgMeta: {
      svgAnchorX: 24,
      svgAnchorY: 180,
      viewBox: [0, 0, 48, 180],
    },
    tags: ["lamppost", "sidewalk", "side-street"],
  },
  {
    id: "scenery/side-tree",
    assetId: "background/iso-bg-tree-street",
    assetUrl: "/data/svg-environments/hq/bodega/parts/background/iso-bg-tree-street.svg",
    kind: "exterior",
    col: 12.5,
    row: 9,
    anchorMode: "iso-bottom",
    width: 60,
    height: 100,
    zIndex: 9,
    opacity: 0.82,
    scale: 1.8,
    svgMeta: {
      svgAnchorX: 30,
      svgAnchorY: 100,
      viewBox: [0, 0, 60, 100],
    },
    tags: ["tree", "sidewalk", "side-street"],
  },
  {
    id: "scenery/side-hydrant",
    assetId: "background/iso-bg-hydrant",
    assetUrl: "/data/svg-environments/hq/bodega/parts/background/iso-bg-hydrant.svg",
    kind: "exterior",
    col: 12,
    row: 3,
    anchorMode: "iso-bottom",
    width: 40,
    height: 56,
    zIndex: 9,
    opacity: 1,
    scale: 1,
    svgMeta: {
      svgAnchorX: 20,
      svgAnchorY: 56,
      viewBox: [0, 0, 40, 56],
    },
    tags: ["hydrant", "sidewalk", "side-street"],
  },
  {
    id: "scenery/side-trash-can",
    assetId: "background/iso-bg-trash-can-wire",
    assetUrl: "/data/svg-environments/hq/bodega/parts/background/iso-bg-trash-can-wire.svg",
    kind: "exterior",
    col: 12,
    row: 16,
    anchorMode: "iso-bottom",
    width: 36,
    height: 56,
    zIndex: 9,
    opacity: 1,
    scale: 1,
    svgMeta: {
      svgAnchorX: 18,
      svgAnchorY: 52,
      viewBox: [0, 0, 36, 56],
    },
    tags: ["trash-can", "sidewalk", "side-street"],
  },
  {
    id: "scenery/main-far-tree",
    assetId: "background/iso-bg-tree-street",
    assetUrl: "/data/svg-environments/hq/bodega/parts/background/iso-bg-tree-street.svg",
    kind: "exterior",
    col: -16,
    row: 20.5,
    anchorMode: "iso-bottom",
    width: 60,
    height: 100,
    zIndex: 9,
    opacity: 0.7,
    scale: 1.8,
    svgMeta: {
      svgAnchorX: 30,
      svgAnchorY: 100,
      viewBox: [0, 0, 60, 100],
    },
    tags: ["tree", "sidewalk", "main-street", "far"],
  },
  {
    id: "scenery/main-far-lamp",
    assetId: "background/iso-bg-lamppost",
    assetUrl: "/data/svg-environments/hq/bodega/parts/background/iso-bg-lamppost.svg",
    kind: "exterior",
    col: -11.5,
    row: 20,
    anchorMode: "iso-bottom",
    width: 48,
    height: 180,
    zIndex: 10,
    opacity: 0.7,
    scale: 0.88,
    svgMeta: {
      svgAnchorX: 24,
      svgAnchorY: 180,
      viewBox: [0, 0, 48, 180],
    },
    tags: ["lamppost", "sidewalk", "main-street", "far"],
  },
  {
    id: "placement/background-iso-bg-building-tall-2",
    assetId: "background/iso-bg-building-tall",
    assetUrl: "/data/svg-environments/hq/bodega/parts/background/iso-bg-building-tall.svg",
    kind: "exterior",
    col: -2,
    row: 19.5,
    anchorMode: "iso-bottom",
    width: 760,
    height: 905,
    zIndex: 2,
    opacity: 1,
    scale: 1,
    svgMeta: {
      svgAnchorX: 380,
      svgAnchorY: 750,
      viewBox: [0, -155, 760, 905],
    },
  },
  {
    id: "placement/background-iso-bg-walk-up-4",
    assetId: "background/iso-bg-walk-up",
    assetUrl: "/data/svg-environments/hq/bodega/parts/background/iso-bg-walk-up.svg",
    kind: "exterior",
    col: 0,
    row: 18.5,
    anchorMode: "iso-bottom",
    width: 330,
    height: 375,
    zIndex: 2,
    opacity: 1,
    scale: 1,
    svgMeta: {
      svgAnchorX: 155,
      svgAnchorY: 395,
      viewBox: [-10, 20, 330, 375],
    },
  },
  {
    id: "placement/background-iso-bg-garden-6",
    assetId: "background/iso-bg-garden",
    assetUrl: "/data/svg-environments/hq/bodega/parts/background/iso-bg-garden.svg",
    kind: "exterior",
    col: 3,
    row: 18.5,
    anchorMode: "iso-bottom",
    width: 300,
    height: 220,
    zIndex: 0,
    opacity: 1,
    scale: 2,
    svgMeta: {
      svgAnchorX: 150,
      svgAnchorY: 220,
      viewBox: [0, 0, 300, 220],
    },
  },
  {
    id: "placement/background-iso-bg-building-tall-8",
    assetId: "background/iso-bg-building-tall",
    assetUrl: "/data/svg-environments/hq/bodega/parts/background/iso-bg-building-tall.svg",
    kind: "exterior",
    col: -9.5,
    row: 19.5,
    anchorMode: "iso-bottom",
    width: 760,
    height: 905,
    zIndex: 0,
    opacity: 1,
    scale: 1,
    svgMeta: {
      svgAnchorX: 380,
      svgAnchorY: 750,
      viewBox: [0, -155, 760, 905],
    },
  },
  {
    id: "placement/background-iso-bg-walk-up-right-10",
    assetId: "background/iso-bg-walk-up-right",
    assetUrl: "/data/svg-environments/hq/bodega/parts/background/iso-bg-walk-up-right.svg",
    kind: "exterior",
    col: 10.5,
    row: 39,
    anchorMode: "iso-bottom",
    width: 330,
    height: 375,
    zIndex: 2,
    opacity: 1,
    scale: 1,
    svgMeta: {
      svgAnchorX: 155,
      svgAnchorY: 395,
      viewBox: [-10, 20, 330, 375],
    },
  },
  {
    id: "placement/background-iso-bg-building-tall-right-12",
    assetId: "background/iso-bg-building-tall-right",
    assetUrl: "/data/svg-environments/hq/bodega/parts/background/iso-bg-building-tall-right.svg",
    kind: "exterior",
    col: 7.5,
    row: 44.5,
    anchorMode: "iso-bottom",
    width: 760,
    height: 905,
    zIndex: 1,
    opacity: 1,
    scale: 1,
    svgMeta: {
      svgAnchorX: 380,
      svgAnchorY: 750,
      viewBox: [0, -155, 760, 905],
    },
  },
  {
    id: "placement/background-iso-bg-lowrise-14",
    assetId: "background/iso-bg-lowrise",
    assetUrl: "/data/svg-environments/hq/bodega/parts/background/iso-bg-lowrise.svg",
    kind: "exterior",
    col: 0,
    row: 0,
    anchorMode: "iso-bottom",
    width: 340,
    height: 280,
    zIndex: 0,
    opacity: 1,
    scale: 1,
    svgMeta: {
      svgAnchorX: 170,
      svgAnchorY: 280,
      viewBox: [0, 0, 340, 280],
    },
  },
  {
    id: "placement/background-iso-bg-highrise-16",
    assetId: "background/iso-bg-highrise",
    assetUrl: "/data/svg-environments/hq/bodega/parts/background/iso-bg-highrise.svg",
    kind: "exterior",
    col: 0.5,
    row: 4,
    anchorMode: "iso-bottom",
    width: 480,
    height: 780,
    zIndex: 2,
    opacity: 1,
    scale: 1,
    svgMeta: {
      svgAnchorX: 240,
      svgAnchorY: 700,
      viewBox: [0, -80, 480, 780],
    },
  },
  {
    id: "placement/background-iso-bg-highrise-18",
    assetId: "background/iso-bg-highrise",
    assetUrl: "/data/svg-environments/hq/bodega/parts/background/iso-bg-highrise.svg",
    kind: "exterior",
    col: 32,
    row: 18,
    anchorMode: "iso-bottom",
    width: 480,
    height: 780,
    zIndex: 2,
    opacity: 1,
    scale: 1,
    svgMeta: {
      svgAnchorX: 240,
      svgAnchorY: 700,
      viewBox: [0, -80, 480, 780],
    },
  },
  {
    id: "placement/background-iso-bg-walk-up-right-20",
    assetId: "background/iso-bg-walk-up-right",
    assetUrl: "/data/svg-environments/hq/bodega/parts/background/iso-bg-walk-up-right.svg",
    kind: "exterior",
    col: 31,
    row: 13,
    anchorMode: "iso-bottom",
    width: 330,
    height: 375,
    zIndex: 0,
    opacity: 1,
    scale: 1,
    svgMeta: {
      svgAnchorX: 155,
      svgAnchorY: 395,
      viewBox: [-10, 20, 330, 375],
    },
  },
  {
    id: "placement/background-iso-bg-building-tall-right-22",
    assetId: "background/iso-bg-building-tall-right",
    assetUrl: "/data/svg-environments/hq/bodega/parts/background/iso-bg-building-tall-right.svg",
    kind: "exterior",
    col: -2,
    row: 44.5,
    anchorMode: "iso-bottom",
    width: 760,
    height: 905,
    zIndex: 0,
    opacity: 1,
    scale: 1,
    svgMeta: {
      svgAnchorX: 380,
      svgAnchorY: 750,
      viewBox: [0, -155, 760, 905],
    },
  },
  {
    id: "placement/background-iso-bg-tenement-left-24",
    assetId: "background/iso-bg-tenement-left",
    assetUrl: "/data/svg-environments/hq/bodega/parts/background/iso-bg-tenement-left.svg",
    kind: "exterior",
    col: 30.5,
    row: 7,
    anchorMode: "iso-bottom",
    width: 280,
    height: 480,
    zIndex: 0,
    opacity: 1,
    scale: 1,
    svgMeta: {
      svgAnchorX: 140,
      svgAnchorY: 480,
      viewBox: [0, 0, 280, 480],
    },
  },
  {
    id: "placement/background-iso-bg-tenement-right-26",
    assetId: "background/iso-bg-tenement-right",
    assetUrl: "/data/svg-environments/hq/bodega/parts/background/iso-bg-tenement-right.svg",
    kind: "exterior",
    col: -4,
    row: 8,
    anchorMode: "iso-bottom",
    width: 280,
    height: 480,
    zIndex: 0,
    opacity: 1,
    scale: 1,
    svgMeta: {
      svgAnchorX: 140,
      svgAnchorY: 480,
      viewBox: [0, 0, 280, 480],
    },
  },
  {
    id: "placement/background-iso-bg-trash-can-wire-30",
    assetId: "background/iso-bg-trash-can-wire",
    assetUrl: "/data/svg-environments/hq/bodega/parts/background/iso-bg-trash-can-wire.svg",
    kind: "exterior",
    col: 28,
    row: 6.5,
    anchorMode: "iso-bottom",
    width: 36,
    height: 56,
    zIndex: 2,
    opacity: 1,
    scale: 1,
    svgMeta: {
      svgAnchorX: 18,
      svgAnchorY: 56,
      viewBox: [0, 0, 36, 56],
    },
  },
];

const BODEGA_EXTERIOR_SCENE: HqSceneComposition = {
  buildingId: "building/bodega",
  sceneId: "bodega-exterior",
  placements: BODEGA_EXTERIOR_PLACEMENTS,
};

const PORTERS_EXTERIOR_PLACEMENTS: readonly HqStaticPlacementDef[] = [
  {
    id: "placement/background-iso-bg-warehouse-2",
    assetId: "background/iso-bg-warehouse",
    assetUrl: "/data/svg-environments/hq/bodega/parts/background/iso-bg-warehouse.svg",
    kind: "exterior",
    col: 0,
    row: 18,
    anchorMode: "iso-bottom",
    width: 500,
    height: 410,
    zIndex: 2,
    opacity: 1,
    scale: 1,
    svgMeta: {
      svgAnchorX: 240,
      svgAnchorY: 420,
      viewBox: [-10, 10, 500, 410],
    },
  },
  {
    id: "placement/background-iso-bg-warehouse-arched-6",
    assetId: "background/iso-bg-warehouse-arched",
    assetUrl: "/data/svg-environments/hq/bodega/parts/background/iso-bg-warehouse-arched.svg",
    kind: "exterior",
    col: -4,
    row: 18,
    anchorMode: "iso-bottom",
    width: 400,
    height: 540,
    zIndex: 1,
    opacity: 1,
    scale: 1,
    svgMeta: {
      svgAnchorX: 240,
      svgAnchorY: 560,
      viewBox: [40, 20, 400, 540],
    },
  },
  {
    id: "placement/background-iso-bg-mooring-bollard-8",
    assetId: "background/iso-bg-mooring-bollard",
    assetUrl: "/data/svg-environments/hq/bodega/parts/background/iso-bg-mooring-bollard.svg",
    kind: "exterior",
    col: 1,
    row: -3.5,
    anchorMode: "iso-bottom",
    width: 44,
    height: 52,
    zIndex: 2,
    opacity: 1,
    scale: 1,
    svgMeta: {
      svgAnchorX: 22,
      svgAnchorY: 52,
      viewBox: [0, 0, 44, 52],
    },
  },
  {
    id: "placement/background-iso-bg-mooring-bollard-10",
    assetId: "background/iso-bg-mooring-bollard",
    assetUrl: "/data/svg-environments/hq/bodega/parts/background/iso-bg-mooring-bollard.svg",
    kind: "exterior",
    col: 4,
    row: -3.5,
    anchorMode: "iso-bottom",
    width: 44,
    height: 52,
    zIndex: 2,
    opacity: 1,
    scale: 1,
    svgMeta: {
      svgAnchorX: 22,
      svgAnchorY: 52,
      viewBox: [0, 0, 44, 52],
    },
  },
  {
    id: "placement/background-iso-bg-container-12",
    assetId: "background/iso-bg-container",
    assetUrl: "/data/svg-environments/hq/bodega/parts/background/iso-bg-container.svg",
    kind: "exterior",
    col: 15,
    row: 1.5,
    anchorMode: "iso-bottom",
    width: 150,
    height: 115,
    zIndex: 2,
    opacity: 1,
    scale: 1,
    svgMeta: {
      svgAnchorX: 75,
      svgAnchorY: 110,
      viewBox: [0, -5, 150, 115],
    },
  },
  {
    id: "placement/background-iso-bg-container-14",
    assetId: "background/iso-bg-container",
    assetUrl: "/data/svg-environments/hq/bodega/parts/background/iso-bg-container.svg",
    kind: "exterior",
    col: 17.5,
    row: 1.5,
    anchorMode: "iso-bottom",
    width: 150,
    height: 115,
    zIndex: 2,
    opacity: 1,
    scale: 1,
    svgMeta: {
      svgAnchorX: 75,
      svgAnchorY: 110,
      viewBox: [0, -5, 150, 115],
    },
  },
  {
    id: "placement/background-iso-bg-container-16",
    assetId: "background/iso-bg-container",
    assetUrl: "/data/svg-environments/hq/bodega/parts/background/iso-bg-container.svg",
    kind: "exterior",
    col: 15,
    row: 2.5,
    anchorMode: "iso-bottom",
    width: 150,
    height: 115,
    zIndex: 2,
    opacity: 1,
    scale: 1,
    svgMeta: {
      svgAnchorX: 75,
      svgAnchorY: 110,
      viewBox: [0, -5, 150, 115],
    },
  },
  {
    id: "placement/background-iso-bg-forklift-18",
    assetId: "background/iso-bg-forklift",
    assetUrl: "/data/svg-environments/hq/bodega/parts/background/iso-bg-forklift.svg",
    kind: "exterior",
    col: 17.5,
    row: 2.5,
    anchorMode: "iso-bottom",
    width: 130,
    height: 105,
    zIndex: 2,
    opacity: 1,
    scale: 1,
    svgMeta: {
      svgAnchorX: 65,
      svgAnchorY: 120,
      viewBox: [0, 15, 130, 105],
    },
  },
  {
    id: "placement/background-iso-bg-tugboat-20",
    assetId: "background/iso-bg-tugboat",
    assetUrl: "/data/svg-environments/hq/bodega/parts/background/iso-bg-tugboat.svg",
    kind: "exterior",
    col: 14,
    row: -4.5,
    anchorMode: "iso-bottom",
    width: 320,
    height: 200,
    zIndex: 2,
    opacity: 1,
    scale: 1,
    svgMeta: {
      svgAnchorX: 160,
      svgAnchorY: 200,
      viewBox: [0, 0, 320, 200],
    },
  },
  {
    id: "placement/background-iso-bg-boat-small-22",
    assetId: "background/iso-bg-boat-small",
    assetUrl: "/data/svg-environments/hq/bodega/parts/background/iso-bg-boat-small.svg",
    kind: "exterior",
    col: -1,
    row: -3.5,
    anchorMode: "iso-bottom",
    width: 385,
    height: 215,
    zIndex: 2,
    opacity: 1,
    scale: 1,
    svgMeta: {
      svgAnchorX: 192.5,
      svgAnchorY: 215,
      viewBox: [0, 0, 385, 215],
    },
  },
  {
    id: "placement/background-iso-bg-keg-stack-24",
    assetId: "background/iso-bg-keg-stack",
    assetUrl: "/data/svg-environments/hq/bodega/parts/background/iso-bg-keg-stack.svg",
    kind: "exterior",
    col: 5.5,
    row: -3,
    anchorMode: "iso-bottom",
    width: 80,
    height: 72,
    zIndex: 2,
    opacity: 1,
    scale: 1,
    svgMeta: {
      svgAnchorX: 40,
      svgAnchorY: 72,
      viewBox: [0, 0, 80, 72],
    },
  },
  {
    id: "placement/background-iso-bg-water-tower-28",
    assetId: "background/iso-bg-water-tower",
    assetUrl: "/data/svg-environments/hq/bodega/parts/background/iso-bg-water-tower.svg",
    kind: "exterior",
    col: -0.5,
    row: 1,
    anchorMode: "iso-bottom",
    width: 130,
    height: 200,
    zIndex: 2,
    opacity: 1,
    scale: 1,
    svgMeta: {
      svgAnchorX: 65,
      svgAnchorY: 200,
      viewBox: [0, 0, 130, 200],
    },
  },
  {
    id: "placement/background-iso-bg-building-tall-30",
    assetId: "background/iso-bg-building-tall",
    assetUrl: "/data/svg-environments/hq/bodega/parts/background/iso-bg-building-tall.svg",
    kind: "exterior",
    col: -6,
    row: 19.5,
    anchorMode: "iso-bottom",
    width: 760,
    height: 905,
    zIndex: 0,
    opacity: 1,
    scale: 1,
    svgMeta: {
      svgAnchorX: 380,
      svgAnchorY: 750,
      viewBox: [0, -155, 760, 905],
    },
  },

  // ── South main street: sidewalk in front of Porter's ────────────────
  // Mirrors the bodega main street layout (row 20, col 1-13 + far-outs).
  {
    id: "scenery/street-tree-far-left",
    assetId: "background/iso-bg-tree-street",
    assetUrl: "/data/svg-environments/hq/bodega/parts/background/iso-bg-tree-street.svg",
    kind: "exterior",
    col: -7,
    row: 20,
    anchorMode: "iso-bottom",
    width: 60,
    height: 100,
    zIndex: 9,
    opacity: 0.82,
    scale: 2,
    svgMeta: {
      svgAnchorX: 30,
      svgAnchorY: 100,
      viewBox: [0, 0, 60, 100],
    },
    tags: ["tree", "sidewalk", "main-street"],
  },
  {
    id: "scenery/street-lamp-left",
    assetId: "background/iso-bg-lamppost",
    assetUrl: "/data/svg-environments/hq/bodega/parts/background/iso-bg-lamppost.svg",
    kind: "exterior",
    col: -3,
    row: 20,
    anchorMode: "iso-bottom",
    width: 48,
    height: 180,
    zIndex: 10,
    opacity: 0.82,
    scale: 0.88,
    svgMeta: {
      svgAnchorX: 24,
      svgAnchorY: 180,
      viewBox: [0, 0, 48, 180],
    },
    tags: ["lamppost", "sidewalk", "main-street"],
  },
  {
    id: "scenery/street-bench",
    assetId: "background/iso-bg-bench",
    assetUrl: "/data/svg-environments/hq/bodega/parts/background/iso-bg-bench.svg",
    kind: "exterior",
    col: 1,
    row: 20,
    anchorMode: "iso-bottom",
    width: 72,
    height: 58,
    zIndex: 9,
    opacity: 1,
    scale: 1,
    svgMeta: {
      svgAnchorX: 36,
      svgAnchorY: 58,
      viewBox: [0, 0, 72, 58],
    },
    tags: ["bench", "sidewalk", "main-street"],
  },
  {
    id: "scenery/street-mailbox",
    assetId: "background/iso-bg-mailbox",
    assetUrl: "/data/svg-environments/hq/bodega/parts/background/iso-bg-mailbox.svg",
    kind: "exterior",
    col: 3.5,
    row: 20,
    anchorMode: "iso-bottom",
    width: 36,
    height: 52,
    zIndex: 9,
    opacity: 1,
    scale: 1,
    svgMeta: {
      svgAnchorX: 18,
      svgAnchorY: 52,
      viewBox: [0, 0, 36, 52],
    },
    tags: ["mailbox", "sidewalk", "main-street"],
  },
  {
    id: "scenery/street-lamp-center",
    assetId: "background/iso-bg-lamppost",
    assetUrl: "/data/svg-environments/hq/bodega/parts/background/iso-bg-lamppost.svg",
    kind: "exterior",
    col: 5,
    row: 20,
    anchorMode: "iso-bottom",
    width: 48,
    height: 180,
    zIndex: 10,
    opacity: 0.82,
    scale: 0.88,
    svgMeta: {
      svgAnchorX: 24,
      svgAnchorY: 180,
      viewBox: [0, 0, 48, 180],
    },
    tags: ["lamppost", "sidewalk", "main-street"],
  },
  {
    id: "scenery/street-trash-can",
    assetId: "background/iso-bg-trash-can-wire",
    assetUrl: "/data/svg-environments/hq/bodega/parts/background/iso-bg-trash-can-wire.svg",
    kind: "exterior",
    col: 7,
    row: 20,
    anchorMode: "iso-bottom",
    width: 36,
    height: 56,
    zIndex: 9,
    opacity: 1,
    scale: 1,
    svgMeta: {
      svgAnchorX: 18,
      svgAnchorY: 52,
      viewBox: [0, 0, 36, 56],
    },
    tags: ["trash-can", "sidewalk", "main-street"],
  },
  {
    id: "scenery/street-hydrant",
    assetId: "background/iso-bg-hydrant",
    assetUrl: "/data/svg-environments/hq/bodega/parts/background/iso-bg-hydrant.svg",
    kind: "exterior",
    col: 9.5,
    row: 20,
    anchorMode: "iso-bottom",
    width: 40,
    height: 56,
    zIndex: 9,
    opacity: 1,
    scale: 1,
    svgMeta: {
      svgAnchorX: 20,
      svgAnchorY: 56,
      viewBox: [0, 0, 40, 56],
    },
    tags: ["hydrant", "sidewalk", "main-street"],
  },
  {
    id: "scenery/street-far-tree",
    assetId: "background/iso-bg-tree-street",
    assetUrl: "/data/svg-environments/hq/bodega/parts/background/iso-bg-tree-street.svg",
    kind: "exterior",
    col: -16,
    row: 20.5,
    anchorMode: "iso-bottom",
    width: 60,
    height: 100,
    zIndex: 9,
    opacity: 0.7,
    scale: 1.8,
    svgMeta: {
      svgAnchorX: 30,
      svgAnchorY: 100,
      viewBox: [0, 0, 60, 100],
    },
    tags: ["tree", "sidewalk", "main-street", "far"],
  },
  {
    id: "scenery/street-far-lamp",
    assetId: "background/iso-bg-lamppost",
    assetUrl: "/data/svg-environments/hq/bodega/parts/background/iso-bg-lamppost.svg",
    kind: "exterior",
    col: -11.5,
    row: 20,
    anchorMode: "iso-bottom",
    width: 48,
    height: 180,
    zIndex: 10,
    opacity: 0.7,
    scale: 0.88,
    svgMeta: {
      svgAnchorX: 24,
      svgAnchorY: 180,
      viewBox: [0, 0, 48, 180],
    },
    tags: ["lamppost", "sidewalk", "main-street", "far"],
  },

  // ── SE intersection: traffic light corners + street sign ────────────
  {
    id: "scenery/intersection-traffic-sw",
    assetId: "background/iso-bg-traffic-light",
    assetUrl: "/data/svg-environments/hq/bodega/parts/background/iso-bg-traffic-light.svg",
    kind: "exterior",
    col: 13,
    row: 33,
    anchorMode: "iso-bottom",
    width: 64,
    height: 210,
    zIndex: 11,
    opacity: 0.75,
    scale: 0.9,
    svgMeta: {
      svgAnchorX: 24,
      svgAnchorY: 205,
      viewBox: [0, 0, 64, 210],
    },
    tags: ["traffic-light", "intersection", "sw-corner"],
  },
  {
    id: "scenery/intersection-traffic-ne",
    assetId: "background/iso-bg-traffic-light",
    assetUrl: "/data/svg-environments/hq/bodega/parts/background/iso-bg-traffic-light.svg",
    kind: "exterior",
    col: 34,
    row: 21,
    anchorMode: "iso-bottom",
    width: 64,
    height: 210,
    zIndex: 11,
    opacity: 0.75,
    scale: 0.9,
    svgMeta: {
      svgAnchorX: 24,
      svgAnchorY: 205,
      viewBox: [0, 0, 64, 210],
    },
    tags: ["traffic-light", "intersection", "ne-corner"],
  },
  {
    id: "scenery/intersection-traffic-se",
    assetId: "background/iso-bg-traffic-light",
    assetUrl: "/data/svg-environments/hq/bodega/parts/background/iso-bg-traffic-light.svg",
    kind: "exterior",
    col: -21,
    row: 21.5,
    anchorMode: "iso-bottom",
    width: 64,
    height: 210,
    zIndex: 11,
    opacity: 0.6,
    scale: 0.9,
    svgMeta: {
      svgAnchorX: 24,
      svgAnchorY: 205,
      viewBox: [0, 0, 64, 210],
    },
    tags: ["traffic-light", "intersection", "se-corner"],
  },
  {
    id: "scenery/intersection-street-sign",
    assetId: "background/iso-bg-street-sign",
    assetUrl: "/data/svg-environments/hq/bodega/parts/background/iso-bg-street-sign.svg",
    kind: "exterior",
    col: 13,
    row: 20,
    anchorMode: "iso-bottom",
    width: 56,
    height: 185,
    zIndex: 10,
    opacity: 0.85,
    scale: 0.85,
    svgMeta: {
      svgAnchorX: 20,
      svgAnchorY: 180,
      viewBox: [0, 0, 56, 185],
    },
    tags: ["street-sign", "intersection"],
  },

  // ── Dock seaboard: structured waterfront along Porter's north edge ──
  // Visual hierarchy (large → small):
  //   1. Dock piling clusters — PRIMARY structural markers, evenly spread
  //   2. Mooring bollards       — SECONDARY posts between pilings
  //   3. Seagull posts          — DYNAMIC accents (life/movement)
  //   4. Rope coils / anchor    — SMALL decorative detail
  //
  // Row bands give depth:
  //   row -0.3 to -0.6  → on-dock decoration (against building)
  //   row -1.2 to -1.8  → pilings at the dock edge
  //   row -3 to -5      → things out in the water (existing boats, bollards)
  //
  // Spread across col -3 (far west) to col 14 (far east beyond the building).

  // ┌─ Far west: dock begins where warehouse pier ends ─
  {
    id: "scenery/dock-piling-far-west",
    assetId: "background/iso-bg-dock-pilings",
    assetUrl: "/data/svg-environments/hq/bodega/parts/background/iso-bg-dock-pilings.svg",
    kind: "exterior",
    col: -11,
    row: -4,
    anchorMode: "iso-bottom",
    width: 120,
    height: 90,
    zIndex: 3,
    opacity: 1,
    scale: 1,
    svgMeta: {
      svgAnchorX: 60,
      svgAnchorY: 90,
      viewBox: [0, 0, 120, 90],
    },
    tags: ["pilings", "dock", "seaboard", "far-west"],
  },
  {
    id: "scenery/dock-seagull-west",
    assetId: "background/iso-bg-seagull-post",
    assetUrl: "/data/svg-environments/hq/bodega/parts/background/iso-bg-seagull-post.svg",
    kind: "exterior",
    col: -1.5,
    row: -0.4,
    anchorMode: "iso-bottom",
    width: 34,
    height: 90,
    zIndex: 6,
    opacity: 1,
    scale: 1,
    svgMeta: {
      svgAnchorX: 17,
      svgAnchorY: 90,
      viewBox: [0, 0, 34, 90],
    },
    tags: ["seagull-post", "dock", "life"],
  },

  // ┌─ West quarter: cluster with pilings + bollard + rope ─
  {
    id: "scenery/dock-piling-west",
    assetId: "background/iso-bg-dock-pilings",
    assetUrl: "/data/svg-environments/hq/bodega/parts/background/iso-bg-dock-pilings.svg",
    kind: "exterior",
    col: 0.5,
    row: -4.1,
    anchorMode: "iso-bottom",
    width: 120,
    height: 90,
    zIndex: 3,
    opacity: 1,
    scale: 1,
    svgMeta: {
      svgAnchorX: 60,
      svgAnchorY: 90,
      viewBox: [0, 0, 120, 90],
    },
    tags: ["pilings", "dock", "seaboard"],
  },
  {
    id: "scenery/dock-bollard-west",
    assetId: "background/iso-bg-mooring-bollard",
    assetUrl: "/data/svg-environments/hq/bodega/parts/background/iso-bg-mooring-bollard.svg",
    kind: "exterior",
    col: 2.5,
    row: -0.3,
    anchorMode: "iso-bottom",
    width: 44,
    height: 52,
    zIndex: 4,
    opacity: 1,
    scale: 1,
    svgMeta: {
      svgAnchorX: 22,
      svgAnchorY: 52,
      viewBox: [0, 0, 44, 52],
    },
    tags: ["bollard", "dock"],
  },
  {
    id: "scenery/dock-rope-coil-west",
    assetId: "background/iso-bg-rope-coil",
    assetUrl: "/data/svg-environments/hq/bodega/parts/background/iso-bg-rope-coil.svg",
    kind: "exterior",
    col: 0.2999999999999998,
    row: -3.2,
    anchorMode: "iso-bottom",
    width: 52,
    height: 36,
    zIndex: 5,
    opacity: 1,
    scale: 1,
    svgMeta: {
      svgAnchorX: 26,
      svgAnchorY: 36,
      viewBox: [0, 0, 52, 36],
    },
    tags: ["rope-coil", "dock"],
  },

  // ┌─ Center: anchor + pilings + bollard + seagull ─
  {
    id: "scenery/dock-piling-center",
    assetId: "background/iso-bg-dock-pilings",
    assetUrl: "/data/svg-environments/hq/bodega/parts/background/iso-bg-dock-pilings.svg",
    kind: "exterior",
    col: 6,
    row: -3.8,
    anchorMode: "iso-bottom",
    width: 120,
    height: 90,
    zIndex: 3,
    opacity: 1,
    scale: 1,
    svgMeta: {
      svgAnchorX: 60,
      svgAnchorY: 90,
      viewBox: [0, 0, 120, 90],
    },
    tags: ["pilings", "dock", "seaboard"],
  },
  {
    id: "scenery/dock-seagull-center",
    assetId: "background/iso-bg-seagull-post",
    assetUrl: "/data/svg-environments/hq/bodega/parts/background/iso-bg-seagull-post.svg",
    kind: "exterior",
    col: -7.3,
    row: -3.9,
    anchorMode: "iso-bottom",
    width: 34,
    height: 90,
    zIndex: 6,
    opacity: 1,
    scale: 1,
    svgMeta: {
      svgAnchorX: 17,
      svgAnchorY: 90,
      viewBox: [0, 0, 34, 90],
    },
    tags: ["seagull-post", "dock", "life"],
  },

  // ┌─ East quarter: pilings + bollard + rope ─
  {
    id: "scenery/dock-bollard-center-east",
    assetId: "background/iso-bg-mooring-bollard",
    assetUrl: "/data/svg-environments/hq/bodega/parts/background/iso-bg-mooring-bollard.svg",
    kind: "exterior",
    col: 8.5,
    row: -0.3,
    anchorMode: "iso-bottom",
    width: 44,
    height: 52,
    zIndex: 4,
    opacity: 1,
    scale: 1,
    svgMeta: {
      svgAnchorX: 22,
      svgAnchorY: 52,
      viewBox: [0, 0, 44, 52],
    },
    tags: ["bollard", "dock"],
  },
  {
    id: "scenery/dock-piling-east",
    assetId: "background/iso-bg-dock-pilings",
    assetUrl: "/data/svg-environments/hq/bodega/parts/background/iso-bg-dock-pilings.svg",
    kind: "exterior",
    col: 10.5,
    row: -4,
    anchorMode: "iso-bottom",
    width: 120,
    height: 90,
    zIndex: 3,
    opacity: 1,
    scale: 1,
    svgMeta: {
      svgAnchorX: 60,
      svgAnchorY: 90,
      viewBox: [0, 0, 120, 90],
    },
    tags: ["pilings", "dock", "seaboard"],
  },
  {
    id: "scenery/dock-rope-coil-east",
    assetId: "background/iso-bg-rope-coil",
    assetUrl: "/data/svg-environments/hq/bodega/parts/background/iso-bg-rope-coil.svg",
    kind: "exterior",
    col: 11,
    row: -3.2,
    anchorMode: "iso-bottom",
    width: 52,
    height: 36,
    zIndex: 5,
    opacity: 1,
    scale: 1,
    svgMeta: {
      svgAnchorX: 26,
      svgAnchorY: 36,
      viewBox: [0, 0, 52, 36],
    },
    tags: ["rope-coil", "dock"],
  },

  // ┌─ Far east: dock continues past the building corner ─
  {
    id: "scenery/dock-bollard-far-east",
    assetId: "background/iso-bg-mooring-bollard",
    assetUrl: "/data/svg-environments/hq/bodega/parts/background/iso-bg-mooring-bollard.svg",
    kind: "exterior",
    col: 12.5,
    row: -0.5,
    anchorMode: "iso-bottom",
    width: 44,
    height: 52,
    zIndex: 4,
    opacity: 1,
    scale: 1,
    svgMeta: {
      svgAnchorX: 22,
      svgAnchorY: 52,
      viewBox: [0, 0, 44, 52],
    },
    tags: ["bollard", "dock"],
  },
  {
    id: "scenery/dock-piling-far-east",
    assetId: "background/iso-bg-dock-pilings",
    assetUrl: "/data/svg-environments/hq/bodega/parts/background/iso-bg-dock-pilings.svg",
    kind: "exterior",
    col: 17.5,
    row: -4,
    anchorMode: "iso-bottom",
    width: 120,
    height: 90,
    zIndex: 3,
    opacity: 1,
    scale: 1,
    svgMeta: {
      svgAnchorX: 60,
      svgAnchorY: 90,
      viewBox: [0, 0, 120, 90],
    },
    tags: ["pilings", "dock", "seaboard", "far-east"],
  },
  {
    id: "scenery/dock-seagull-far-east",
    assetId: "background/iso-bg-seagull-post",
    assetUrl: "/data/svg-environments/hq/bodega/parts/background/iso-bg-seagull-post.svg",
    kind: "exterior",
    col: 9.5,
    row: -3.9,
    anchorMode: "iso-bottom",
    width: 34,
    height: 90,
    zIndex: 6,
    opacity: 1,
    scale: 1,
    svgMeta: {
      svgAnchorX: 17,
      svgAnchorY: 90,
      viewBox: [0, 0, 34, 90],
    },
    tags: ["seagull-post", "dock", "life"],
  },
];

const PORTERS_EXTERIOR_SCENE: HqSceneComposition = {
  buildingId: "building/porters",
  sceneId: "porters-exterior",
  placements: PORTERS_EXTERIOR_PLACEMENTS,
};

// ── Scene lookup ─────────────────────────────────────────────────────────

const EXTERIOR_SCENES: Readonly<Record<string, HqSceneComposition>> = {
  "building/bodega": BODEGA_EXTERIOR_SCENE,
  "building/porters": PORTERS_EXTERIOR_SCENE,
};

function resolveScenePlacementAssetUrl(
  buildingId: string,
  placement: HqStaticPlacementDef,
): HqStaticPlacementDef {
  return {
    ...placement,
    assetUrl: resolveHqEnvironmentAssetUrl(buildingId, placement.assetId) ?? placement.assetUrl,
  };
}

/** Return the exterior scene composition for a building, or undefined if none exists. */
export function getExteriorScene(buildingId: string): HqSceneComposition | undefined {
  const scene = EXTERIOR_SCENES[buildingId];
  if (!scene) {
    return undefined;
  }

  return {
    ...scene,
    placements: scene.placements.map((placement) =>
      resolveScenePlacementAssetUrl(buildingId, placement),
    ),
  };
}
