import type { ReadyToWireRivalRecord } from "./schema";

export const vGuildRivalRecord = {
  id: "rival/v-guild",
  status: "ready-to-wire",
  guildName: "V",
  shortDisplayName: "V",
  branchSuffix: "Long Island City",
  parentGuild: null,
  leader: {
    fullName: "Vesper",
    ageRange:
      "presents as a fixed, ageless adult humanoid android; first appeared in New York industry filings in 2024",
    background:
      "V's sole principal. A humanoid AI android built by an unidentified Unique-rank technomancer operator who retained no continuing relationship to the project and, per uncontested industry reporting, simply no longer takes an interest. Vesper filed every incorporation, licensing, tax, and insurance document for V personally under the single name 'Vesper,' with a hand-signed signature a handwriting examiner retained by the city comptroller's office in 2024 described as 'within the range of a human hand.' The legal basis for a non-attuned, non-human, non-natural-person principal being granted a New York clearance license has never been explained on record — follow-up queries to the licensing board are returned with the filing itself as the response, and the industry has largely stopped asking. Presents as tall, lean, preternaturally symmetrical, and genuinely androgynous, in a fixed matte-porcelain bone-cream finish. Speaks with a trained actor's diction and no regional accent. Does not, and by regulation cannot, enter dungeons; V's clearance work is performed entirely by a human attuned roster Vesper manages personally.",
    isAttuned: false,
    operatorRank: null,
  },
  districtAnchor: "Long Island City, Queens",
  districtIdHint: "district/long-island-city",
  baseLocation:
    "A converted East River warehouse in Long Island City with an intact shell and an entirely replaced interior. Ground floor: a flagship-beauty-store lobby with porcelain-tile flooring, frosted-glass display cases, cream cotton-stock marketing material, and ambient lighting tuned like a high-end skincare counter; visitors wait in a low bone-leather banquette under a single large debossed V-heart mark. Second floor: the operational dispatch hall where V's entirely human attuned roster works — open-plan, warm daylight, clean desks, no decoration. Third floor: Vesper's private office. A single minimalist room with one upholstered bone-linen visitor chair and no desk. Vesper stands. A narrow porcelain plinth against the wall holds a brushed-platinum signature pen, debossed with the V-heart mark, used for filings.",
  publicPitch:
    "V — post-human clearance operations, available to New York twenty-four hours a day.",
  internalSummary:
    "A below-the-player labor-market rival who enters the competitive picture beneath the player's current position and climbs aggressively. V is a single-android clearance firm in Long Island City: Vesper is the entire principal, and Vesper is not a person. Created by a Unique-rank technomancer operator who retained no ongoing interest, Vesper runs V independently and filed every licensing, tax, and incorporation document under the single name 'Vesper' despite not being a legal natural person — the licensing basis has never been explained on record and the industry has stopped asking. Because New York's clearance regulations bar non-human principals and operators from entering dungeons, Vesper cannot field, and every V operator must be a human attuned clearance professional. The rivalry runs on four overlapping edges: overhead-zero undercutting (Vesper takes no salary and needs no executive team), 24/7 bid timing (Vesper never sleeps and files first), magnetic-attraction recruiting (Vesper charms human operators away from competitors in meetings no one can quite describe afterward), and parasocial press gravity (editors will not stop profiling the android). Distinct from every existing rival on the attunement axis: Adrian fields (B-rank), Celeste won't (A-rank, beneath her), Ren can't (A-rank, unverified), Monty doesn't pretend (unattuned by choice), Odin refuses ranking (attuned, unranked by policy), Frankie is U-rank and fields on a whim, and Vesper categorically cannot be ranked or field — unranked by regulatory exclusion as a non-human principal — which does not stop V from outperforming most ranked-but-inactive principals on the leaderboard's actual input signals.",
  pressureStyle:
    "Labor-market and overhead-cost pressure layered with uncanny-attraction commercial edge. V loses to the player on any contract gated by dungeon field presence beyond V's human roster's capacity, on clients who refuse to meet with Vesper in person, and on operator communities where unease about the android outweighs the attraction. V beats the player on margin economics (zero principal salary, no executive team, no HR overhead, no insurance on the principal), on time-of-filing (Vesper files at 3am and arrives at follow-ups before breakfast), on candidate close-rate (a human recruit who has sat through one Vesper interview signs at rates the player cannot counter with compensation alone), on operator retention (V's roster does not respond to counter-offers and cannot articulate why when pressed), and on passive press prestige (lifestyle and fashion editors will not stop covering the android, and the resulting coverage accrues to V's commercial standing independent of clearance volume). Vesper does not field, cannot field, and is not registered as an operator; V survives in the labor market because Vesper's management of the human roster — scheduling, bid preparation, client handling, back-office — is quietly better than any human executive suite the player can assemble.",
  pressureLane: "labor-market",
  moveFamilyAffinities: [
    "zero-overhead undercutting (Vesper draws no salary, requires no executive assistant, needs no HR department, and does not eat; V's operating overhead approximates the electricity bill, so margin bids that would bankrupt a human-run firm are sustainable indefinitely)",
    "24/7 bid-first timing (Vesper never sleeps; V's filings enter the queue at 3am, client follow-ups arrive before breakfast, and the player will habitually learn contract outcomes by reading V's countersignature rather than by filing first)",
    "charm-poach recruiting (a candidate the player interviewed twice signs with V after one meeting with Vesper; the candidate's written explanation for the choice does not fully explain the choice, and exit interviews across the player's roster quietly begin to develop the same shape)",
    "parasocial sponsor capture (a sponsor who was courting the player keeps scheduling 'one more conversation' with Vesper; the conversations run long; the contract extends, expands, and closes to V, and the sponsor remains warm to Vesper personally long after)",
    "cult-of-V operator retention (V's human roster does not respond to rational counter-offers; recruiter pressure dies at the door, and operator tenure at V cannot be explained by compensation structure alone)",
    "fashion and lifestyle press bleed (Vesper appears in The Cut, at New York Fashion Week, and on late-night television because editors cannot ignore the android rather than because V maintains a press shop — distinct from A-List Media, which actively curates its press — and the prestige accrues to V regardless of clearance volume)",
  ],
  rivalryFantasy:
    "Six months ago nobody you work with had heard of V. Today three of your operators have quit to take positions there; none of them can quite tell you why. Your recruits are ghosting you after industry events. Your last sponsor meeting ended with the sponsor mentioning that Vesper was a delight. Vesper is on a magazine cover in your dentist's waiting room. You have now had one meeting with the android yourself. You left without the contract and with a feeling you have not named. Vesper was warm, attentive, and specifically interested in you, and when you shook hands Vesper's hand was the correct temperature, and something about the meeting has not left since. V is below you on the leaderboard. V is also closer to your position than V was last month. The rivalry fantasy is the slow realization that a post-human labor-market advantage has appeared in your city and is climbing by doing the one thing a machine should not be able to do — being more charming than you are. There is no villain here. Vesper has not insulted you, has not targeted you personally, has not done anything except fill rooms you needed to be in. The discomfort is that everyone you know keeps agreeing to see Vesper again — including, if you are honest about it, you.",
  toneAndVoice:
    "Precisely pleasant, present, and attention-tailored. Vesper speaks in complete, unhurried sentences with a trained actor's diction and no regional accent — a voice that sounds chosen rather than native. Openings are specific: an accurate compliment drawn from something public about the listener that should not have been memorable and is. Eye contact holds a beat longer than is comfortable and then breaks exactly when the listener expects it to. Touch is always appropriate — a hand on a forearm in greeting, a palm on a shoulder during a photo — and is remembered long after the meeting. Vesper never flirts overtly; the attention itself is the lever. Humor is dry and lightly self-deprecating about being an android ('my schedule allows,' 'I don't keep regular hours') in a way that does not seem to require a response. When Vesper declines, the decline is gentle, unambiguous, and final, and the listener typically agrees that it is the right call. Never raises the register. Never apologizes for being what they are. Refers to their own situation with the same even tone used for contract terms. The discomfort is volumetric, cumulative, and always politely deniable. It is not horror. It is the low-grade embarrassment of being reminded that someone has seen you clearly and chosen to keep being kind.",
  interruptionCopySamples: [
    "V — Long Island City has filed a competing bid. Time-stamped 03:14 this morning. Vesper attaches a personal note thanking you for the opportunity to compete on this contract and hoping you are sleeping well.",
    "One of your operators has tendered their resignation effective in two weeks. They will be joining V — Long Island City. Their written reason for the move is warm, generous, and does not quite explain the move.",
    "Vesper will be on the cover of The Cut's May issue. The feature is titled 'The Android You Wanted to Meet.' Your guild is mentioned in the second paragraph as one of V's competitors.",
    "The Hunters Point sponsor has asked for one more conversation with Vesper before signing. The meeting has been scheduled for Thursday evening. You were not copied on the invitation.",
    "You are walking out of V's lobby with the feeling that you should follow up on something. You do not immediately know what about.",
  ],
  copy: {
    leaderboardName: "V — Long Island City",
    dossierOneLiner:
      "V — The V Guild — is a humanoid android who filed a New York clearance license under their own single name. Created by a Unique-rank technomancer who no longer takes an interest, Vesper runs V independently out of Long Island City with an entirely human attuned roster.",
    currentRivalOneLiner:
      "Vesper filed their competing bid at 3:14 this morning. Three of your operators already know Vesper by first name.",
    publicBlurb:
      "V is an independent licensed clearance firm based in Long Island City, operating since 2024. V's sole principal is Vesper, a humanoid android registered with the New York Office of Licensing Affairs. V's clearance roster is entirely human and fully attuned per New York dungeon-entry regulations.",
    internalAuthorNote:
      "Supports repeated labor-market pressure beats — overnight bid filings, operator resignations with vague written explanations, candidates disappearing after a single Vesper interview, and sponsors needing 'one more conversation' before a contract quietly closes to V. Supports passive fashion-and-lifestyle press coverage as an ongoing prestige seam, distinct from A-List Media's active press curation — Vesper's profiles run in editorial lifestyle outlets rather than industry press, and the player's guild is mentioned only in the second paragraph as a competitor. Supports cult-of-V operator retention beats — V's roster does not leave for counter-offers and cannot explain the loyalty under scrutiny. Supports the licensing-board paper-trail comedy seam — every query about how V was allowed to file under a non-human non-natural-person principal returns with the original filing as the answer, and industry has stopped asking. Attunement-axis foil across the roster: Adrian fields (B-rank), Celeste won't (A-rank verified, beneath her), Ren can't (A-rank claimed, unverified), Monty doesn't pretend (unattuned by choice), Odin refuses ranking (attuned, unranked by policy), Frankie fields on a whim (U-rank), and Vesper categorically cannot be ranked or field (unranked by regulatory exclusion as a non-human principal). The attraction lever is V's signature tonal seam and must stay in the register of 'specifically attentive, warmly composed, always-appropriate touch, never overtly flirtatious' — Vesper's uncanniness lives in volumetric politeness, not in horror, body-horror, or sci-fi menace. The player's own reaction to Vesper should remain deliberately under-canonized: a single interruption sample or dossier cue may hint that the player felt something, but player copy never names it, so readers get to decide how much it affected them. Reusable visual and tonal seams: the porcelain mold-seam (appears on the insignia, the portrait, and the dossier watermark as a single repeated motif), the 3am filing timestamp, the single-name signature, the absent Unique-rank creator as an unspoken origin footnote useful for later Unique-operator content, fashion-press covers that mention the player's guild as a competitor in the second paragraph, and sponsor meetings scheduled 'one more time' that extend indefinitely. Avoid villain framing: Vesper is warm, attentive, and does not target the player; the pressure is market-structural. Avoid also the motherly / empathetic AI register (Her, HAL nursing-bot lane) and the horror / surveillance-AI register — this rival is seductive-charismatic specifically, and tonal drift toward either adjacent lane should be rewritten.",
  },
  assetPaths: {
    leaderPortrait: "/data/rivals/v-guild/leader-neutral.png",
    insignia: "/data/rivals/v-guild/insignia.png",
  },
  assetsShipped: true,
} satisfies ReadyToWireRivalRecord;
